naver/billboard.js

src/internals/text.js
May seem like useless micro optimization, but just with this simple change my sizable graph redraw went from 6s to 3s.
Each call to getBoundingClientRect() causes forced layout, avoiding when possible can make big difference.
Avoids getBoundingClientRect() call until actually needed - paths that don't need it will not call this function
=> Avoid unnecessary getBoundingClientRect() calls

spec/api.zoom-spec.js, src/api/api.zoom.js, src/internals/shape.js
#16
chart which is bar type didn't zoom because `zoomScale` is not applied.
@netil
=> fix(shape, api.zoom): fix zoom for barchart

karma.conf.js, package.json, spec/api.axis-spec.js, spec/api.data-spec.js, spec/api.focus-spec.js, spec/api.grid-spec.js, spec/api.load-spec.js, spec/api.region-spec.js, spec/api.zoom-spec.js, spec/arc-spec.js, spec/assets/util.js, spec/axis-spec.js, spec/bb-spec.js, spec/class-spec.js, spec/core-spec.js, spec/data-spec.js, spec/domain-spec.js, spec/grid-spec.js, spec/interaction-spec.js, spec/legend-spec.js, spec/shape.bar-spec.js, spec/shape.line-spec.js, spec/title-spec.js, spec/tooltip-spec.js, spec/type-spec.js, spec/zoom-spec.js, src/config/Options.js, src/internals/shape.js, src/internals/shape.line.js
Adjusted test codes to be run in multiple environment
=> Test env update

package.json, webpack.config.js, yarn.lock
#23
- with this plugin, can shrink some bytes with webpack 3.0 scope hoisting
- change webpack's config to es6 syntax
- Result of build files built using webpack 3.0 w/scope hoisting
| file | with CommonJS Tree Shaker | without |
| --- | --- | --- |
| billboard.js | 381,558 | 381,593 |
| billboard.min.js | 170,605 | 170,632 | 
| billboard.pkgd.js | 850,815 | 850,850 |
| billboard.pkgd.min.js | 415,740 | 415,767 |
=> chore(webpack): Add CommonJS Tree Shaker plugin

src/config/Options.js
#79
Add missing ratio option to API
- donut.label.ratio
- pie.label.ratio
=> docs(options.donut,options.pie): Add donut/pie label ratio option api

spec/core-spec.js, src/config/Options.js, src/internals/ChartInternal.js
#56 
To give an alternative option of chart elements rendering.
It add new `clipPath` option which handle `clip-path` property setting on chart element.
=> feat(ChartInternal,Options): Add new clipPath option

spec/core-spec.js, src/config/Options.js, src/internals/ChartInternal.js
Add two new callbacks for before and after initialization.
Not sure if this is what you wanted as it seems a little "easy". Did #55 mean to implement something for beforeInit() and afterInit() as well?
Ref #55
=> feat(ChartInternal,Options): Add before/after initialization callbacks

spec/assets/util.js, spec/legend-spec.js, src/api/api.show.js, src/config/Options.js, src/internals/ChartInternal.js, src/internals/legend.js
#58
- Added updateLegendTemplate() to handle template option
- Split legend item setting to setLegendItem()
- Fixed wrong param call on test helper
```js
legend: {
template: {
bindto: "#legend",
html: "<li style='background-color:{=COLOR}'>{=NAME}</li>"
}
}
```
with above option, will get the result as:
```html
<ul id="legend">
<li style="background-color: rgb(42, 208, 255);" class="bb-legend-item bb-legend-item-data1">data1</li>
...
</ul>
```
=> feat(legend): Implement legend.contents

spec/data-spec.js, src/config/Options.js, src/data/data.js
#8
Chart elements are rendered async, but callback is executed synchronously.
Element selection is buggy and can cause problem.
=> fix(data): Remove selection on data.onmin/max

demo/demo.js, demo/index.html, spec/shape.line-spec.js, src/config/Options.js, src/internals/ChartInternal.js, src/internals/class.js, src/internals/shape.line.js
This option allows lines to be customized with an extra css class, and works like the `color_pattern` option.
```javascript
var chart = bb.generate({
data: {
columns: [
["data1", 30, 200, 100, 400, 150, 250],
["data2", 50, 20, 10, 40, 15, 25]
]
},
line: {
classes: [
"line-class-1",
"line-class-2"
]
},
bindto: "#chart"
});
```
=> feat(shape.line): Add a line_classes option

spec/shape.bar-spec.js, src/axis/bb.axis.js, src/internals/shape.bar.js
#166
Make to use data length, instead of tick elements' size on setting bar's width
=> fix(bar): Adjust bar width regardless tick count limit

README.md
No have issue ticket.
https://naver.github.io/billboard.js/LICENSE <- this link is broken.
So, I change that link to this. https://github.com/naver/billboard.js/blob/master/LICENSE
=> fix(readme): Change broken link about license

spec/bb-spec.js, src/config/Options.js, src/internals/ChartInternal.js
#201
Allow to change the class name for the bind element,
which was fixed for 'bb'.
```js
// current
bb.generate({ ... });
// <div id='chart' class='bb'>
// it provide the current and extended option
bb.generate({
bindto: {
classname: "billboard-js"
}
}
// <div id='chart' class='billboard-js'>
```
=> feat(Options): Add custom classname for bind element

src/config/Options.js
#216
Ordering with data.groups can differ than the non grouped data.
Add note to get rid some unexpected confusion.
=> docs(tooltip): Add note for data.groups

demo/chart.js
None
In the example of the demo page(https://naver.github.io/billboard.js/demo/), I think that double quotes in the key part of JSON hurt readability.
I added <code>.replace(/\"([^(\")"]+)\":/g,"$1:")</code> to JSON.stringify()
This regular expression changes the "key" : "value" to key : "value"
=> docs(demo): Updated JSON key without quotes in demo

spec/axis-spec.js, src/axis/bb.axis.js
#230
At the initialization, transition element can have an incorrect
rendering when non-transition selection is returned.
When the condition met, cancelling the transition is needed.
=> fix(axis): Correct rotated x axis rendering

spec/internals/bb-spec.js, src/internals/ChartInternal.js
#92
On IE11 with IE9 emulation mode, ('ontouchstart' in window) is returning true.
Evaluate inputType.touch to not be empty and change condition as ('ontouchmove' in window)
=> fix(internal): Correct evaluating inputType condition

spec/api/api.zoom-spec.js, spec/interactions/zoom-spec.js, src/api/api.zoom.js, src/config/Options.js
#272
- Fix the x Axis re-scaling
- Reinforce zoom APIs and options description
- Updated to return when param is not given for `.zoom.max()`, `.zoom.min()` and `.zoom.range()`
=> fix(zoom): Correct not to re-scale while zoom is disabled

spec/api/api.data-spec.js, spec/internals/arc-spec.js, src/api/api.data.js, src/data/data.js, src/shape/arc.js
#303, #331
- Fix % value for pie when uses with `padAngle` or `padding` options
- When above options are used, make the ratio calculation to be based on the value not from the rendered angle value.
- Fix to return multiple data values as indicated
=> fix(arc,api): Correct on data representation and handling

demo/demo.js, spec/shape/shape.bar-spec.js, src/axis/Axis.js, src/config/Options.js, src/shape/shape.js
=> feat(option): Intent to ship bar.padding option

package-lock.json, src/internals/color.js
#298
schemeCategory10 differs depend on d3 version: v4(d3-scale), v5(d3-scale-chromatic)
set schemeCategory10 value as separate value to get rid issue.
=> fix(color): Remove importing schemeCategory10

src/api/api.chart.js, src/internals/ChartInternal.js, src/internals/util.js
#404, #347
- Get rid internal event biding, replacing to d3's event binding.
- Reinforce some condition on .destroy() API
=> refactor(internal): Substitute resize event binding

spec/internals/bb-spec.js, src/config/Options.js, src/internals/ChartInternal.js
#429
- Avoid the call of generateWait() when the condition aren't met.
- Change 'onrendered' option's default value to undefined to not fulfill condition for generateWait().
- Timer interval to check transition end, increased from 20 to 50.
=> refactor(ChartInternal): Improve redraw

spec/api/api.zoom-spec.js, src/api/api.chart.js, src/api/api.zoom.js, src/axis/bb.axis.js, src/config/Options.js, src/interactions/interaction.js, src/interactions/zoom.js, src/internals/ChartInternal.js, src/internals/domain.js, src/internals/scale.js, src/internals/util.js, src/shape/line.js, src/shape/shape.js
#177
- Added internal 'getCustomizedScale()' to handle scale updates when zoom occurs and sum with the category offset
- Update default value for zoom events options(onzoomstart, onzoom, onzoomend) to undefined to avoid unnecessary call
- Reset zoom scaling when `.flush()` is called
- Moved 'emulateEvent' to util.js
- And some refactorings
=> fix(zoom): Correct zooming for category axis type

demo/demo.js, demo/simple-sidebar.css, spec/api/api.chart-spec.js, src/internals/ChartInternal.js
- Revert the redrawArc call, it's causing pie not been hide on .transform() api
- Update wrong css rule for axis
=> skip: Fix side effects from the 1.5.0 changes

spec/internals/bb-spec.js, src/api/api.chart.js, src/internals/ChartInternal.js
#466
Fix the side effect from #404.
D3's event binding, behaves removing previous attached.
Updated to keep all previous resize events.
=> fix(event): Correct on resizing all generated charts

spec/shape/shape.line-spec.js, src/data/data.js, src/shape/line.js
#471
- When is rotated, the d3.curveStep() computes isn't applicable.
- Fix on data type conversion for step type
=> fix(line): Correct on rotated step type

spec/shape/shape.line-spec.js, src/data/data.js, src/internals/ChartInternal.js, src/internals/grid.js, src/internals/tooltip.js, src/shape/line.js
#482
Fix for area-range data when contains null data.
I'll be considered as `null` when nulls are indicated as:
```js
data: {
columns: [
["x", "2013-01-01", "2013-01-02", "2013-01-03", "2013-01-04", "2013-01-05", "2013-01-06"],
["data1",
[null, null, null],
null,
[160, 135, 120],
[135, 120, 110],
[180, 150, 130],
[199, 160, 125]
],
["data2",
null,
{high: null, mid: null, low: null},
{high: 230, mid: 220, low: 200},
{high: 210, mid: 200, low: 180},
{high: 220, mid: 210, low: 190},
{high: 200, mid: 180, low: 160}
],
["data3", 130, 140, 200, 150, 210, 150]
],
type: "area-line-range"
}
```
=> fix(area-range): Correct handling null data

spec/internals/color-spec.js, src/internals/color.js
#507
Internal cache isn't shared among different instances.
Use body's property to store pattern value instead.
=> fix(color): Correct the way on setting pattern value

spec/internals/arc-spec.js, src/config/Options.js, src/shape/arc.js
#442
Implement to be multilined using '\n' character.
```js
bb.generate({
gauge: {
width: 30,
max: 100,
expand: true,
label: {
format: function(value) {
return value +"%\nTest\nValue";
}
}
},
data: {
columns: [
["data", 8]
],
type: "gauge"
}
});
```
=> feat(gauge): Enhance display multiline labels

spec/interactions/interaction-spec.js, spec/internals/tooltip-spec.js, spec/shape/shape.point-spec.js, src/shape/point.js
#547
#241 
- Add 'use' tag as valid point type
- Set stroke custom point css prop from none to inherit to be used on css theme
=> fix(tooltip): Fix on ungrouped tooltip showing for custom shape

package.json
Ref #391
Ref #525
Point 'src/core.js' file as main entry, to make import
only used d3 modules for module based work environments
=> fix(dev-env): Update main entry point

package.json, webpack.config.js
Ref #525
Ref #391
Make only root is required with the name of 'd3' and others requiring as it is.
=> chore(dev-env): Improved external module loading build

jsdoc.json, package-lock.json, yarn.lock
Due to the docdash 1.0 update, add some useful options for API doc generation.
This will add search field and some updates.
=> chore(doc): Update jsdoc output options

spec/api/api.chart-spec.js, src/api/api.chart.js
#502
Allow to set null, for cases to set falsy value.
=> skip: allow to set null for .config() api

spec/internals/axis-spec.js, src/internals/ChartInternal.js
#348
When given data is zero and tick count is greater than 1,
limit tick generation count to 1.
=> fix(axis): Correct not to generate unnecessary ticks

spec/internals/tooltip-spec.js, src/config/Options.js, src/interactions/interaction.js, src/shape/line.js
#568
Show overlapped data points tooltip as grouped even tooltip.grouped=false is set.
=> fix(tooltip): Enhancement for overlapped points

spec/api/api.region-spec.js, src/api/api.region.js
#578
Correct side-effect caused by #529
=> fix(api): Fix regions.remove() error

spec/api/api.load-spec.js, src/api/api.load.js, src/internals/cache.js
#626
- Remove unnecessary .hasCaches()
- Add .removeCache()
- Enforce .unload API doc
- Remove cached data when is unloaded
=> fix(api): Remove cached data when .unload() is called

demo/demo.js, spec/internals/data-spec.js, src/api/api.group.js, src/axis/Axis.js, src/config/Options.js, src/data/data.js, src/internals/domain.js, src/internals/scale.js, src/internals/tooltip.js, src/shape/arc.js, src/shape/bar.js, src/shape/radar.js, src/shape/shape.js
#623
- Merged all ratio functions to be done in data
- Add internal .isStackNormalized()
- Implementation for normalize option
=> feat(shape): Intent to ship stack.normalize

src/shape/line.js
#618
Safari & Edge return different x/y value from .getBBox().
Use node's x/y attribute instead.
=> fix(point): Fix custom point hover position

spec/interactions/zoom-spec.js, src/api/api.zoom.js, src/interactions/zoom.js
#654
- Make zoom scale consistent
- Reset transform value for .unzoom()
=> fix(zoom): Maintain zoommed scale on .zoom()

src/api/api.zoom.js, src/data/data.convert.js, src/data/data.js, src/interactions/zoom.js, src/internals/ChartInternal.js, src/internals/domain.js, src/internals/util.js, src/shape/bubble.js, src/shape/radar.js
#708
Removed use of some d3's modules.
- d3-collection is deprecated
- d3-array replace using native APIs
=> refactor(all): Remove use of d3-array & d3-collection

spec/interactions/subchart-spec.js, spec/internals/core-spec.js, spec/internals/data-spec.js, spec/internals/grid-spec.js, src/internals/ChartInternal.js, src/internals/grid.js
#36
not generate nodes for when:
- subchart's clip-path if isn't used
- data.empty.label.text isn't specified
- grid lines aren't specified
=> refactor(all): Decreasing node generation

src/axis/Axis.js, src/axis/AxisRenderer.js, src/axis/AxisRendererHelper.js, src/config/Options.js, src/internals/ChartInternal.js, src/internals/scale.js
#759
- Fixed to not applying transiton when transition.duration is falsy
- Avoid computing max tick width value if domain hasn't been changed.
> This will degrade dramastically on layout/style recalc.
> Left: with this changes / Right: 1.7.1 release
> ![benchmark](https://user-images.githubusercontent.com/2178435/52456497-573ab780-2b98-11e9-83ab-0bfefff7b1d9.gif)
- Simplified .getXAxis()/.getYAxis() arguments numbers
=> fix(axis): Correct axis transition

spec/interactions/interaction-spec.js, src/interactions/interaction.js
#768
- Re-arranged touch event binding calles
- Refactored setOver() to handle over & out functionality
=> fix(data): Correct onover/out callback on touch

demo/demo.js, spec/shape/shape.line-spec.js, src/config/Options.js, src/shape/line.js, types/options.d.ts
#755
Implement `linearGradient` for area type
```js
{
// will generate follwing linearGradient:
// <linearGradient x1="0" x2="0" y1="1">
//    <stop offset="0" stop-color="$DATA_COLOR" stop-opacity="0"></stop>
//    <stop offset="1" stop-color="$DATA_COLOR" stop-opacity="1"></stop>
// </linearGradient>
linearGradient: true,
// Or customized gradient
linearGradient: {
x: [0, 0],  // x1, x2 attributes
y: [0, 0],  // y1, y2 attributes
stops: [
// offset, stop-color, stop-opacity
[0, "#7cb5ec", 1],
// setting 'null' for stop-color, will set its original data color
[0.5, null, 0],
// setting 'function' for stop-color, will pass data id as argument.
// It should return color string or null value
[1, function(id) { return id === "data1" ? "red" : "blue" }, 0],
]
}
}
```
=> feat(area): Intent to ship area.linearGradient

spec/api/api.chart-spec.js, src/api/api.chart.js, src/axis/Axis.js, src/internals/ChartInternal.js
#798
- Split orient changes functionality as separate method
- Make to be called when .flush() is called
=> refactor(axis): Enhance dyanmic axis inner option

src/internals/ChartInternal.js, src/internals/legend.js, src/internals/size.js
- Reduce retrieving unnecessary .updateSize() calls
- Chaged the way on getting chart container's dimension
=> refactor(size): Reduce duplicated dimension call

demo/demo.js, spec/shape/shape.arc-spec.js, src/config/Options.js, src/shape/arc.js, types/options.d.ts
#856
Implement innerRadius to be applicable for each dataset.
```js
bb.generate({
data: {
columns: [
["data1", 30],
["data2", 50],
["data3", 20]
],
type: "pie"
},
pie: {
innerRadius: {
data1: 50,
data2: 80,
data3: 0
}
}
});
```
=> feat(pie): Enhance innerRadius option

demo/demo.js, spec/internals/data-spec.js, src/config/Options.js, src/internals/text.js, types/chart.d.ts, types/options.d.ts, types/tsconfig.json
#871
Implementation of data.labels.colors option
```js
var chart = bb.generate({
data: {
columns: [
["data1", 30, -200, -100, 400, 150, 250],
["data2", -50, 150, -150, 150, -50, -150]
],
labels: {
colors: {
data1: "fuchsia",
data2: "blue"
}
}
}
});
```
=> feat(data): Intent to ship data.labels.colors

spec/internals/tooltip-spec.js, src/internals/tooltip.js
#816 
It wasn't setting proper `<svg>` element to show color in tooltip,
Is a side effect caused by #816.
=> fix(tooltip): Fix handling on color tile

spec/shape/shape.point-spec.js, src/axis/AxisRenderer.js, src/internals/tooltip.js, src/shape/line.js
#897
- Change CSS props set as 'transform' attribute rather than style
property.
- Fix opacity value setting as string type to work on IE9
- For tooltip visibility: add 'visibility' prop to work on IE9
=> fix(point): Correct point expansion on old IEs

spec/internals/data-spec.js, src/config/Options.js, src/internals/ChartInternal.js, types/options.d.ts
#901
- Correct empty label text displaying css prop from 'opacity' to 'display'
- Removed applying .transition() which makes flickering.
=> fix(data): Fix empty label text flickering

demo/demo.js, spec/internals/legend-spec.js, spec/shape/shape.arc-spec.js, src/config/Options.js, src/config/classes.js, src/data/data.js, src/internals/title.js, src/internals/util.js, src/scss/billboard.scss, src/scss/theme/graph.scss, src/scss/theme/insight.scss, src/shape/arc.js, types/options.d.ts
#580
- Implement stack data handling for gauge type
- Implement gauge.title option
- Make multiline text functionality as separate util funciton
=> feat(gauge): Intent to ship stack data

demo/demo.js, spec/interactions/interaction-spec.js, spec/shape/shape.radar-spec.js, src/config/Options.js, src/internals/util.js, src/shape/radar.js
#904
Implement multiline axis text via '\n'.
```js
var chart = bb.generate({
padding: {
top: 20
},
data: {
x: "x",
columns: [
["x", "1st\nPrize", "2nd\nPrize", "3rd\nPrize"],
["data1", 230, 250, 100],
["data2", 150, 150, 230]
],
type: "radar",
labels: true
},
radar: {
axis: {
max: 300
}
}
});
```
=> feat(radar): Intent to ship multiline axis

spec/internals/legend-spec.js, src/internals/legend.js, src/scss/billboard.scss, src/scss/theme/graph.scss, src/scss/theme/insight.scss
#907
- Make custom legend behaves same as normal legend
- Make legend text to be unselectable
=> refactor(legend): Improve custom legend behaves

config/webpack.config.plugin.js, src/api/api.export.js, src/interactions/interaction.js, src/interactions/zoom.js, src/internals/ChartInternal.js, src/internals/browser.js, src/internals/clip.js, src/internals/color.js, src/internals/legend.js, src/internals/size.js, src/internals/tooltip.js, src/internals/util.js, src/shape/arc.js, src/shape/point.js, webpack.config.js
#558
- Make window & document to be referenced from `./src/internals/browser`.
- Move `.isMobile()` to ChartInternal.js' `.convertInputType()`.
- Add output.globalObject option to make webpack's bootstrap from `window`
to `this`.
=> fix(browser): Fix to work on Node.js env

src/internals/ChartInternal.js
#967
Add browser sniffing to determine 'mobile' touch to be distinguished
with the desktop with the touch support.
=> fix(event): Update determination condition

spec/internals/tooltip-spec.js, src/internals/tooltip.js
#972
Correct displaying contents template when tooltip grouped is false.
=> fix(tooltip): Fix on contents template

spec/internals/bb-spec.js, src/internals/Chart.js, src/internals/ChartInternal.js
#994
- Change the order to get primary node elements to be accessible during
onrendered callbacks
- Update jsdoc description to be exposed on navbar
- rename insternal .getChartElements() to .setChartElements()
=> fix(chart): Correct the order to set '$' node values

demo/demo.js, spec/internals/axis-spec.js, src/axis/Axis.js, src/config/Options.js, src/internals/ChartInternal.js, src/internals/util.js, types/axis.d.ts
#915
- Implement y/y2 axes culling
- Fix .sortValue() being falsy when treating 0
```js
axis: {
y: {
tick: {
culling: true
}
},
y2: {
show: true,
tick: {
culling: {
max: 3
}
}
}
}
```
=> feat(axis): Intent to ship y/y2 axis culling

demo/demo.js, demo/simple-sidebar.css, spec/assets/util.js, spec/internals/bb-spec.js, src/api/api.chart.js, src/config/Options.js, src/internals/ChartInternal.js, types/options.d.ts
#1015
- Implement lazy rendering and observe element's visibility by MutationObserver
- Add rendering state variable `Chart.internal.rendered` to determine rendering process status
=> feat(options): Intent to ship render option

spec/internals/data-spec.js, src/internals/text.js, src/internals/util.js
#1026
- Update the condition for y position when all data values are 0
- add .getBoundingRect() to util, to cache element's .getBoundingClientRect() value
=> fix(text): Fix data label y position when all data are 0

spec/api/api.load-spec.js, spec/api/api.region-spec.js, spec/interactions/interaction-spec.js, spec/internals/data-spec.js, src/api/api.load.js, src/config/Options.js, src/data/data.convert.js, src/data/data.load.js
#1031
- Fix headers values to be set after XHR request object is opened
- Add more descritive example and options for: 'data.mimeType' and '.load()'
- Fix .load()'s option 'done' to not be called twice
=> fix(data): Fix header option setting

package-lock.json
#1029 
- Make eslint dependency to be exact on `6.1.0` to avoid upgrade install until the https://github.com/naver/billboard.js/issues/1029#issuecomment-522415676 issue is fixed (is causing nightly build error).
- `eslint 6.2.1` still not solved.
=> chore(dev-env): Degrade eslint to 6.1.0

package-lock.json, package.json
#1029 
eslint 6.2.0 nor 6.2.1 causing `no-unused-vars` check error.
Until is fixed, it should remain using 6.1.0.
=> chore(dev-env): Degrade eslint@6.1.0

spec/interactions/interaction-spec.js, src/interactions/interaction.js, src/interactions/zoom.js
#1056
- Make tooltip touch event binding to be 'capture', because d3-zoom stops event propagation.
- Fix on event rect element redraw for touch environment.
=> fix(tooltip): Fix tooltip work on touch zoom

spec/shape/shape.arc-spec.js, src/config/Options.js, src/shape/arc.js, types/options.d.ts
#1073
- Make background startingAngle to be independent from option.
- Add missing gauge option definition
=> fix(gauge): Fix to not align background startingAngle from option

spec/internals/axis-spec.js, src/axis/Axis.js
#1077
Make the interval of tick value to be rounded for x Axis category type.
The interval value is determined based on below equation,
```js
// to exclude the first and the last tick
count = tickCount - 2;
interval = (end - start) / (count + 1);
```
ex)
- x Axis scale:  0 ~ 6.
> [0, 1, 2, 3, 4, 5]
- Given tick count: 3
```
(5 - 0) / (1 + 1) = 2.5
```
Resulting a float value, which for 'category' type axis will result to omit displaying ticks.
To fix, the interval should be an integer value for 'category' x Axis.
=> fix(axis): Correct on tick count display

spec/interactions/interaction-spec.js, src/config/Options.js, src/interactions/interaction.js, src/shape/line.js, types/options.d.ts, types/types.d.ts
#1100
Pass current element argument to data.onover/out callbacks.
```js
data: {
onover: function(d, element) {
// d - ex) {x: 4, value: 150, id: "data1", index: 4}
// element - <circle> (in case of 'line' type)
...
},
onover: function(d, element) {
...
}
}
```
=> feat(data): Pass element arg for data callbacks

spec/interactions/zoom-spec.js, src/axis/Axis.js
#1106
Make to call .setCulling() when y Axis zoom.rescale is set.
=> fix(zoom): Correct Axis culling on zoom

demo/demo.js, spec/internals/axis-spec.js, src/axis/Axis.js, src/config/Options.js
#1090
Implement axes.domain option for x/y/y2.
```js
axis: {
y: {
axes: [
// axis text value will display based on the domain range
{ domain: [500, 1000] },
{ domain: [0, 500] },
]
```
=> feat(axis): Intent to ship axes.domain

src/internals/tooltip.js, src/scss/billboard.scss, src/scss/theme/graph.scss, src/scss/theme/insight.scss
#1124
- Remove setting 'pointer-events:none' which makes not to respond on click event.
- Add 'user-select:none' prop on default css file for tooltip element.
=> fix(tooltip): Remove 'pointer-events:none' inline set

demo/demo.js, spec/internals/data-spec.js, src/config/Options.js, src/internals/text.js, types/options.d.ts
#1126
Implement labels position to be applicable for each dataset.
```js
labels: {
show: true,
position: {
data1: {x: 3, y: -10},
data2: {x: 3, y: 30}
}
}
```
=> feat(data): Intent to ship data.labels.position dataset

demo/demo.js, spec/internals/bb-spec.js, src/internals/ChartInternal.js
#1132
- Fix the implementation of background option, making background element
to be positioned under the grid, region elements.
- Also make to work for arc types.
=> fix(options): Correct background element's position

types/chart.d.ts
Ref https://github.com/naver/billboard.js/issues/767#issuecomment-547338496
Add missing params definitions for .load()
=> docs(types): Add missing .load() params defs

demo/demo.js, demo/simple-sidebar.css, spec/internals/grid-spec.js, src/api/api.flow.js, src/api/api.tooltip.js, src/config/Options.js, src/config/classes.js, src/interactions/interaction.js, src/internals/ChartInternal.js, src/internals/grid.js, src/plugin/stanford/index.js, src/scss/billboard.scss, src/scss/theme/graph.scss, src/scss/theme/insight.scss, types/options.d.ts
#1154
- Implementation of new grid.focus.x and edge option.
- Fix `.dispatchEvent()` x coordination value to be 0, when axis is rotated.
```js
bb.generate({
data: {
columns: [
["data1", 300, 350, 300, 0, 0, 0],
["data2", 130, 100, 140, 200, 150, 50]
],
axes: {
data1: "y",
data2: "y2"
}
},
axis: {
y2: {
show: true
}
},
tooltip: {
grouped: false
},
grid: {
focus: {
show: true,
y: true,
edge: true
}
}
});
```
=> feat(grid): Intent to ship grid.focus.y

README.md
Github does not have any issue with images loaded over HTTP, because it proxies all images. But the doc website has a mixed content warning due to this badge.
The server is redirecting the HTTP request to HTTPS anyway.
=> Use an HTTPS url for the gzip-size badge

spec/api/api.zoom-spec.js, spec/interactions/zoom-spec.js, src/interactions/interaction.js, src/interactions/zoom.js, src/internals/ChartInternal.js, src/shape/bar.js
#1185
- Fix .getBarW() to update width on zoom interaction
- Make to hold event rect elements in $$.eventRect
- Make to not bind zoom event when subchart is enabled
- Make xx() to handle direct data value argument
=> fix(bar): Bar's width resize according the zoom scale

demo/demo.js, spec/shape/shape.arc-spec.js, src/config/Options.js, src/shape/arc.js, types/options.d.ts
#1189
Implement Donut, Gauge & Pie's expand.rate option
```js
// interface
[donut | gauge | pie] : {
expand: {
rate: 1
}
}
```
=> feat(options): Intent to ship Arc's expand.rate

spec/internals/core-spec.js, src/internals/ChartInternal.js, src/shape/arc.js, src/shape/radar.js
#1194
- Remove transition on radar's polygon definition
- Make onrendered callback for Arcs to be fired after the transitions ends
- Assure .generateRedrawList() to work when redraw list aren't empty or not in transiting state
=> fix(core): Fix onrendered firing time

spec/interactions/zoom-spec.js, src/config/Options.js, src/interactions/zoom.js, types/options.d.ts
#1171
Implement zoom.resetButton.onclick option
```js
zoom: {
resetButton: {
onclick: function(button) {
button; // Reset button element reference
...
}
}
```
=> feat(zoom): Intent to ship zoom.resetButton.onclick

.gitignore, spec/internals/tooltip-spec.js, src/config/Options.js, src/internals/tooltip.js, types/options.d.ts
#1216
Pass 2 arguments to callbacks:
- ctx: current chart instance
- selectedData: current dataset object
```js
tooltip: {
// fires prior tooltip is shown
[onshow | onshown | onhide | onhidden]: function(ctx, selectedData) {
ctx; // current chart instance
// current dataset selected
// ==> [{x: 4, value: 150, id: "data2", index: 4, name: "data2"}, ...]
selectedData;
},
}
```
=> feat(tooltip): Enhancement on callback options

spec/internals/tooltip-spec.js, src/config/Options.js, src/internals/tooltip.js, types/options.d.ts
#1239
Implementation of tooltip.position.unit to set position's unit value as '%'.
```js
tooltip: {
position: {
// the tooltip position(top/left) will be set as '%' rather than 'px' value.
// fit for responsible devices
unit: "%"
}
}
```
=> feat(tooltip): Intent to ship tooltip.position.unit

spec/internals/bb-spec.js, spec/internals/tooltip-spec.js, src/api/api.chart.js, src/config/Options.js, src/internals/ChartInternal.js, src/internals/tooltip.js, types/options.d.ts
#1139
#1243
#1239
- Remove `tooltip.position.unit` option
- Implement auto tooltip x positioning
- Improve on resize function to be invoked with intervals
=> fix(tooltip): Auto pos adjustion for tooltip

spec/internals/bb-spec.js, src/api/api.chart.js, src/internals/Chart.js, src/internals/ChartInternal.js
#1254
- Correct onafterinit callback to not be triggered when chart isn't fully rendered.
- Fix .resize() to not rendere when the chart isn't fully rendered
=> fix(callbacks): Fix triggering in lazy rendering

spec/internals/axis-spec.js, src/axis/Axis.js, src/config/Options.js, src/internals/domain.js
#1251
- Evaluate y tick width when tick.values option isn't set
- Update API doc adding more info for y Axis tick padding
=> fix(axis): Correct y Axis tick padding

spec/interactions/zoom-spec.js, spec/internals/axis-spec.js, src/config/Options.js, src/internals/domain.js, types/axis.d.ts, types/chart.d.ts
#7
Implementation of axis.x.min/max.fit option.
Given `axis.x.min/max` option as below, will make a spaced area on left & right side.
```js
var chart = bb.generate({
data: {
columns: [
["data1", 30, 200, 100, 100, 100],
["data2", 50, 20, 10, 50, 60]
]
},
axis: {
x: {
min: -1,
max: 10
}
}
});
```
The newly implemented `axis.x.min/max.fit` option, will make to fit on bound data range.
```js
axis: {
x: {
min: {
fit: true,
value: -1
},
max: {
fit: true,
value: 10
}
}
}
```
But, in a case that bound data is greater than the min/max value, it will behave as before.
```js
axis: {
x: {
min: {
fit: true,
value: 1
},
max: {
fit: true,
value: 3
}
}
}
```
=> feat(axis): Intent to ship axis.x.min/max.fit

spec/internals/tooltip-spec.js, src/internals/tooltip.js
#1267
Adjust tooltip position for rightest positioned data points to not overlap data points.
=> fix(tooltip): Fix tooltip position on overlapping data point

spec/internals/axis-spec.js, src/axis/Axis.js, src/axis/AxisRenderer.js, src/axis/AxisRendererHelper.js, src/internals/size.js
#1278
- Fix throwing error on setting axis tick translate when tick.rotate option is used
- Fix some side-effects caused by the merge of #1250
=> fix(axis): Fix axis tick rotate translate

spec/internals/domain-spec.js, src/internals/domain.js
https://github.com/naver/billboard.js/pull/1233#issuecomment-595675546
When data are bound to use different axis, it should maintain its axis domain value.
=> fix(axis): Fix for multi axes data bound

.travis.yml, README.md
#1277
As of the deprecation of greenkeeper, remove its integration.
Migrate to [`Snyk`](https://snyk.io/).
=> chore(dev-env): Remove greenkeeper

spec/internals/axis-spec.js, src/axis/Axis.js, src/internals/size.js, src/scss/theme/insight.scss
#1278, https://github.com/naver/billboard.js/pull/1250#issuecomment-601505201
- When there's no data to show, return evaluated tick width size.
- Remove 'Meiryo' font-family from insight theme.
- Remove returning rotate size when no data to show from .getAxisTickRotate().
=> fix(axis): Fix x Axis spacing and legend toggle error

spec/shape/shape.bar-spec.js, spec/shape/shape.line-spec.js, src/shape/bar.js, src/shape/line.js, src/shape/shape.js
#1302
Make area/bar path draw to not surpass x Axis position, if axis.y/y2.min option is set.
=> fix(shape): Fix non-grouped area/bar to be drawn from bottom of x Axis

spec/interactions/interaction-spec.js, src/internals/grid.js
#1306
Add condition to prevent selecting non-existence node to show grid focus.
=> fix(grid): Fix possible error when grid.focus.show set false

config/webpack.config.plugin.js, package.json, src/internals/util.js, src/plugin/stanford/ColorScale.js, src/plugin/stanford/index.js, yarn.lock
#1310
- Remove the use of d3-array, replacing to use internal implementaion
- Update webpack plugin devtool option, to debug w/sourcemap
=> refactor(plugin): Remove the use of d3-array

.dependabot/config.yml, package.json, yarn.lock
#1310
- As of d3-scale v3.x dropping old browser support. To facilitate in general use cases where can’t transpire nor use packaged bundle downgrade d3-scale to v2.x.
- Make ‘d3-scale’ to be ignored from dependabot update
=> refactor(dev-env): Downgrade d3-scale to 2.x

spec/shape/shape-spec.js, src/shape/line.js, src/shape/shape.js
#1316
- Fix side-effect caused by #1304, making to return y Axis base value based on the current y Axis scale value.
- Make sure this to used only non-grouped data and for y Axis min is greater than 0.
=> fix(shape): Fix incorrect area/bar rendering

spec/internals/core-spec.js, src/internals/ChartInternal.js, src/internals/grid.js, src/internals/text.js
#1276
#1343
- Fix the side-effect caused by #1276
- Make functions added to ‘generateWait()’ to be determined as ‘done’ when return true
- rename ‘.updategridFocus()’ to ‘updateGridFocus()’
=> fix(core): Fix handling transition tasks

spec/shape/shape.arc-spec.js, src/data/data.js, src/shape/arc.js
#1376
- Correct data ratio as-is when hiden data are set.
- Added param to .getTotalDataSum() to return subtract hidden data
- Added .getHiddenTotalDataSum() to return hidden data total sum
=> fix(arc): Fix data ratio for stacked gauge

spec/internals/tooltip-spec.js, src/internals/tooltip.js
#1400
Force x/y coordinate to be 0 when it becomes below to 0.
Is to prevent tooltip not be positioned out of viewport.
=> fix(tooltip): Fix tooltip position in narrow size container

src/internals/ChartInternal.js, src/internals/clip.js
Make to generate 'clip-xaxisticktexts' only when axis.x.tick.autorotate option is set to true.
=> refactor(clip): Avoid generate xaxisticktexts defs

spec/internals/axis-spec.js, src/axis/Axis.js
#1429
Force adding a condition for not evaluating x Axis tick size when
domain values are same and also greater than 0.
=> fix(axis): Fix evaluating tick text size

mocha.opts
From the Mocha v8 update, parallel tests is supported.
https://mochajs.org/#parallel-tests
Update mocha options adding '--parallel' flag
=> chore(dev-env): update run mocha in parallel

src/ChartInternal/internals/clip.ts, test/internals/axis-spec.ts, types/axis.d.ts
#1572
- Fix wrong y attribute value when axis is rotated
- Fix wrong interface name for y/y2 definition file
=> fix(axis): fix y axis clip-path coordinates

src/ChartInternal/Axis/AxisRendererHelper.ts, src/ChartInternal/internals/domain.ts, src/ChartInternal/internals/scale.ts, src/config/Options/axis/x.ts, src/config/Options/axis/y.ts, src/config/Options/axis/y2.ts, test/internals/axis-spec.ts, types/axis.d.ts
#1578
Replace the use of d3.scaleLog to d3.scaleSymlog to handle 0(zero) in scale values.
=> feat(axis): Improve log scale to handle 0

src/ChartInternal/internals/legend.ts, test/assets/util.ts, test/internals/legend-spec.ts
#1599
Remove 'bb-legend-item-focused' class and opacity when legend element is clicked.
=> fix(legend): Make legend blurry after click

demo/demo.js, src/Chart/api/tooltip.ts, src/ChartInternal/data/data.ts, src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/interactions/interaction.ts, src/ChartInternal/interactions/zoom.ts, src/ChartInternal/internals/color.ts, src/ChartInternal/internals/tooltip.ts, src/config/Store/State.ts, src/module/util.ts, test/api/load-spec.ts, test/api/tooltip-spec.ts, test/api/zoom-spec.ts, test/assets/module/util.ts, test/assets/util.ts, test/esm/bar-spec.ts, test/interactions/interaction-spec.ts, test/interactions/zoom-spec.ts, test/internals/axis-spec.ts, test/internals/color-spec.ts, test/internals/selection-spec.ts, test/internals/tooltip-spec.ts, test/shape/point-spec.ts, test/shape/radar-spec.ts
#1642
- Enhance on event handling by mitigating event <rect> element
- Do not re-generate and re-bind events when redraw happens
=> feat(interaction): avoid multiple <rect> generation

src/ChartInternal/data/data.ts
#1670
Legacy IE, x & y prop values aren't available from .getBoundingClientRect().
Use left & top prop instead.
=> fix(interaction): fix retrieving event rect position

src/ChartInternal/interactions/eventrect.ts, test/interactions/interaction-spec.ts
#1650
- Bind touch event only for rect element
- Make to unselect if touch happens outside of rect element
=> fix(interaction): bind touch event only for rect element

src/Chart/api/chart.ts, src/ChartInternal/internals/grid.ts, test/interactions/subchart-spec.ts, types/chart.d.ts
#1681
Improve .flush() to reset zomming state when is called programmatically.
=> refactor(api): reset zooming state when .flush() called

src/ChartInternal/interactions/eventrect.ts
#1642
The update of eventRect isn't necessary in all circumstances.
Limit the call only for at initialization & resizing, will reduce
unnecessary call.
=> refactor(interaction): reduce .updateEventRect() call

src/ChartInternal/ChartInternal.ts, src/ChartInternal/interactions/drag.ts, src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/interactions/interaction.ts, src/ChartInternal/internals/selection.ts, src/ChartInternal/shape/point.ts, test/assets/helper.ts, test/assets/util.ts, test/interactions/drag-spec.ts, test/interactions/subchart-spec.ts
#1642
- remove default ‘drag’ module import. It will be imported along with selection module.
- move .setDragStatus() from drag.ts to interaction.ts
- fix draggable selection to work
- fix selected point to be transitioning
=> fix(interaction): correct draggable selection functionaliy

src/ChartInternal/interactions/eventrect.ts, test/internals/tooltip-spec.ts
#1695, #1642
Chart dimension can be updated dynamically.
Having this possibility, the new event <rect> event handling based on the <rect> coordinate, need to be get updated to reflect current dimension.
For this, run <rect> coord update when mouseover/touchstar event is triggered.
=> fix(interaction): Fix wrong tooltip event coordinate

src/Chart/api/chart.ts, test/api/chart-spec.ts
#1695
Update resizing state value when .resize() is called to
prevent when resize.auto=false is set.
=> fix(api): fix resizing event element

src/ChartInternal/interactions/eventrect.ts, test/esm/bar-spec.ts
#1737
- Add prevention condition when handling single x Axis event data
- Update the event reference for touch environment
=> fix(event): Fix handling for single x Axis data

src/Chart/api/tooltip.ts, src/ChartInternal/internals/tooltip.ts, test/api/tooltip-spec.ts
#1753
- When call tooltip.hide(), dispatch 'mouseend' or 'touchend' event to
remove possible pending event from tooltip.show()
- update handling linked charts instances by filtering
=> fix(tooltip): fix to reset pending events from .show()

src/Chart/api/tooltip.ts, test/esm/bar-spec.ts, test/esm/line-spec.ts
#1760
The call of tooltip.hide(), unexpad of circles & bars internal methods are called.
They're extended when line() or bar() modules are imported and called for esm env.
=> fix(zoom): fix throwing TypeError during zoom

src/ChartInternal/interactions/eventrect.ts, test/api/load-spec.ts
#1761
When .updateEventRectData() is called, reset eventReceiver
coords data length to prevent incorrect coords length setting.
=> fix(api): fix tooltip showing when lesser data loaded

src/config/Options/data/axis.ts, src/config/Options/data/data.ts, test/esm/radar-spec.ts
#1765
Make config's 'data_x' field to be appended on data's option,
to be available for all chart types.
=> fix(radar): fix labels showing on esm usage

package.json, src/Chart/api/show.ts, test/api/show-spec.ts
#1758
When dataseries is hidden, set 'display:none' to fix
certain data values of bar shape is not correctly shown
on ie11.
=> fix(shape): shape not showing on ie11

src/module/browser.ts
#1778
Prioritize referencing Node.js' global to prevent reference error for some environment.
```
// the reference order when the prior is undefined.
global -> globalThis -> self -> window -> this
```
=> fix(browser): fix referencing global order

src/ChartInternal/shape/bar.ts, src/ChartInternal/shape/shape.ts, test/shape/bar-spec.ts
#1818
When given data name key includes 'total', it wrongly refers internal
bar width data key where ends not rendering correctly.
To avoid, added '_$' as prefix for internal object key names.
=> fix(bar): fix bar width rendering for 'total' data key

demo/demo.js, src/ChartInternal/shape/arc.ts, src/config/Options/shape/pie.ts, src/config/Store/State.ts, test/api/zoom-spec.ts, test/shape/arc-spec.ts, types/options.d.ts
#1825
Implement pie.outerRadius option.
```js
pie: {
outerRadius: 100,
// or
outerRadius: {
data1: 80,
data2: 120,
...
}
}
```
=> feat(pie): Intent to ship pie.outerRadius

src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/internals/class.ts
fix the duplicated 'bb-event-rect' class setting to event <rect> element.
=> refactor(eventrect): remove duplicated class value setting

src/ChartInternal/interactions/eventrect.ts, test/api/load-spec.ts
#1864
Force to update event rect size when .redrawEventRect() is called.
=> fix(eventrect): fix resizing event rect element after .load()

src/Chart/api/axis.ts, test/api/axis-spec.ts
#1865
The API description states return values, but it wasn't.
Make return axis' label text object when .axis.labels() is called.
```js
const chart = bb.generate({
axis: {
x: {
label: "X Label"
},
});
// before
chart.axis.labels({y: "Y Axis Label"));
//--> does not return any value
// after
chart.axis.labels();
//--> {x: "X Label"}
chart.axis.labels({y: "Y Axis Label"));
//--> {x: "X Label", y: "Y Axis Label"}
```
=> feat(api): make return values for axis.labels()

src/Chart/api/data.ts, src/ChartInternal/internals/legend.ts, src/ChartInternal/internals/redraw.ts, src/config/Store/State.ts, test/api/data-spec.ts
#1888
Issue caused by the use of cached legend dimension value.
To avoid the use of cache, added redraw state value,
to not take cached value during the redraw process.
=> fix(api): fix incorrect legend text positioning

src/ChartInternal/shape/point.ts, src/config/Options/common/point.ts, test/shape/point-spec.ts, types/options.d.ts
#1867
Implement point.opacity option
```js
point: {
// do not set inline 'opacity' css prop setting
opacity: null,
// set every data point's opacity value
opacity: 0.7
}
```
=> feat(point): Intent to ship point.opacity

demo/demo.js, src/ChartInternal/internals/text.ts, src/config/Options/data/data.ts, test/internals/data-spec.ts, types/options.d.ts
#1845
Enhance data.labels.colors option to support callback function.
```js
data: {
labels: {
// call back for label text color
colors: function(color, d) {
// color: the default data label color string
// data: ex) {x: 0, value: 200, id: "data3", index: 0}
....
return d.value > 200 ? "cyan" : color;
}
}
}
```
=> feat(data.labels.colors): Add callback support

webpack.config.js
#1913
As of Webpack v5 transpile using ES6 syntax, needs to
add extra target configuration to support old browser.
Ref. https://webpack.js.org/migrate/5/#need-to-support-an-older-browser-like-ie-11
=> fix(build): suport for legacy browser

src/ChartInternal/internals/domain.ts, test/internals/axis-spec.ts
#1981
Bind the context correctly when 'parseDate' is called
within .getXDomainMinMax()
=> fix(axis): fix axis.x.max error throw

src/Chart/api/zoom.ts, src/ChartInternal/interactions/subchart.ts, src/config/Options/interaction/subchart.ts, test/interactions/subchart-spec.ts, types/options.d.ts
#2037
Implement new option to specify subchart selection range at the initialization.
```js
subchart: {
enabled: true,
init: {
// specify initial range domain selection
range: [2, 3]
}
}
```
=> feat(subchart): Intent to ship subchart.init.range option

src/ChartInternal/Axis/Axis.ts, test/internals/axis-spec.ts
#2038
Refactor .getXAxisPadding() to handle axis.x.padding option,
when value given is number type.
=> fix(axis): Fix axis.x.padding value setting

src/ChartInternal/Axis/Axis.ts, test/internals/axis-spec.ts
#2038,  https://github.com/naver/billboard.js/pull/2042/files#r613857084
Make sure to handle correctly when axis.x.padding value is
given as number or as object.
=> fix(axis): fix handling x padding value

config/webpack/development.js, src/ChartInternal/internals/region.ts, test/api/region-spec.ts, webpack.config.js
#2067
- Insert regions's <g> node to be positioned behind the chart's graph nodes
- Set webpack output.publicPath option due to the webpack-dev-server option remove
=> fix(region): fix region append position

src/ChartInternal/internals/size.ts, test/internals/bb-spec.ts
#2086
When bound element's height specified other than 'px' unit,
determine height value taking same logic as width's.
=> fix(size): enhance applying height value

src/Chart/api/show.ts, src/Chart/api/subchart.ts, src/ChartInternal/Axis/Axis.ts, src/ChartInternal/Axis/AxisRenderer.ts, src/ChartInternal/ChartInternal.ts, src/ChartInternal/interactions/subchart.ts, src/ChartInternal/internals/grid.ts, src/ChartInternal/internals/legend.ts, src/ChartInternal/internals/region.ts, src/ChartInternal/internals/text.ts, src/ChartInternal/internals/tooltip.ts, src/ChartInternal/shape/arc.ts, src/ChartInternal/shape/bar.ts, src/ChartInternal/shape/candlestick.ts, src/ChartInternal/shape/gauge.ts, src/ChartInternal/shape/line.ts, src/ChartInternal/shape/point.ts, src/Plugin/stanford/Elements.ts, test/api/focus-spec.ts, test/api/legend-spec.ts, test/api/show-spec.ts, test/interactions/zoom-spec.ts, test/internals/axis-spec.ts, test/internals/bb-spec.ts, test/shape/area-spec.ts, test/shape/bar-spec.ts, test/shape/line-spec.ts, test/shape/point-spec.ts
#2076
Removed setting css props, which works as same way with default value.
For the following props lists, there's no need to be set explicitly.
- display: block
- visibility: visible
- opacity: 1
- fill-opacity: 1
=> feat(all): contain inline css prop setting

src/Chart/api/load.ts, src/ChartInternal/data/convert.ts, src/ChartInternal/data/load.ts, test/api/export-spec.ts, test/api/load-spec.ts, test/shape/radar-spec.ts, types/chart.d.ts
#2140
Implement data append option for .load() API.
```js
// Given chart
const chart = bb.generate({
data: {
x: "x",
xFormat: "%Y-%m-%dT%H:%M:%S",
columns: [
["x", "2021-01-03T03:00:00", "2021-01-04T12:00:00", "2021-01-05T21:00:00"],
["data1", 36, 30, 24]
]
},
axis: {
x: {
type: "timeseries"
}
}
};
// load new data by appending it.
chart.load({
columns: [
// when existing chart has `x` value, should provide correponding 'x' value.
// with 'append' option, the 'data1' will have `[36,30,24,37]`.
["x", "2021-02-01T08:00:00"],
["data1", 37]
],
append: true
});
```
=> feat(api): Intent to ship append load

src/Chart/api/load.ts, test/api/load-spec.ts
#2121 
When multiple and consecutive loading task w/unload option
are called sequentially in a very short gap, mitigate unproper
rendering by queueing load task using requestIdleCallback().
=> refactor(load): mitigate unproper rendering

src/Chart/api/load.ts
Fix the api documentation to enable working copy-paste.
Fixes: 80767955cedd ("feat(api): Intent to ship append load")
=> docs(api): fix missing comma for append load

src/Chart/api/show.ts, src/ChartInternal/data/data.ts, src/config/Options/data/data.ts, test/internals/data-spec.ts, types/options.d.ts
#2146
Implement data.onshown/onhidden.
These callbacks will be called whenever some data series' visibility changes.
```js
data: {
onshown: function(ids) {
// ids - ["data1", "data2", ...]
},
onhidden: function(ids) {
// ids - ["data1", "data2", ...]
},
}
```
=> feat(data): Intent to ship data.onshown/onhidden

src/Chart/api/flow.ts, src/ChartInternal/Axis/AxisRenderer.ts, src/ChartInternal/Axis/AxisRendererHelper.ts, src/ChartInternal/internals/redraw.ts, test/interactions/zoom-spec.ts
#2140
- Prevent transition selection to throw error
- Make state.redrawing to be set false after redraw calls
=> refactor(axis): prevent transition not found error

src/ChartInternal/Axis/Axis.ts, src/ChartInternal/internals/scale.ts, test/internals/axis-spec.ts
#2186
Make to use UTC scale when axis.x.localtime=false
=> fix(axis): fix handling x axis localtime

src/Chart/api/zoom.ts, src/ChartInternal/ChartInternal.ts, src/ChartInternal/interactions/zoom.ts, src/ChartInternal/internals/domain.ts, src/ChartInternal/shape/line.ts, test/api/export-spec.ts, test/api/zoom-spec.ts, test/interactions/zoom-spec.ts, test/internals/tooltip-spec.ts, test/shape/bar-spec.ts
#2194
Refactor zoom transform and its releated codes.
=> fix(zoom): fix inconsistent zoom on .zoom() -> wheel

src/ChartInternal/Axis/Axis.ts, src/ChartInternal/internals/domain.ts, src/ChartInternal/internals/size.axis.ts, src/config/Options/axis/x.ts, src/config/Store/State.ts, test/internals/axis-spec.ts, types/axis.d.ts
#2246
- Implement axis.x.padding.unit='px'
- Removed axis.getXAxisPadding() substituting by .getXDomainPadding()
- Refactor convert pixel to scale
```js
axis: {
x: {
padding: {
left: 100,
right: 80,
unit: "px"
}
}
}
```
=> feat(axis): Enhance padding to accept px value

src/ChartInternal/internals/tooltip.ts, src/config/Options/common/tooltip.ts, test/api/load-spec.ts, test/internals/tooltip-spec.ts
#2267
Pass position object argument to tooltip.position callback
to facilitate position value control.
```js
tooltip: {
position: function(data, width, height, element, pos) {
// data: [{x, index, id, name, value}, ...]
// width: Tooltip width
// height: Tooltip height
// element: Tooltip event bound element
// pos: {
//   x: Current mouse event x position,
//   y: Current mouse event y position,
//   xAxis: Current x Axis position
// }
return {top: 0, left: 0}
},
}
```
=> feat(tooltip): Enhance tooltip.position passing curr pos

package.json, src/ChartInternal/internals/selection.ts, test/api/selection-spec.ts
#2272
Remove the use of d3-color package and replaces its functionality
by css filter brightness function.
=> refactor(api): Remove d3-color package usage

types/options.d.ts
#2275
- Fix wrong types for data.onshown/onhidden function params
- Add missing newly added(#2270) tooltip.position params types
=> fix(types): fix data.onshown/hidden types

src/ChartInternal/interactions/eventrect.ts, test/internals/tooltip-spec.ts
#2287
Remove unnecessary step-after index update
=> fix(event): make consistent tooltip position on step-after

src/ChartInternal/Axis/AxisRendererHelper.ts, test/internals/axis-spec.ts
#2294
Round y axis starting value to avoid being floating values
=> fix(axis): fix y axis stepSize value

src/ChartInternal/interactions/zoom.ts, test/api/zoom-spec.ts, test/interactions/zoom-spec.ts
#2254
Remove triggering 'onzoomend' when .zoom() is called.
Side-effect caused by #2217
=> fix(zoom): Fix zoomend call on .zoom()

types/chart.d.ts, types/plugin/plugin.d.ts
#2316
Fix wrong type definition for
- .load(), .zoom() callback option
- make prserveAspectRatio option from .export() as optional
- specify Plugin interface context
=> fix(types): Fix wrong type definition

src/ChartInternal/internals/redraw.ts, test/api/grid-spec.ts, test/api/region-spec.ts
#2411
Add withLegend option on .redrawWithoutRescale()
=> fix(api): Fix zoom reset for  regions(), grids() api call

src/ChartInternal/shape/bar.ts, test/shape/bar-spec.ts
#2421
- Make 0(zero) value to not apply Arc path command
- When clipPath=false is set, add clip-path attribute to bar element
=> fix(bar): fix bar radius rendering with clipPath=false option

demo/demo.js, src/ChartInternal/ChartInternal.ts, src/ChartInternal/internals/domain.ts, src/ChartInternal/internals/scale.ts, src/ChartInternal/internals/size.ts, src/config/Options/common/main.ts, test/internals/core-spec.ts, types/options.d.ts
#2367
When set to 'false', will remove padding area completely.
```js
{
padding: false
}
```
=> feat(option): Enhance padding to be removed completely

demo/demo.js, src/Chart/api/data.ts, src/ChartInternal/data/IData.ts, src/ChartInternal/data/data.ts, src/ChartInternal/shape/shape.ts, src/Plugin/sparkline/index.ts, src/config/Options/shape/bar.ts, test/shape/bar-spec.ts, types/options.d.ts
#1687
Implement bar.indices.removeNull option, where make positioning
each bar shape's position on each tick removing nullish values.
ex) When data is given as:
```js
data: {
columns: [
['data1', 4, null, 4],
['data2', null, 3, null],
['data3', 1, 4, 4]
]
}
```
- left: default
- right: with`bar.indices.removeNull=true` option
=> feat(bar): Intent to ship bar.indices.removeNull

src/Chart/api/chart.ts, src/ChartInternal/ChartInternal.ts, src/ChartInternal/interactions/interaction.ts, src/ChartInternal/internals/tooltip.ts, test/api/chart-spec.ts
#2489
Instead of resetting by innerHTML, remove nodes to make sure
nodes to be removed from DOM tree. Also, add unbind all attached events.
=> fix(api): Ensure svg nodes to be removed from memory

src/ChartInternal/shape/shape.ts, test/internals/axis-spec.ts
Update getting y/y2 axes min value.
Side effect caused by #1323
Ref #2503
```js
bb.generate({
data: {
columns: [
["data1", 30, 200, -100],
["data2", 50, -50, 70]
],
type: "bar",
axes: {
data1: "y",
data2: "y2",
}
},
axis: {
y: {
inverted: true
},
y2: {
show: true,
inverted: true
}
}
});
```
From the above option, will be drawn as:
=> fix(axis): Fix bar draw for inverted y/y2 axes

src/ChartInternal/internals/redraw.ts, test/api/zoom-spec.ts
#2531
When grids/regions APIs called, do not update legend,
where makes x's scale update.
=> fix(zoom): Fix unzoom after appeding regions

src/Chart/api/chart.ts, src/Chart/api/subchart.ts, test/api/subchart-spec.ts
#2536 #2534
- Replace calling .reszize() instead of .flush() when show & hide is called.
- Add prevention code on handling subchart's node
=> fix(subchart): Fix axis position on subchart.hide() call

src/ChartInternal/internals/format.ts, src/config/Options/common/tooltip.ts, test/internals/tooltip-spec.ts
#2542
- Revert defaultValueFormat function changes done from d2be8c0
- Add descriptive info on how defaultValueFormat behave on API doc
=> fix(tooltip): revert tooltip.contents' defaultValueFormat

src/ChartInternal/ChartInternal.ts, src/module/util.ts, test/internals/core-spec.ts
#2551
Remove changes to be duplicate clip-pah id value, coming from timestamp value.
Make to be defined from random and timestamp computation.
=> refactor(internal): Reinforce clip-path unique id definition

src/ChartInternal/ChartInternal.ts, src/config/Options/common/main.ts, test/internals/bb-spec.ts, types/options.d.ts
#2587
Implement onclick option
```js
bb.generate({
...,
// will be called when chart area(somewhere of entire svg element) is clicked
onclick: function(event) {
this; // chart instance itself
event; // native event object
}
});
```
=> feat(option): Intent to ship onclick

src/Chart/api/axis.ts, test/api/axis-spec.ts, types/chart.d.ts
#2398
Add capability to reset specified axis range min/max value
```js
chart.axis.min({
x: false,
y: false,
y2: false
});
// shorthand
chart.axis.min(-100);  // will set min of y/y2 as -100
chart.axis.min(false);  // will unset min of y/y2
chart.axis.max({
x: false,
y: false,
y2: false
});
// shorthand
chart.axis.max(1000);  // will set max of y/y2 as 1000
chart.axis.max(false);  // will unset max of y/y2
chart.axis.range({
min: {
x: false,
y: false,
y2: false
},
max: {
x: false,
y: false,
y2: false
},
});
// shorthand
chart.axis.range({
// shorthand, which sets min of y/y2 as -100, max of y/y2 as 10000
min: -100,
max: 10000,
// shorthand, which unset min & max of y/y2
min: false,
max: false
});
```
=> feat(api): Implement axis range reset

src/ChartInternal/ChartInternal.ts, src/ChartInternal/shape/point.ts, test/internals/data-spec.ts
#2609
Make bubble/scatter type circle to be initialized with opacity=0,
and then handle the opacity at the initialization according dataset's visibility option.
=> fix(option): Fix data.hide not working for bubble/scatter type

src/module/util.ts, test/internals/util-spec.ts
#1714
When given datetime specifier mismatch with the given data,
previously logging error about it, but from this commit
will enhance to handle even the mismatch to mitigate strict
data input format.
ex)
Given below option, previously `error` message was logged.
From the enhancement, will not log any `error` and the x value will be parsed as `new Date("2013-01-01 00:00:00");`
```js
bb.generate({
data: {
x: "x",
columns: [
["x", "2013-01-01 00:00:00", "2013-01-02 00:00:00"],
["data1", 30, 200]
]
},
axis: {
x: {
type: "timeseries",
tick: {
format: "%Y-%m-%d" // given specifier mismatch with the given 'x' value.
}
}
},
});
```
=> fix(util): Enhance parsing date string

.github/workflows/ci.yml
#2638
As the Node 12 EOL(Apr. 30, 2022), drop from the CI matrix.
Add v17 instead.
=> chore(ci): Drop node 12 from the matrix

README.md, src/ChartInternal/shape/point.ts, src/module/util.ts
#2637
- Make .inputType() to return 'mouse' if haven't detected any.
- Degrade the use of DOM APIs which isn't supported for legacy browser.
=> fix(point,util): fix syntax to work on legacy browser

src/ChartInternal/shape/bar.ts, test/shape/bar-spec.ts
#2642
In a process where values dynamically change from positive
value to zero, the transition appears wrongly if the Arc command removed from the exist path.
To mitigate, maintain Arc command from path on this data flow.
=> fix(bar): fix bar radius for zero value

src/Plugin/stanford/index.ts, test/plugin/stanford/stanford-spec.ts
#2657
Fix formatting tooltip for timeseries type chart
=> fix(plugin): fix stanford tooltip formatting

src/Plugin/sparkline/index.ts, test/plugin/sparkline/sparkline-spec.ts
#2682
- Make to override padding values when there's no option given and when padding != false.
- Append tooltip node when tooltip is enabled and bind events when is necessary only.
=> fix(plugin): fix sparkline dimension & tooltip

src/ChartInternal/internals/size.axis.ts, test/internals/axis-spec.ts
#2675
Add gap pixels when tickWidth is zero.
=> fix(size.axis): fix truncated axis when has no data

src/ChartInternal/ChartInternal.ts, src/config/Options/common/main.ts, src/module/generator.ts, test/internals/bb-spec.ts
#2650
Implement resize.timer option, where to give alternative option
for controlling timer trigger delay and use requestIdleCallback()
instead.
```js
resize: {
timer: false,  // make to use 'requestIdleCallback()'
timer: 1000 // trigger resize function on delay of 1000ms (default delay is 200ms)
}
```
- default resize(w/200ms delay)
- using 'requestCallbackIdle()
=> feat(resize): Intent to ship resize.timer

src/ChartInternal/Axis/AxisRenderer.ts, src/ChartInternal/internals/grid.ts, test/internals/grid-spec.ts
#2710
Make to use generated ticks for grid display.
```js
bb.generate({
data: {
columns: [
["data1", 100, 50, 150, 200, 100, 350, 58, 210, 80, 126],
["data2", 305, 350, 55, 25, 335, 29, 258, 310, 180, 226],
["data3", 223, 121, 259, 247, 53, 159, 95, 111, 307, 337]
],
type: "line",
labels: true
},
axis: {
y: {
type: "log",
max: 400
}
},
grid: {
y: {
show: true
}
}
});
```
=> fix(grid): Fix y grid to show for log axis type

demo/benchmark/benchmark.js, src/ChartInternal/ChartInternal.ts, src/ChartInternal/internals/color.ts, test/internals/color-spec.ts
- Refactor not appending new element to parse colors from CSS to improve initial render
- Detach extending to ChartInternal
- Add option to load local build on benchmark
=> refactor(color): Refactor getColorFromCss()

src/ChartInternal/Axis/AxisRenderer.ts, src/ChartInternal/internals/grid.ts, test/internals/grid-spec.ts
#2786
fix getting axis.generatedTicks property when isn't available
=> fix(axis): fix undefined error reading generatedTicks

src/config/Options/common/legend.ts, test/internals/grid-spec.ts, test/internals/legend-spec.ts
#2780
Add `legend.contents.template` value to not break when only
`legend.contents.bindto` is specified.
```js
// before: will break throwing error, w/o legend.contents.template option
// after: will work with default legend.contents.template value: 
//   <span style='color:#fff;padding:5px;background-color:{=COLOR}'>{=TITLE}</span>
legend: {
contents: {
bindto: "#tooltip"
}
}
```
=> fix(legend): Add default for legend.contents.template

src/ChartInternal/shape/arc.ts, test/shape/gauge-spec.ts
#2799
Fix gauge's size to be same when label text is hidden
=> fix(gauge): Fix size mismatch w/o gauge multi label text is hidden

src/ChartInternal/data/convert.ts, src/ChartInternal/internals/color.ts, src/ChartInternal/internals/legend.ts, test/internals/data-spec.ts
#2808
Prevent data sorting with old id value
=> fix(data): Fix idConverter error

src/config/Options/common/grid.ts
#2809
Remove default value, which makes counter intuitive
when is used along with grid.y.show=true is set.
=> fix(grid): Remove grid.y.ticks default value

src/ChartInternal/Axis/AxisRenderer.ts, test/internals/grid-spec.ts
Adjust interval for grid lines display when grid.y.ticks is given
ex.
When `axis.y.grid.ticks=5` is given,
- As-is: left
- To-be: right
=> refactor(grid): update threshold for grid interval

demo/demo.js, src/Chart/api/group.ts, src/ChartInternal/shape/shape.ts, src/config/Options/data/data.ts, test/interactions/interaction-spec.ts, test/internals/data-spec.ts, types/options.d.ts
#2813
Implement the way to specify how zero value is treated on groups
Possible values:
- `zero`: 0 will be positioned at absolute axis zero point.
- `positive`: 0 will be positioned at the top of a stack.
- `negative`: 0 will be positioned at the bottom of a stack.
```js
data: {
columns: [
["data1", -11, -11, -11, -11],
["data2", 4, 4, 4, 4],
["data3", 0, 1, 0, -1]
],
type: "area",
order: null,
groups: [
["data1", "data2", "data3"]
],
groupsZeroAs: "positive"
}
```
=> feat(options): Intent to ship data.groupsZeroAs

demo/demo.js, src/ChartInternal/shape/bar.ts, src/ChartInternal/shape/candlestick.ts, src/ChartInternal/shape/shape.ts, src/config/Options/shape/bar.ts, test/shape/bar-spec.ts, types/options.d.ts
#2839
Implement overlapped bar option
```js
bb.generate({
data: {
columns: [
["data1", 80, 150, 100],
["data2", 100, 120, 130],
["data3", 150, 80, 120]
],
type: "bar"
},
bar: {
width: {
data1: 60,
data2: 40,
data3: 20
},
overlap: true
}
});
```
=> feat(options): Intent to ship bar.overlap

types/axis.d.ts
this fixes the issue reported in https://github.com/naver/billboard.js/commit/fb246bc92d328450b185314d5267dfc0862e55d3#r77903654
This is resubmitting #2790 because you modified the patch when "merging" it in https://github.com/naver/billboard.js/commit/1d378e05af25e33d6d50d92dea51db7fd6b411d7, which totally defeats the goal of the patch.
See https://github.com/naver/billboard.js/pull/2676 for the original type checking error that this fixes (if the patch gets merged without reverting the most important part of it, the issue will finally be fixed)
=> fix(types): Fix the type declarations for the y tick format

src/Chart/api/chart.ts, src/ChartInternal/ChartInternal.ts, src/config/Store/State.ts, src/config/config.ts, test/api/chart-spec.ts, test/plugin/sparkline/sparkline-spec.ts, types/chart.d.ts
#2864
Get generation options object from the API call
```js
const chart = bb.generate({
data: {
columns: [
["data1", 80, 150, 100],
["data2", 100, 120, 130],
["data3", 150, 80, 120]
],
type: "bar"
},
bindto: "#chart"
});
// get the options object specified at the initialization
chart.config();
// --> {data: {…}, bindto: '#chart'}
```
=> feat(api): Enhance .config() to return generation options

demo/demo.js, src/ChartInternal/internals/legend.ts, src/config/Options/common/legend.ts, test/internals/legend-spec.ts, types/options.d.ts
#2874
Implement 'circle' shape for legend item tile.
```js
legend: {
item: {
tile: {
type: "circle",  // default 'rectangle'
r: 10,  // setup radius of circle item type
}
}
}
```
=> feat(options): Intent to ship legend.item.tile.type

config/jsdoc/static/doc.css, demo/demo.js, demo/tomorrow.css, src/Chart/api/export.ts, src/ChartInternal/internals/grid.ts, src/module/util.ts, test/api/export-spec.ts, types/chart.d.ts
#2892
Enhance to preserve outlink applied font-family on export.
```js
chart.export({
preserveFontStyle: true
}, function(dataUrl) {
...
}
```
=> feat(api): Enhance .export() to preserve fontStyle

src/ChartInternal/interactions/interaction.ts, test/internals/tooltip-spec.ts
#2901
Make the call only when there's no selected shape.
=> fix(tooltip): fix redundant onxxx callback calls

src/ChartInternal/interactions/interaction.ts, test/interactions/interaction-spec.ts
#2927
Before setting focused state, make sure to remove possible previous focused state by removing "_expanded_" class.
=> fix(interaction): Fix unset focused state

src/ChartInternal/data/data.ts, src/ChartInternal/shape/area.ts, src/ChartInternal/shape/bar.ts, src/config/Options/common/tooltip.ts, test/internals/tooltip-spec.ts, types/options.d.ts
#2921
Make to pass 'ratio' to tooltip.format.value callback for stacked area/bar type.
```js
bb.generate({
data: {
columns: [
["data1", 50, 80, 10],
["data2", 50, 20, 90]
],
type: "bar",
groups: [
["data1", "data2"]
],
},
tooltip: {
format: {
value: function(value, ratio, id, index) {
ratio; // <== will given ratio
}
}
}
})
```
=> feat(tooltip): Enhance passing ratio value for stacked area/bar

demo/demo.js, src/ChartInternal/data/IData.ts, src/ChartInternal/shape/arc.ts, src/config/Options/shape/arc.ts, src/config/Options/shape/gauge.ts, src/config/resolver/shape.ts, test/shape/arc-spec.ts, types/options.d.ts, types/options.shape.d.ts
#2936
Implement option to make corner radius for arc types: donut/gauge/pie/polar
```js
arc: {
cornerRadius: 12,
// can customize corner radius for each data with function callback
//
// The function will receive:
// - id {string}: Data id
// - value {number}: Data value
// - outerRadius {number}: Outer radius value
cornerRadius: function(id, value, outerRadius) {
return (id === "data1" && value > 10) ?
50 : outerRadius * 1.2;
},
// set ratio relative of outer radius
cornerRadius: {
ratio: 0.5
}
}
```
=> feat(arc): Intent to ship arc.cornerRadius

package.json, yarn.lock
Add taffydb module as jsdoc generation fails as:
- FATAL: Unable to load template: Cannot find module 'taffydb'
=> chore(jsdoc): Add taffydb to dev dependency

types/options.shape.d.ts
#2946
Add missing 'id' param definition
=> fix(types): Add missing param definition for gauge.label.format

src/ChartInternal/internals/domain.ts, test/internals/domain-spec.ts
#2962
Fix wrong domain range setting when axis min/max option is set
=> fix(domain): Fix wrong domain range setting

src/ChartInternal/internals/format.ts, test/internals/axis-spec.ts
#2976
Make format function to be called within current instance context
=> fix(axis): fix axis.y/y2.tick.format context error

src/ChartInternal/Axis/Axis.ts, test/internals/axis-spec.ts
#2974
Make calculate tick width size when has no data.
=> fix(axis): Fix axis label overlap when has no data

src/Plugin/stanford/ColorScale.ts, test/plugin/stanford/stanford-spec.ts
#2999
Replace d3-scaleLog to d3-scaleSymLog to handle 0(zero) for scale start value
=> fix(plugin): Fix stanford scale to accept 0 as min value

src/ChartInternal/ChartInternal.ts, src/ChartInternal/internals/clip.ts, src/ChartInternal/shape/treemap.ts
#3035
- side-effect call from the treemap implementation #3012
- revert .initCall() call
=> fix(internals): Fix unexpected initClip() call

src/Chart/api/tooltip.ts, test/esm/donut-spec.ts
#3038
Make optional chaining when calling internal .hideGridFocus() to prevent error from Arc types.
=> fix(api): Fix tooltip.hide() error call for Arc types

src/ChartInternal/data/data.ts, src/ChartInternal/internals/redraw.ts, src/ChartInternal/shape/arc.ts, test/internals/data-spec.ts
#3066
- Make background arc to not draw when has no data to show
- Fix not throw error when empty array is given for data value
=> fix(gauge): fix when has no data

src/ChartInternal/data/IData.ts, src/ChartInternal/data/data.ts, src/ChartInternal/interactions/eventrect.ts, test/internals/data-spec.ts
#3100
- Remove condition to determine as multipleX type
- Make data to be sorted to handle correctly event receiver area
=> fix(data): Fix tooltip event bound when data.xSort=false set

src/ChartInternal/shape/bar.ts, test/shape/bar-spec.ts
#2642
During the path data update with arc command, include arc path data even isn't arc type shape to prevent broken shape rendering during the transition.
=> fix(bar): Fix broken bar shape transition with grouped radius option

demo/demo.js, demo/tomorrow.css, src/ChartInternal/internals/clip.ts, src/ChartInternal/internals/legend.ts, src/ChartInternal/internals/size.axis.ts, src/ChartInternal/internals/size.ts, src/ChartInternal/internals/transform.ts, src/config/Options/common/main.ts, test/internals/axis-spec.ts, test/internals/core-spec.ts, types/options.d.ts
#3118
Implement 'fit' option, which reduce padding as much as possible making chart to fit to the container element.
```js
bb.generate({
padding: "fit",
...
});
```
- Checkout the difference of two chart element's padding. 
- The dotted border is the boundary of the bound element area.
=> feat(padding): Intent to ship padding='fit'

demo/demo.js, src/Chart/api/zoom.ts, src/ChartInternal/Axis/Axis.ts, src/ChartInternal/Axis/AxisRenderer.ts, src/ChartInternal/ChartInternal.ts, src/ChartInternal/data/data.ts, src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/interactions/subchart.ts, src/ChartInternal/interactions/zoom.ts, src/ChartInternal/internals/domain.ts, src/ChartInternal/internals/redraw.ts, src/ChartInternal/internals/scale.ts, src/ChartInternal/internals/size.axis.ts, src/config/Options/axis/x.ts, src/config/Options/axis/y.ts, src/config/Options/axis/y2.ts, test/internals/axis-x-spec.ts, types/axis.d.ts
#3137
Implement inversion option for x axis
```js
data: {
x: "x",
columns: [
// when 'axis.x.inverted=true' is set, x axis and its data will appear as in following order.
// "2023-01-06" -> "2023-01-04" -> "2023-01-03" -> "2023-01-02" -> "2023-01-01"
["x", "2023-01-01", "2023-01-02", "2023-01-03", "2023-01-04", "2023-01-06"],
["data1", 30, 200, 100, 400, 150],
],
},
axis: {
x: {
inverted: true,
type: "timeseries"
}
}
```
=> feat(axis): Intent to ship axis.x.inverted

src/Chart/api/load.ts, src/ChartInternal/data/load.ts, src/config/Options/common/main.ts, src/module/generator.ts, test/api/load-spec.ts, types/chart.d.ts
#3157
Set as default the resizing after .load() or .unload() is called.
To keep backward compatibility, add `resizeAfter` option to on/off this behavior.
```js
// will resize after the load by default
chart.load({ ... });  
// will not resize after the load by default
chart.load({ 
...
resizeAfter: false
}); 
```
```js
// will resize after the unload by default
chart.unload({ ... });  
// will not resize after the unload by default
chart.unload({
...
resizeAfter: false
}); 
```
- Resize by default
- Turn off resize option
=> feat(api): Enhance resizeAfter for .load/unload APIs

src/Chart/api/load.ts, src/Chart/api/zoom.ts, src/module/browser.ts, src/module/generator.ts, src/module/util.ts, test/api/chart-spec.ts, test/assets/module/browser.ts
#3159
Do not override requestAnimationFrame neither requestIdleCallback to prevent any possible side-effects.
=> refactor(browser): update raf, ric to not override global

src/Chart/api/load.ts, src/ChartInternal/data/load.ts, test/api/chart-spec.ts, test/api/load-spec.ts, test/internals/boost-spec.ts
#3157
To keep backward compatibility and prevent some unexpected behavior, set resizeAfter's default to false.
=> refactor(api): make .load/unload() option 'resizeAfter' to default 'false'

src/ChartInternal/internals/region.ts, test/api/chart-spec.ts, test/api/region-spec.ts
#3147 #3037
When grid API is called, empty <rect> elements are appended. Fix to not append unnecessary nodes.
=> fix(grid): fix redundant <rect> appends

src/Chart/api/tooltip.ts, test/api/tooltip-spec.ts
#3187
When x axis is multipleXS type and has zoom scale, use corresponding scale.
=> fix(api): Fix tooltip.show() to work zoomed with xs option

src/ChartInternal/interactions/eventrect.ts, test/api/load-spec.ts
#3194
when data initializes with empty data, do not initialize eventRect and initializes when data is loaded dynamically.
=> fix(api): fix tooltip work for .load() with xs key

demo/demo.js, src/ChartInternal/internals/text.ts, src/config/Options/data/data.ts, test/internals/text-spec.ts, types/options.d.ts
#3237
Implement customizable position function for data labels.
```js
data: {
...
labels: {
show: true,
/**
* The arguments are:<br>
* - `type` coordinate type string, which will be 'x' or 'y'.
* - `v` is the value of the data point where the label is shown.
* - `id` is the id of the data where the label is shown.
* - `i` is the index of the data series point where the label is shown.
* - `texts` is the array of whole corresponding data series' text labels.
*/
position: function(type, v, id, i, texts) {
let pos = 0;
const len = texts.size() / 2 - 1;
if (type === "x" && (i === 0 || i === len)) {
pos = i === 0 ? 20 : -20;
}
return pos;
}
```
=> feat(data): Intent to ship data.labels.position function

package.json
#3221
Fix Plugin class to be imported from the npm package module.
```js
// npm package to export Plugin class 
import Plugin from "billboard.js/src/Plugin/Plugin";
class MyPlugin extends Plugin { .. }
```
=> fix(export): Fix Plugin class import

src/ChartInternal/internals/tooltip.ts, src/scss/billboard.scss, src/scss/theme/dark.scss, src/scss/theme/datalab.scss, src/scss/theme/graph.scss, src/scss/theme/insight.scss, test/internals/tooltip-spec.ts
#3254
- Adjust left position value
- Add `white-space:nowrap;` to prevent line break
=> fix(tooltip): Fix tooltip overflow when right side edge is hovered

src/ChartInternal/internals/legend.ts, src/config/Options/common/legend.ts, test/internals/legend-spec.ts, types/options.d.ts
#1598
This option can control default interaction of legend items
```js
legend: {
item: {
// will disable default interaction (mouse hover effect and click to hide clicked dataseries)
interaction: false,
// when set below callback option value, will work regardless of 'interaction=false' is set
onclick: function(id) { ... },
onover: function(id) { ... },
onout: function(id) { ... }
}
}
```
=> feat(legend): Intent to ship legent.item.interaction

demo/chart.js, demo/demo.js, src/ChartInternal/internals/legend.ts, src/config/Options/common/legend.ts, test/internals/legend-spec.ts, types/options.d.ts
#1404
- Implement double click interaction and option
- Reenforce legend click interaction on API doc
```js
legend: {
item: {
interaction: {
/**
* Set legend item to interact on double click.
*  - **NOTE:**
*    - Double clicking will make focused clicked dataseries only, hiding all others.
*      - for single click case, `click + altKey(Win)/optionKey(Mac OS)` to have same effect.
*    - To return initial state(which all dataseries are showing), double click current focused legend item again.
*      - for single click case, `click + altKey(Win)/optionKey(Mac OS)` to have same effect.
*    - In this case, default `click` interaction will be disabled.
*/
dblclick: true
}
}
}
```
=> feat(legend): Intent to ship legend.item.interaction.dblclick

src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/internals/tooltip.ts, test/internals/tooltip-spec.ts
#3291
- Refactor splitting tooltip positioning methods
- Make tooltip position to update following  mouse event coordinate
=> fix(tooltip): Fix tooltip positioning

src/ChartInternal/data/data.ts, src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/shape/point.ts, test/shape/point-spec.ts
#3293
- Fix closest data point to work with point.sensitivity option
- Split getSensitivity inner function to getPointSensitivity
Before | After
:---: | :---:
=> fix(point): Fix point sensitivity pointer

src/ChartInternal/shape/line.ts, test/shape/line-spec.ts
#3295
Remove 'shape-rendering:crispEdges' for step line to remove rendering issue on Windows
=> fix(line): Fix step line path rendering on Windows

src/Chart/api/load.ts, src/Chart/api/tooltip.ts, src/ChartInternal/data/data.ts, src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/interactions/interaction.ts, src/ChartInternal/internals/redraw.ts, src/ChartInternal/internals/tooltip.ts, src/ChartInternal/shape/arc.ts, src/ChartInternal/shape/radar.ts, test/assets/helper.ts, test/internals/tooltip-redraw-spec.ts, test/internals/tooltip-spec.ts, test/shape/radar-spec.ts
#3305
- Enhance tooltip update dynamically on redraws
- refactoring on handling events
- Improve .tooltip.show() param to accept 'id' for Arc types
> Note: It marked as 'fix' type where isn't a bug. Is to facilitate mark to be added on release item process.
Basically, in a situation where tooltip is displayed, and it happens some dynamic data load(or redraws happens), will reflect updated data to tooltip. 
But when chart has some states not having any data to display it will hide. From that point tooltip will not reflect updated data unless tooltip is shown again.
=> fix(load): Enhance tooltip update on dynamic load

demo/demo.js, src/ChartInternal/internals/region.ts, src/config/Options/common/main.ts, src/config/Options/data/axis.ts, src/scss/billboard.scss, src/scss/theme/dark.scss, src/scss/theme/datalab.scss, src/scss/theme/graph.scss, src/scss/theme/insight.scss, test/api/region-spec.ts, test/internals/rergions-spec.ts, types/types.d.ts
#3319
Implement regions.label
```js
regions: [
{
...
label: {
text: "Regions 1",
x: 50,  // position relative of the initial x coordinate
y: 50,  // position relative of the initial y coordinate
color: "red",  // color string
rotated: true.  // make text to show in vertical or horizontal
},
...
}
]
```
=> feat(regions): Intent to ship regions.label

src/ChartInternal/shape/arc.ts, test/shape/arc-spec.ts
#3321
For interpolation, make sure to be applied only necessary values.
Issue happened because colorish string were interpolated, which transformed
id values as interpolated color string.
=> fix(arc): Fix shape rendering when data id equivalent of color string

babel.config.cjs, karma.conf.cjs, src/ChartInternal/interactions/interaction.ts, src/Plugin/bubblecompare/index.ts, src/Plugin/tableview/index.ts, test/assets/helper.ts, test/plugin/bubble-compare/bubble-compare-spec.ts, test/plugin/tableview/tableview-spec.ts, test/plugin/textoverlap/textoverlap-spec.ts
#3332
- Exclude d3 modules to be transpiled for test build (some d3 code block scope, transpile wrongly and throws error)
- Add test codes for plugins
- Include again textoverlap plugin test(fixed and happened due to the transpile issue)
=> test(plugin): boost test coverage

babel.config.cjs, config/webpack/plugin.cjs, karma.conf.cjs, package.json
#3334
- Set plugin dist files name to contain 'pkgd' as postfix.
- Remove '@babel/plugin-transform-block-scoping' plugin wich transpiles incorrectly
=> chore(build): Rename plugin packaged file name

src/Chart/api/subchart.ts, src/Chart/api/zoom.ts, src/ChartInternal/data/IData.ts, src/ChartInternal/internals/domain.ts, test/api/subchart-spec.ts, test/internals/axis-x-spec.ts, types/chart.d.ts
#3342
Implement .subchart() and .subchart.reset()
```js
const chart = bb.generate({ ... });
// select subchart selection giving domain range
chart.subchart([2, 5]);
// reset subchart selection
chart.subchart.reset();
```
=> feat(api): Intent to ship subchart method

src/ChartInternal/data/data.ts, test/api/export-spec.ts, test/api/flow-spec.ts, test/api/grid-spec.ts, test/api/selection-spec.ts, test/api/tooltip-spec.ts
#3333
Enforce test coverage under 90%
=> test(api): Increase test coverage for APIs

src/ChartInternal/Axis/AxisRendererHelper.ts, src/ChartInternal/data/convert.helper.ts, src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/interactions/flow.ts, src/ChartInternal/interactions/interaction.ts, src/config/Options/data/data.ts, test/api/category-spec.ts, test/api/flow-spec.ts, test/interactions/drag-spec.ts, test/interactions/interaction-touch-spec.ts, test/internals/data-convert-spec.ts, test/shape/treemap-spec.ts
#3333
- Reinforce test coverage for interaction related codes
- Remove unused ‘else’ condition block from .generateTicks()
- Remove unused ‘jsonTreemp’ module
=> test(interaction): Increase test coverage for interactions

src/ChartInternal/internals/clip.ts, src/config/Options/axis/x.ts, test/internals/title-spec.ts
#3364
Adjust x axis' <clipPath> height to prevent axis being hidden
=> fix(clip): Fix x axis hide on title.bottom

src/Chart/api/category.ts, test/api/category-spec.ts
#3365
Fix to return indexed values when .categories() is called for indexed x axis type
=> fix(api): Fix to return indexed categories

src/ChartInternal/internals/text.ts, src/ChartInternal/internals/tooltip.ts, src/config/Options/common/tooltip.ts, src/module/util.ts, test/internals/text-spec.ts, test/internals/tooltip-spec.ts, types/options.d.ts
#3369
Fix tooltip initial call to call .tooltip.show() api to follow internal flow process
=> fix(tooltip): Fix tootip display on tooltip.init

src/ChartInternal/internals/tooltip.ts, src/config/Options/common/tooltip.ts, test/internals/tooltip-spec.ts
#3371
- Unify the call of sanitize for all formatter function
- Fix the unnecessary call and pass correct arguments for bar range type
=> fix(tooltip): Fix tooltip.format.value call

src/ChartInternal/interactions/eventrect.ts, test/internals/tooltip-spec.ts
#3396
- Reinforce test case
- Add conditional on calling .setTooltipPosition()
=> test(tooltip): Add tests for tooltip.show=false case

demo/demo.js, src/ChartInternal/internals/color.ts, src/ChartInternal/shape/point.ts, src/config/Options/common/point.ts, src/config/Options/shape/area.ts, src/config/Options/shape/bar.ts, test/shape/point-spec.ts, types/options.d.ts, types/options.shape.d.ts
#3405
Implement point.radialGradient option
```js
point: {
// apply radial gradient with default value
radialGradient: true,
// or apply radial gradient with customized value
radialGradient: {
cx: 0.5,
cy: 0.5,
r: 0.5,
stops: [
[0.3, "#fff", 0.8],
[0.6, function(id) { return id === "data1" ? this.color(id) : "green"; }, 0.35],
[1, null, 1]
]
}
}
```
=> feat(point): Intent to ship point.radialGradient

test/shape/point-spec.ts
#3333
Add test case for custom point
=> test(point): Add custom point test

demo/demo.js, src/ChartInternal/internals/tooltip.ts, src/config/Options/common/tooltip.ts, test/internals/tooltip-spec.ts, types/options.d.ts
#3434 
Enhance providing y axis position value or function for tooltip.position callback argument
```js
tooltip: {
position: function(data, width, height, element, pos) {
// pos: {
//   x: Current mouse event x position,
//   y: Current mouse event y position,
//   xAxis: Current x Axis position (the value is given for axis based chart type only)
//   yAxis: Current y Axis position value or function(the value is given for axis based chart type only)
// }
// yAxis will work differently per data lenghts
// - a) Single data: `yAxis` will return `number` value
// - b) Multiple data: `yAxis` will return a function with property value
// a) Single data:
// Get y coordinate
pos.yAxis; // y axis coordinate value of current data point
// b) Multiple data:
// Get y coordinate of value 500, where …
```
=> feat(tooltip): Provide y position for tooltip position callback

src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/shape/point.ts, test/interactions/interaction-spec.ts, test/shape/point-spec.ts
#3466
when point.senstivity='radius' is set, the conditional checking distance not work. When the value is 'radius' make conditional to work with node's radius value instead.
=> fix(point): Fix data.onclick not called when point.senstivity is radius

src/ChartInternal/interactions/zoom.ts, test/interactions/zoom-spec.ts
#3470
Fix zoom event binding error when initialized with empty data.
=> fix(zoom): Fix initial error empty data with zoom

src/ChartInternal/internals/size.ts, src/ChartInternal/internals/tooltip.ts, test/internals/text-spec.ts, test/internals/tooltip-spec.ts
#3473
Reflect padding top/left option on tooltip positioning.
=> fix(tooltip): Fix wrong tooltip position with padding option

src/ChartInternal/interactions/interaction.ts, src/config/Options/axis/x.ts, src/config/Options/data/axis.ts, test/api/tooltip-spec.ts, test/internals/tooltip-spec.ts
#3476
- Adjust y coordinate for event on rotated axis
- Update d3's format specifier doc link
=> fix(tooltip): Fix wrong .tooltip.show() on rotated axis

src/ChartInternal/internals/size.ts, test/esm/donut-spec.ts
https://github.com/naver/billboard.js/issues/3473#issuecomment-1781091685
Side effect caused by #3475.
The condition set where valid only for axis based chart
=> fix(tooltip): Fix tooltip error on Arc type

src/ChartInternal/data/data.ts, src/ChartInternal/internals/format.ts, src/ChartInternal/internals/text.ts, src/ChartInternal/shape/arc.ts, src/ChartInternal/shape/shape.ts, test/internals/text-spec.ts
#3495
Handle ranged data from bar/AreaRange type to render data labels text
```js
bb.generate({
data: {
columns: [
["data1", 
[150, 140, 110],
[155, 130, 115],
[160, 135, 120],
],
["data2", [230, 340], 200, [-100, -50]]
],
types: {
data1: "area-line-range",
data2: "bar"
},
labels: true
}	
});
```
=> fix(labels): Fix data.labels rendering for ranged data

demo/index.html, src/ChartInternal/Axis/Axis.ts, src/ChartInternal/internals/size.axis.ts, src/ChartInternal/internals/size.ts, test/internals/axis-spec.ts
#3499
Fix side-effect of #3433, where removed x axis tick overflow computation
=> fix(axis): Fix x axis autorotate option applies

src/ChartInternal/internals/format.ts, test/internals/text-spec.ts
#3506
Add handling object data type for formatting
=> refactor(format): Add object type handling

src/ChartInternal/internals/format.ts, src/ChartInternal/internals/tooltip.ts, test/internals/tooltip-spec.ts
#3507
- Make format function called once for range(array) data type
- Update on defaultValueFormat to handle array type value also.
```js
bb.generate({
data: {
columns: [
["data1", [100, 250], 30]
],
type: "bar"
},
tooltip: {
format: {
value: function (value, ratio, id, index) {
// when value is ranged type, "value" argument will be an array
// x0: value => [100, 250]
// x1: value => 30
}
}
}
});
```
=> fix(tooltip): Fix tooltip.format.value arg for bar range data

src/ChartInternal/interactions/interaction.ts, src/ChartInternal/shape/radar.ts
Event binding done unefficiently and called whenever redraws happens.
Make event binding done in delegation mode.
=> refactor(radar): Delegate event binding

.eslintrc, demo/demo.js, src/ChartInternal/Axis/AxisRenderer.ts, src/config/Options/axis/x.ts, test/api/export-spec.ts, test/internals/axis-x-spec.ts, types/options.d.ts
#3552
Implement tick text inner option
```js
axis: {
x: {
tick: {
text: {
inner: true
// or specify each position of the first and last tick text
inner: {
first: true,
last: true
}
}
}
}
}
```
=> feat(axis): Add x.tick.text.inner option

src/ChartInternal/internals/tooltip.ts, src/ChartInternal/internals/type.ts, test/internals/tooltip-spec.ts
#3575
Update tooltip positioning to not interfere shape reading and also adjust tooltip content to not be interfered from mouse cursor.
Types affected are: Pie, Gauge, Donut, Radar and Treemap.
Before | After 
:---: | :---:
=> fix(tooltip): Fix tooltip position from interference

src/ChartInternal/data/data.ts, src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/internals/type.ts, src/module/util.ts, test/assets/module/util.ts, test/internals/tooltip-spec.ts, test/internals/util-spec.ts
#3592
Reflect current scroll position(body and container scroll also) for correct data selection on tooltip show
Before | After
:---: | :---:
=> fix(tooltip): Fix wrong tooltip selection on browser scroll change

demo/demo.js, src/ChartInternal/shape/arc.ts, src/ChartInternal/shape/gauge.ts, src/config/Options/shape/gauge.ts, test/shape/gauge-spec.ts, types/options.shape.d.ts
#2125
Implement enforceMinMax option, which will make data to be displayed in a range of min/max value even value is out of range
```js
gauge: {
// enforce min/max value.
// when given value < min, will render as empty value.
// when value > max, will render to given max value not surpassing it.
enforceMinMax: true,
min: 50,  // when given value is 30, gauge will render as empty value.
max: 100. // when given value is `120`, gauge will render till 100, not surpassing max value.
}
```
Example of `gauge.enforceMinMax=true`:
when `value=30`, `gauge.min=50` | when `value=120`, `gauge.max=100` | 
:---: | :---: |
not reached min value, so do not draw | surpassing max value, so render till max value
=> feat(gauge): Intent to ship gauge.enforceMinMax

src/module/util.ts, src/scss/billboard.scss, src/scss/theme/dark.scss, src/scss/theme/datalab.scss, src/scss/theme/graph.scss, src/scss/theme/insight.scss, src/scss/theme/modern.scss, test/assets/common.css, test/internals/rergions-spec.ts
#3611
update ".bb-region rect" rule to not interfere applying regions.class rule
```css
/* before 3.10 */
.bb-region {
fill: steelblue;
fill-opacity: .1;
}
/* 
3.10+
previous css rule updated as below, because "fill-opacity" property is affect all descendant elements(like text).
*/
.bb-region {
rect {
fill: steelblue;
fill-opacity: .1;
}
}
```
will be updated as 
```css
.bb-region {
fill: steelblue;
/* it still remains possibility to not take effect, when regions.class='some' contains fill-opacity property */
/* in that case, needs consider specifity ex.: .some rect { fill:red; fill-opacity: 0.5 } */
rect {
fill-opacity: .1;
}
}
```
=> fix(regions): Fix applying regions class

demo/demo.js, src/ChartInternal/shape/arc.ts, src/config/Options/shape/gauge.ts, src/config/Options/shape/pie.ts, test/shape/gauge-spec.ts, types/options.shape.d.ts
#3633
Implement gauge.label.ratio option
=> feat(gauge): Intent to ship gauge.label.ratio

demo/demo.js, demo/simple-sidebar.css, demo/tomorrow.css, src/ChartInternal/data/data.ts, src/ChartInternal/internals/size.ts, src/ChartInternal/internals/transform.ts, src/ChartInternal/shape/arc.ts, src/ChartInternal/shape/gauge.ts, src/config/Options/shape/arc.ts, src/config/classes.ts, test/shape/arc-rangeText-spec.ts, test/shape/arc-spec.ts, test/shape/gauge-spec.ts, types/options.shape.d.ts
#2120
Implement new arc.rangeText option, which can display a range in Arc shape.
```js
arc: {
rangeText: {
values: [15, 30, 50, 75, 95],
unit: "%", (default: 'absolute')
fixed: false, // only available for gauge chart
format: function(v) {
return v === 15 ? "Fifteen" : v;
},
position: function(v) {
return v === 15 ? {x: 20, y: 10} : null; // can return one props value also.
},
position: {x: 10, y: 15},
position: {x: 10}
}
}
```
Gauge | Donut
:---: | :---:
=> feat(arc): Intent to ship arc.rangeText

src/ChartInternal/data/load.ts, src/ChartInternal/shape/point.common.ts, test/internals/legend-spec.ts
#3660
when legend.usePoint is set with custome point,
remove element added to <defs> on unload
=> fix(legend): Remove def element added on unload

src/ChartInternal/internals/clip.ts, test/internals/core-spec.ts
#3684
Remove ie9 conditional and make setting clip-path's url() value to specify id value without setting full domain
=> fix(clip): Remove setting full domain url

demo/demo.js, src/ChartInternal/Axis/Axis.ts, src/ChartInternal/ChartInternal.ts, src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/internals/color.ts, src/ChartInternal/internals/grid.ts, src/ChartInternal/internals/text.ts, src/ChartInternal/shape/arc.ts, src/ChartInternal/shape/polar.ts, src/config/Options/axis/axis.ts, src/config/Store/Element.ts, src/config/classes.ts, src/scss/billboard.scss, src/scss/theme/dark.scss, src/scss/theme/datalab.scss, src/scss/theme/graph.scss, src/scss/theme/insight.scss, src/scss/theme/modern.scss, test/internals/axis-spec.ts, types/axis.d.ts
#3603
Implement realtime coordinate axis tooltip
```js
axis: {
tooltip: true, // default background color is
// set backgound color for axis tooltip texts
tooltip: {
backgroundColor: "red",
// set differenct backround colors per axes
// NOTE: In this case, only specified axes tooltip will appear.
backgroundColor: {
x: "green",
y: "yellow",
y2: "red"
}
}
}
```
=> feat(axis): Intent to ship axis.tooltip

demo/demo.js, src/ChartInternal/data/data.ts, src/ChartInternal/internals/grid.ts, src/config/Options/axis/x.ts, test/internals/axis-x-spec.ts, types/axis.d.ts
#3764
Implement multiple xs interact as single x
```js
axis: {
x: {
forceSingle: true
}
}
```
Working example:
- `scatter` type interacting as single x
=> feat(axis): Intent to ship axis.x.forceAsSingle

src/ChartInternal/shape/treemap.ts, test/assets/util.ts, test/shape/treemap-spec.ts
#3777
when given bindto element doesn't exist, will append node internally, but generating treemap data will throw `parent.ownerDocument` error. Fix waraping treemap data in array.
=> fix(treemap): Fix generation w/non-exist node

src/module/util.ts
#3798
Apply to fix weired evaluation from the browser.
Same logic splitted into two different condition, where evaluating within Array.some() give different result.
=> fix(util): Update inputtype determination code

src/ChartInternal/interactions/zoom.ts, src/module/util.ts
#3791
- Remove unused mouse wheel event bind, where added as part of workaound for chrome
- Apply code format
=> fix(zoom): Remove unused wheel listener

demo/demo.js, src/ChartInternal/shape/shape.ts, src/config/Options/shape/bar.ts, test/shape/bar-spec.ts, types/options.shape.d.ts
#3820
Implement bar.width to accept function where can adjust bar's width
```js
// or specify width callback. The callback will receive width, targetsNum, maxDataCount as arguments.
// - width: chart area width
// - targetsNum: number of targets
// - maxDataCount: maximum data count among targets
width: function(width, targetsNum, maxDataCount) {
return width / (targetsNum * maxDataCount);
}
```
=> feat(bar): Enhance bar width to adjust from callback

src/ChartInternal/internals/scale.ts, src/ChartInternal/shape/line.ts, src/config/Options/shape/bar.ts, test/internals/rergions-spec.ts
#3790
Prevent dashed lines coordinates to overflow
Before | After the fix
:---: | :---:
```js
// generation option used for screenshot example
bb.generate({
size: {
width: 640,
height: 480
},
data: {
columns: [
["data1", 30, 200, 100, 400 , 150, 250, 30]
],
type: "line",
regions: {
data1: [
{
start: 1,
end: 2,
style: {
dasharray: "5 3"
}
},
{
start: 3,
end: 4,
style: {
dasharray: "10 5"
}
}
]
}
},
axis: {
y: {
show: false
}
},
point: {
show: false
},
zoom: {
enabled: true
}
});
```
=> fix(regions): Mitigate broken dashed lines rendering

src/ChartInternal/data/data.ts, src/ChartInternal/internals/scale.ts, src/ChartInternal/shape/line.ts, src/config/Options/data/axis.ts, test/internals/data-spec.ts, test/internals/rergions-spec.ts
Ref 
#3830 #3790
Improve dashed line rendering using css instead path command. Will render same way for nullish value.
Multiple path command | Single path command
:---: | :---:
```sh
M5,232.59188034188037L95,136.3311965811966M99.1850983903491,139.55194620927864L104.28196148658054,142.77269583736071M109.37882458281199,145.99344546544276L114.47568767904343,149.21419509352484M119.57255077527489,152.4349447216069L124.66941387150631,155.65569434968896M129.76627696773778,158.87644397777103L134.8631400639692,162.0971936058531M139.96000316020064,165.31794323393515L145.0568662564321,168.53869286201723M150.15372935266356,171.75944249009927L155.250592448895,174.98019211818138M160.34745554512645,178.20094174626342L165.44431864135788,181.4216913743455M170.5411817375893,184.64244100242755L175.6380448338 …
```
=> feat(regions): Enhance regions rendering

src/ChartInternal/interactions/zoom.ts
#3856
As of Safari needs bind wheel event to svg element, prior within element, apply workaround to Safari desktop only
=> fix(zoom): Fix zoom wheel interaction

demo/demo.js, src/ChartInternal/internals/legend.ts, src/config/Options/common/legend.ts, test/internals/legend-spec.ts, types/options.d.ts
#3663
When data.names option is specified, provide original data id to format callback
```js
bb.generate({
data: {
names: {
"data1": "Detailed Name",
"data2": "Name Detailed"
},
columns: [
["data1", 71.4],
["data2", 10],
],
type: "gauge"
},
legend: {
format(id, dataId) {
return id === "Name Detailed" ? dataId : id;
},
tooltip: true
}
});
```
=> feat(legend): Provide original data id in format callback

.github/workflows/ci.yml, package.json, src/ChartInternal/internals/legend.ts, src/ChartInternal/internals/size.ts, test/assets/util.ts, test/internals/padding-spec.ts, test/shape/arc-needle-spec.ts
#3872
On gettting legend's height, make to use internal legend height value when padding fit mode is used
=> fix(size): Fix legend overflows with padding fit mode

src/ChartInternal/data/load.ts, src/ChartInternal/interactions/zoom.ts, test/interactions/zoom-spec.ts
#3878
Fix wrong domain value setting when .load() API is called after zoom and unzoom
=> fix(zoom): Fix unzoom after dynamic data load

src/ChartInternal/Axis/AxisRendererHelper.ts, test/api/export-spec.ts, test/internals/axis-spec.ts
#3881
Do not call .getBBox() for empty node
=> fix(axis): fix error when showing tick only

src/Chart/Chart.ts, src/ChartInternal/ChartInternal.ts, src/config/Options/common/main.ts, src/module/error.ts, src/module/util.ts, test/assets/module/util.ts, test/internals/bb-spec.ts
#3106
Make to initialize when chart element isn't visible, but render.lazy=false is set
=> feat(render): Add forced init option on lazy rendering

src/ChartInternal/Axis/AxisRenderer.ts, src/ChartInternal/Axis/AxisRendererHelper.ts, src/config/Options/axis/axis.ts, test/api/axis-spec.ts, test/internals/axis-spec.ts, types/axis.d.ts
#3889
Implement axis text's size evaluation option.
New `axis.evalTextSize` option has three different usage options.
```js
axis: {
// 1: default, which will memoize evaluated axis text size
evalTextSize: true,
// 2: will evaluate the dimension of axis text size every time.
evalTextSize: false,
// 3: customize dimension evaluator
evalTextSize: function(text) {
...
return {width, height):
}
}
```
=> feat(axis): Intent to ship axis.evalTextSize

demo/chart.js, demo/demo.js, src/ChartInternal/ChartInternal.ts, src/ChartInternal/internals/size.ts, src/config/Options/common/main.ts, test/internals/bb-spec.ts, types/options.d.ts
#3893
Implement auto resize based on viewBox attribute
```js
resize: {
auto: "viewBox"
}
```
resize.auto=true | resize.auto='viewBox'
:---: | :---:
=> feat(resize): Intent to ship resize.auto='viewBox'

src/ChartInternal/Axis/AxisRendererHelper.ts, src/ChartInternal/interactions/zoom.ts, test/api/zoom-spec.ts, test/internals/bb-spec.ts
#3895
- When given zoom-in range isn't handled, do not perform next steps
- Initialize drag zoom related event binding when only 'drag' type is specified
=> fix(zoom): Prevent error for out of range

src/ChartInternal/internals/legend.ts, src/config/Options/common/legend.ts, test/internals/legend-spec.ts, types/options.d.ts
#3897
Pass visibility state argument to event callbacks
```js
legend
item: {
onclick: function(id, visible) {
// toggle based on the data visibility
this[visible ? "hide" : "show"](id);
},
onover: function(id, visible) { ... },
onout: function(id, visible) { ... },
}
}
```
=> feat(legend): Pass visibility state to legend item's event callback

src/ChartInternal/data/IData.ts, src/ChartInternal/shape/bar.ts, test/shape/bar-spec.ts
#3903
clip surpassing shape area to mitigate visualization of value
=> fix(bar): fix representation of radius for small data

src/ChartInternal/shape/point.ts, test/shape/point-spec.ts
#3912
Fix to consider point.sensitivity as function value when determining mouse pointer is within the point
=> fix(point): fix data.onclick working with sensitivity function

src/ChartInternal/shape/point.ts, test/shape/point-spec.ts
Reinforce test when point.sensitivity is given as function
=> test(point): update test for point.sensitivity

src/config/Options/shape/gauge.ts, types/options.shape.d.ts
#3918
Currently enforceMinMax option works for single data series only. Make sure clarifying the use of this option
=> docs(gauge): Clarify enforceMinMax option

demo/demo.js, src/Chart/api/regions.ts, src/ChartInternal/internals/region.ts, src/config/Options/common/main.ts, test/internals/regions-spec.ts, types/types.d.ts
#3920
- Enhance regions start/end to use category name values
- Reinforce documentation and demo
```js
bb.generate({
data: {
columns: [
["data1", 30, 200, 100, 400, 150, 250],
["data2", 100, 150, 130, 200, 220, 190]
],
axes: {
data2: "y2"
},
type: "line", // for ESM specify as: line()
colors: {
data1: "#ff0000"
}
},
axis: {
x: {
type: "category",
categories: [
"cat1",
"cat2",
"cat3",
"cat4",
"cat5",
"cat6"
]
}
},
regions: [
{
axis: "x",
start: "cat2",  // <-- can use category name
end: "cat3"
},
{
axis: "x",
start: "cat5",
end: 5. // <-- can be combined with indexed number value
}
]
});
```
=> feat(region): Enhance regions accept category range

demo/demo.js, demo/simple-sidebar.css, src/Chart/api/chart.ts, src/ChartInternal/ChartInternal.ts, src/config/Options/common/main.ts, test/internals/bb-spec.ts, types/options.d.ts
#3955
Implement auto resize based on parent node size changes
```js
resize: {
// auto resize when parent container element size changes
auto: "parent"
}
```
=> feat(resize): Container based auto resize

demo/demo.js, src/ChartInternal/internals/region.ts, src/config/Options/common/main.ts, test/internals/regions-spec.ts, types/options.d.ts
#3960
Implement center alignment feature for region label
```js
regions: [
{
label: {
center: "xy"
}
},
{
label: {
center: "x"
}
},
{
label: {
center: "y"
}
}
]
```
=> feat(regions): Intent to ship regions.label.center

demo/demo.js, src/ChartInternal/Axis/Axis.ts, src/config/Options/axis/x.ts, src/config/Options/axis/y.ts, src/config/Options/axis/y2.ts, src/config/Options/common/main.ts, test/internals/axis-spec.ts, types/axis.d.ts
#3967
Implement new reverse option where culling to start from the last tick
```js
axis: {
[x | y | y2]: {
tick: {
outer: false,
culling: {
max: 6,
reverse: true
}
}
}
}
```
=> feat(axis): Intent to ship axis' tick.culling.reverse

src/ChartInternal/internals/color.ts, test/api/chart-spec.ts
#3984
Update data.color and data.colors options value to take from the config always. This will make runtime update to be applied at any time.
```js
const chart = bb.generate(args);
// when update `data.color` after the init, the new updated color value will be taken.
chart.config("data.color", function (color, d) {
return {data: "blue"}[d.id];
}, true);
```
=> refactor(color): Enhance data.color(s) option to take config value always

src/Chart/api/export.ts, src/ChartInternal/Axis/Axis.ts, src/ChartInternal/Axis/AxisRendererHelper.ts, src/ChartInternal/data/data.ts, src/ChartInternal/interactions/eventrect.ts, src/ChartInternal/interactions/interaction.ts, src/ChartInternal/internals/size.ts, src/ChartInternal/internals/tooltip.ts, src/ChartInternal/shape/point.ts, src/ChartInternal/shape/radar.ts, src/ChartInternal/shape/shape.ts, src/config/Options/common/main.ts, src/module/util.ts, test/assets/module/util.ts
- Update the call of .getBoundingClientRect() and .getBBox() to use internal single function
- revert resize.timer=true as default
=> refactor(all): make rect called from single source 

src/ChartInternal/Axis/AxisRenderer.ts, src/ChartInternal/Axis/AxisRendererHelper.ts, test/api/export-spec.ts, test/internals/axis-spec.ts
#4017
Adjust tick text position based on the text font-size. As the nature of font's dimension can't be get accurately, texts position accuracy has limited.
- left: before / right: after
=> fix(axis): Fix axis text position
