naver/billboard.js

- .eslintrc
- .travis.yml
- karma.conf.js
- mocha.opts
- package.json
- spec/api.data-spec.js
- spec/api.focus-spec.js
- spec/arc-spec.js
- spec/axis-spec.js
- spec/bb-spec.js
- spec/class-spec.js
- spec/core-spec.js
- spec/data-spec.js
- spec/domain-spec.js
- spec/grid-spec.js
- spec/interaction-spec.js
- spec/legend-spec.js
- spec/shape.bar-spec.js
- spec/shape.line-spec.js
- spec/title-spec.js
- spec/tooltip-spec.js
- spec/type-spec.js
- spec/zoom-spec.js
#1 
- Upgrade node version
- Cache node packages
> chore(CI): Modify travis config

- .travis.yml
- README.md
- karma.conf.js
- package.json
- spec/class-spec.js
- spec/core-spec.js
- yarn.lock
#2 
- Add build status badge
- Add coverage status badge
- remove done param from some tests
@sculove
> chore(dev-env): Add build & coverage badge

- .travis.yml
#12 
Make sure every push to be checked
@sculove
> chore(travis): run lint before test

- spec/axis-spec.js
- spec/data-spec.js
- src/api/api.data.js
- src/axis/bb.axis.js
- src/data/data.convert.js
- src/data/data.js
- src/internals/grid.js
#17 
- fix babel transform on MacOS
@netil
> fix(data): babel transform bug

- src/config/Options.js
#28 
Add some missing `data` options APIs
@sculove
> doc(options): Add missing data option API

- spec/interaction-spec.js
- src/interactions/interaction.js
- src/internals/arc.js
#24
- Fix wrong bindings and improved the way of event binding
- Changed some code format style
@sculove
> fix(interaction): Correct event binding

- spec/tooltip-spec.js
- src/internals/tooltip.js
#39 
Avoid unnecessary double dashed class name
> style(tooltip): Remove double dashed class name

- src/config/Options.js
#42
- Add detailed description and examples on axis.padding
- Touched some text styles
> docs(Options): Add more description on axis padding

- .gitignore
- spec/api.zoom-spec.js
- spec/title-spec.js
- src/data/data.js
- src/interactions/interaction.js
Ref #33
- fix rect size bug when zooming
@netil
> fix(api.zoom, interaction): fix zoom bug for rects

- spec/shape.line-spec.js
- src/axis/Axis.js
- src/data/data.js
- src/internals/ChartInternal.js
- src/internals/shape.js
- src/internals/shape.line.js
#10 
when axis x value is Date type, changed to compare with time numeric value, due to Date type comparison doesn't work as expected
@sculove
> fix(shape.line): Correct getting shape object

- config/changelog.js
- package.json
- src/axis/Axis.js
#49 
Create CHANGELOG.md file from git log
> chore(changelog): Generate changelog file

- README.md
#52 
- Add CDN info
- Change demo URL
- Update on documents links
- Add npm package badge
- Simplified 'npm test' command
> docs(readme): up-to-date

- CONTRIBUTING.md
- config/commit.template
- config/validate-commit-msg.js
- package.json
- yarn.lock
#48 
- `prepush`: run lint
- `commitmsg`: check for commit msg style
- convert `validate-commit-msg.js` to ES6 syntax
@sculove
> chore(git-hook): Add git hook for push & commit

- .travis.yml
#64
Do not build branches starting with 'greenkeeper/'
> chore(travis): Add exclude branch regex

- src/interactions/interaction.js
- src/internals/arc.js
- src/internals/clip.js
- src/internals/domain.js
- src/internals/region.js
- src/internals/scale.js
- src/internals/shape.js
- src/internals/shape.line.js
- src/internals/tooltip.js
#65 
Error happened from the upgrade of eslint.
There's no changes of code. All changes are about correcting spacing & indentations.
> style(interactions,internals): Correct eslint error

- .travis.yml
#65 
To be updated lock file automatically
> chore(dev-env): add greenkeeper-lockfile

- config/webpack.config.development.js
- config/webpack.config.packaged.js
- config/webpack.config.production.js
- webpack.config.js
#23
Add plugin and change config to es6 syntax
> chore(dev-env): Add webpack ModuleConcatenationPlugin

- demo/demo.js
#72
onmouseXXX option to onover/onout
@kjhwee91
> docs(demo): Correct wrong option name

- .github/PULL_REQUEST_TEMPLATE.md
> docs(gh-template): Remove 'preferred reviewers' clause

- src/config/Options.js
#87, #89
Update and add more detailed descriptions
> docs(options): Reinforce API docs

- README.md
- Separated badges & links for ease maintenance
- Added download badge
> chore(readme): Re-organizing badges

- README.md
To visualize different chart types supported by billboard.js
> docs(readme): Add chart type image

- config/changelog.js
#96 
Updated to use package.json's `bugs.url`.
> chore(changelog): use packages's bug url

- src/config/Options.js
Add descriptive example of paramters for:
- data.onselected
- data.onunselected
> docs(Options): Add param description on data selection

- spec/interaction-spec.js
- src/internals/selection.js
#112
Change to normal function correcting the scope issue
> fix(selection): Correct on data selection

- index.html
Just improving the English text. Hope you don't mind :)
> Improve the English text

- spec/selection-spec.js
- src/internals/selection.js
#117 
Check last toggle circle element to avoid multiple calls
> fix(selection): Correct multiple callback calls

- spec/data-spec.js
- src/config/Options.js
- src/data/data.convert.js
- src/data/data.js
- src/internals/ChartInternal.js
- src/internals/type.js
#8
- Add min, max data extraction codes
- Refactored codes getting chart types
> feat(data,Options): Implement data.onmin/onmax callback

- spec/api.chart-spec.js
Ref #62
Add basic test cases for chart.resize() and chart.destroy()
> test(api.chart): Add some initial test cases for chart api

- spec/arc-spec.js
- src/config/Options.js
- src/internals/arc.js
#71
Add line break functionality using '\n' key
> feat(Arc): Implement multiline donut title

- src/config/Options.js
#133
Add api doc for item.tile, padding & equally option
> docs(legend): Document missing API

- spec/tooltip-spec.js
- src/config/Options.js
- src/internals/tooltip.js
#127
- Add new tooltip.order option
- Detach data.order to be used on tooltip ordering
> feat(tooltip): Implement tooltip.order

- spec/zoom-spec.js
- src/axis/Axis.js
- src/axis/bb.axis.js
- src/interactions/zoom.js
- src/internals/ChartInternal.js
- src/internals/legend.js
#60
For zoomed chart axis wasn't reflecting resize. When zoom scale exist, use zoom scale.
Also fixed to react resize event after zoom out.
> fix(zoom): Correct zoom resizing

- spec/arc-spec.js
- spec/axis-spec.js
- src/config/Options.js
- src/internals/arc.js
#140
- Correct to draw full circle background when fullCircle options is set
- Changed max text label display on fullCircle
- Add missing gauge API docs
> fix(gauge): Correct background rendering on fullCircle

- spec/api.load-spec.js
- src/internals/shape.line.js
#147
Correction on return type to array in redrawCircle(), to not break rendering flow.
> fix(shape.line): Correct return type

- README.md
#165
- clarify file path
- add ESM import description
> docs(readme): clarifying loading files

- css/styles.css
No issue
Deletes:
- Delete position absolute on header content
- Delete min height on header
Changes:
- Change bottom padding on header content
- Change some media query width value
Add:
- Set font size 11px on nav item when width less than 860px
- Set header content padding top 100px when width less than 860px
> Make gh-pages intro header clear

- demo/chart.js
- demo/demo.js
- demo/index.html
- demo/simple-sidebar.css
Ref #144, #174
- Add for new options
- Display markup code
- Fix code replacement
> docs(example): Add new options example

- spec/assets/util.js
- spec/shape.bar-spec.js
- src/data/data.js
- src/interactions/interaction.js
#178
- Fix erroneous element selector
- Update event firing for test cases
> fix(data,interaction): Bar type interaction error on multiple x

- src/config/Options.js
#173
- update description
- remove unnecessary definition
> skip: update point.type jsdoc

- spec/bb-spec.js
- src/internals/size.js
- src/internals/util.js
#179
Use body's offsetWidth when width value is greater.
> fix(size): Correct width on resizing

- spec/interaction-spec.js
#202
#204
Test case for multiple xs
> test(data.xs): Add data.onclick for multiple xs

- src/api/api.axis.js
- src/api/api.category.js
- src/api/api.chart.js
- src/api/api.color.js
- src/api/api.data.js
- src/api/api.flow.js
- src/api/api.focus.js
- src/api/api.grid.js
- src/api/api.group.js
- src/api/api.legend.js
- src/api/api.load.js
- src/api/api.region.js
- src/api/api.selection.js
- src/api/api.show.js
- src/api/api.tooltip.js
- src/api/api.transform.js
- src/api/api.x.js
- src/api/api.zoom.js
- src/config/Options.js
- src/core.js
- src/internals/browser.js
- src/internals/util.js
#190
- Make to generate undocumented APIs changing some code structures.
- Changed the arbitrary colon char to dot char.
- Updated `@memberof` tag to `@memberOf`
> docs(all): Improve readability & undocumented APIs

- demo/demo.js
- src/config/Options.js
- src/internals/tooltip.js
- src/scss/tooltip.scss
#193 
- Enhance API doc on id definition
- Fix wrong css property for normal tooltip
- Add more demo
> skip: correct & enhance on color.tiles

- demo/demo.js
- spec/api.load-spec.js
- spec/shape.bubble-spec.js
- src/data/data.load.js
- src/shape/point.js
#163
When loads happens containing higher value than loaded,
the previous size should shrink.
> fix(bubble,point): Fix bubble size change on load API

- CONTRIBUTING.md
- README.md
2
typo-fixed -> avoide -> avoid
> typo-fixed

- .travis.yml
- spec/bb-spec.js
- src/internals/ChartInternal.js
#155
Removed setting 'max-height' property and set <svg> as block element.
> fix(size): Correct height increase during resize

- src/config/Options.js
#238
Corrected incorrect demo code syntax
> docs(Options): Fix incorrect demo code on API

- spec/axis-spec.js
- src/axis/Axis.js
- src/axis/bb.axis.js
- src/config/Options.js
- src/internals/scale.js
#236
Add &lt;title> element showing full category text when the option is set
> feat(axis): Inten to ship axis.x.tick.tooltip

- spec/api/api.chart-spec.js
- spec/api/api.flow-spec.js
- spec/api/api.legend-spec.js
- spec/api/api.region-spec.js
- spec/api/api.select-spec.js
- spec/api/api.show-spec.js
- spec/api/api.tooltip-spec.js
- spec/api/api.zoom-spec.js
- src/api/api.show.js
#62
- Add test codes for show APIs(show, hide & toggle), groups(), 
- Update show APIs docs
- Mark as @todo for APIs not added yet
> test(API): Add test codes

- spec/api/api.flow-spec.js
- src/api/api.flow.js
#62 
- Add TC for .flow()
- Update .flow() API doc
> test(api.flow): Add .flow() test codes

- spec/internals/axis-spec.js
- src/axis/bb.axis.js
#240
Side effect on implementing the new axis.x.tick.tooltip option
> fix(tooltip): Correct on toggling data series

- src/api/api.tooltip.js
- src/interactions/interaction.js
Ref #251
- Use MouseEvent to create whenever is supported.
- Added params description for .tooltip.show()
> fix(interaction): Correct creating mouse event

- spec/api/api.tooltip-spec.js
- src/api/api.tooltip.js
#248
- Add missing test codes
- Reinforce `.tooltip.show()` API docs
> test(tooltip): Add tooltip's API test codes

- spec/api/api.legend-spec.js
#249
Test codes for `.legend.show()` and `.legend.hide()`
> test(legend): Add test code for .legend.show/hide()

- spec/interactions/interaction-spec.js
- src/internals/ChartInternal.js
- src/internals/ua.js
#92
Determine by userAgent and prioritize mouse input type for non-mobile environment.
> fix(interaction): Prioritize mouse input

- spec/api/api.zoom-spec.js
- src/api/api.zoom.js
#290
- Use zoom.min/max for the range setting
- Add test codes for zoom.min/max/range
> fix(zoom): Correct zoom.range() to work

- config/webpack.config.development.js
- package-lock.json
- package.json
- webpack.config.js
- yarn.lock
#299
Add webpack-stylish module
> chore(webpack): Organize webpack build logs

- spec/internals/bb-spec.js
- src/core.js
- src/internals/ChartInternal.js
#308
Implement a property of array containing instances generated in a page
> feat(core): Intent to ship instance property

- .travis.yml
#316
Update install command from `npm install` to `npm ci`
> chore(ci): Change npm install command

- spec/assets/util.js
- spec/internals/axis-spec.js
- spec/internals/bb-spec.js
- src/axis/bb.axis.js
- webpack.config.js
#222
Correct when tick float value aren't rounded
> fix(axis): Round float numbers from 'binary floating point'

- spec/internals/axis-spec.js
- src/axis/Axis.js
- src/axis/bb.axis.js
- src/config/Options.js
#327
- Pass category name for tick.format function
- Fix axis.y.tick.format API doc
> feat(axis): Pass category name param

- demo/chart.js
- spec/api/api.chart-spec.js
- src/api/api.chart.js
#347
When .destroy() is called, it should be removed from the bb.instance
> fix(api): Fix to remove instance

- spec/api/api.tooltip-spec.js
- src/api/api.tooltip.js
#343
Changed dispatching event to direct node handling
> fix(api): Change the way of hiding tooltip

- config/webpack.config.packaged.js
#372
Remove the scss import to not be parsed
> chore(dev-env): Remove css inclusion on packaged build

- spec/internals/tooltip-spec.js
- src/api/api.tooltip.js
- src/data/data.js
- src/interactions/interaction.js
- src/internals/ChartInternal.js
- src/internals/tooltip.js
- src/shape/line.js
#376
- Fix tooltip.show() to work
- Fix data point circle expansion
- Fix tooltip.init.show option to work
- Add touch event dispatcher
> fix(tooltip): Correct interaction on mobile

- spec/internals/grid-spec.js
- src/config/Options.js
- src/internals/ChartInternal.js
- src/internals/grid.js
#384
New option to handle grid element position on DOM hierarchy
> feat(grid): Intent to ship grid.front option

- spec/internals/axis-spec.js
- src/axis/bb.axis.js
- src/config/Options.js
#381
Added to line break with '\n', allowing to line break on exact position.
> feat(axis): Enhancement on tick multiline

- spec/api/api.load-spec.js
- src/data/data.convert.js
- src/internals/util.js
#398
Correct the condition on loading JSON according the type (Array or Object).
> fix(api): Fix JSON data loading

- spec/api/api.show-spec.js
- spec/internals/tooltip-spec.js
- src/config/Options.js
- src/internals/tooltip.js
#401
- Option to interact using name
- Refactored tooltip-spec.js
> feat(tooltip): Intent to ship linked tooltip with name

- package-lock.json
- package.json
- spec/internals/axis-spec.js
- src/axis/bb.axis.js
- src/internals/util.js
- yarn.lock
#399
Moved and updated condition on getSizeFor1Char() call to avoid multiple calls.
> fix(axis): Avoid unnecessary computing char dimension

- package.json
- webpack.config.js
#410
Tagging the version for nightly.
> chore(dev-env): Add nightly build

- spec/internals/data-spec.js
- src/data/data.js
- src/internals/util.js
#379
The sorting of data was altering its order when is called.
Prevent this by deep copying it.
> fix(data): Correct data order to not be altered

- spec/api/api.grid-spec.js
- src/internals/grid.js
#389
- Split grid lines update functions: updateXGridLines(), updateYGridLines()
- Refactored grid's position and text-anchor setting functions
> fix(grid): Correct updating grid's attributes

- src/api/api.export.js
> docs(export): Add styling note

- spec/internals/axis-spec.js
- src/axis/bb.axis.js
- Removed duplication, re-organizing variable, etc.
- Removed unnecessary assertion
> refactor(axis): Removed duplication and re-styling

- spec/internals/selection-spec.js
- src/config/Options.js
- src/internals/selection.js
- src/shape/arc.js
#445
- Fixed incorrect selector
- Added interaction.brighten API doc
> fix(selection): Correct multiple selection error

- spec/api/api.show-spec.js
- src/api/api.show.js
#454
Split show & hide tasks for grouping and ran separately.
For hide tasks schedule tasks using setTimeout.
> fix(api): Correct toggle interaction

- spec/internals/axis-spec.js
- src/axis/Axis.js
- src/axis/bb.axis.js
- src/internals/scale.js
#380
Specify axes names instead of the assumption.
> fix(axis): Correct tick's position implementation

- demo/demo.js
- demo/simple-sidebar.css
- spec/internals/axis-spec.js
- spec/internals/core-spec.js
- src/config/Options.js
- src/internals/ChartInternal.js
- src/internals/clip.js
#458
Implement clipPath option for x and y axis
> feat(axis): Intent to ship axis clipPath option

- spec/internals/bb-spec.js
#468
Updated the way on resizing tests
> test(resize): Fix on CI timeout failing

- src/data/data.js
> refactor(data): Simplify on step data conversion

- spec/shape/shape.line-spec.js
- src/config/Options.js
- src/data/data.js
#481
Area-range types have different data format than others,
and updated to handle to maintain compatibility with others
> fix(area-range): Fixed data parsing

- spec/internals/data-spec.js
- src/internals/text.js
- src/internals/type.js
- src/shape/line.js
#488
- Make data label to show
- Enhance label text's y position to be relative of point.r size
> fix(data): Correct data label text to be shown on scatter

- spec/interactions/interaction-spec.js
- src/config/Options.js
- src/interactions/interaction.js
#490
- Update on use of 3.x d3.drag API
- Removed duplicated call on drag function
> fix(interaction): Correct drag selection error

- spec/assets/util.js
- spec/internals/tooltip-spec.js
- src/internals/tooltip.js
#494
- Update tooltip show/hide based on index instead of x value
- Fix on incorrect sandbox generation
- Fix and refactoring on tooltip test codes
> fix(tooltip): Make linked tooltip to work based on index

- demo/demo.js
- spec/internals/data-spec.js
- src/config/Options.js
- src/shape/line.js
#491
- Implement 'dasharray' option to let customize dashed styles
- Refactorings on data test codes and line related codes
> feat(regions): Intent to ship dasharray

- config/deploy.sh
- jsdoc.json
- package.json
- spec/internals/bb-spec.js
- src/api/api.axis.js
- src/api/api.legend.js
- src/api/api.tooltip.js
- src/core.js
- src/internals/Chart.js
- src/internals/ChartInternal.js
#423
- Intent to ship primary node elements
- Build api doc without entire building
> feat(Chart): Expose primary node elements

- spec/api/api.load-spec.js
- src/data/data.convert.js
- src/data/data.load.js
- src/shape/bubble.js
#517
- Corrected to point correct x axis index value when the loaded x is already exists
- Fix on getting bubble radius when is used with area-range type
> fix(api): Fix loading to maintain correct x index

- spec/api/api.zoom-spec.js
- spec/interactions/interaction-spec.js
- src/interactions/interaction.js
- src/internals/ChartInternal.js
- src/internals/util.js
#522
- Update condition for rect resizing
- Some refactorings on ChartInternal.js
> fix(interaction): Correct rect element sizing

- src/api/api.chart.js
- src/api/api.load.js
- src/api/api.zoom.js
- src/axis/bb.axis.js
- src/config/Options.js
- src/interactions/zoom.js
- src/internals/ChartInternal.js
- src/internals/class.js
- src/internals/color.js
- src/internals/grid.js
- src/internals/legend.js
- src/internals/region.js
- src/internals/selection.js
- src/internals/size.js
- src/internals/text.js
- src/internals/title.js
- src/internals/tooltip.js
- src/internals/util.js
- src/shape/arc.js
- src/shape/bar.js
- src/shape/shape.js
#524
- Remove the use of MutationObserver
- Add call function utility function
> refactor(all): Removed & updated unnecessary codes

- src/axis/bb.axis.js
#399
There's report on throwing error on getting rect bound.
Surround with try catch block to avoid blocking chart generation.
> refactor(all): Prevent throwing error

- src/core.js
- src/data/data.convert.js
- src/data/data.js
- src/interactions/subchart.js
- src/internals/domain.js
- src/internals/util.js
It's unnecessary extend as part of ChartInternal
> refactor(core): Remove extending util as member of ChartInternal

- spec/api/api.export-spec.js
- src/shape/bar.js
#530 
New line chars can cause not to export as image properly.
> fix(bar): Remove new line chars on path string

- spec/api/api.load-spec.js
- src/api/api.load.js
- src/axis/Axis.js
- src/data/data.convert.js
- src/data/data.js
- src/interactions/interaction.js
#534
- Correct .getMaxTickWidth() to get last max axis width value
- Some refactorings
- Fix side effect caused by #519
> fix(axis): Correct axis label position

- spec/shape/shape.radar-spec.js
- src/internals/ChartInternal.js
- src/shape/radar.js
#497
Fix on redraw handling selections
> fix(radar): Correct on resizing

- demo/demo.js
- spec/shape/shape.radar-spec.js
- src/config/Options.js
- src/shape/radar.js
#464
Implementation of the radar type draw direction
> feat(radar): Intent to ship radar.direction.clockwise

- demo/demo.js
- spec/api/api.chart-spec.js
- src/api/api.chart.js
#502
- Implementation of the new .config() method
- Add the support of soft redraw for .flush()
> feat(api): Intent to ship .config()

- spec/internals/tooltip-spec.js
- src/internals/tooltip.js
#431
- When has zoomScale, make to be based on mouse x coordinate
- Some refactorings on tooltip
> fix(tooltip): Correct tooltip position when is zoomed

- src/internals/tooltip.js
- src/scss/theme/insight.scss
#546 
- Fix side-effect by #546, some template literals weren't transpiled
correctly due to some code structures.
- Add font-family style for tooltip for insight theme
> skip: Fix the template literal transpile error

- spec/interactions/drag-spec.js
#552
Add test cases for dragstart, drag and dragend
> test(drag): Add drag tests

- spec/interactions/zoom-spec.js
- src/internals/region.js
#483
- Use zoomScale when is available
- Refactorings on regions dimension methods
> fix(regions): Fix regions resizing on zoom

- demo/demo.js
- spec/shape/shape.point-spec.js
- src/shape/point.js
#562
Allow grouped child nodes as custom point
> feat(point): Allow grouped custom point

- spec/interactions/zoom-spec.js
- src/api/api.zoom.js
- src/interactions/zoom.js
- src/internals/ChartInternal.js
#470
Update x axis domain with the zoomScale domain value
> fix(zoom): Fix on zoom.rescale option

- spec/interactions/zoom-spec.js
- src/interactions/interaction.js
- src/interactions/zoom.js
#583
Split data click handlers as separate function and make to use
those for drag zoom
> fix(zoom): Correct not firing data.onclick callback

- spec/internals/tooltip-spec.js
- src/internals/tooltip.js
#597
Fix on wrong mid value appending
> fix(tooltip): Fix mid value showing for area-range type

- spec/internals/tooltip-spec.js
- src/interactions/interaction.js
- src/internals/tooltip.js
#593
- Prevent when instances are empty
- Prevent circular call for certain cases
> fix(tooltip): Fix for mobile environment

- spec/assets/util.js
- spec/internals/tooltip-spec.js
- spec/shape/shape.arc-spec.js
- spec/shape/shape.bubble-spec.js
#617
- Move hoverChart function to test's util
- Add test cases for arc interaction
- Add test cases for different bubble.maxR option value
> test(shape): Add test codes

- spec/api/api.selection-spec.js
#617
Test cases for bar(path) elements selection
> test(api): Add test code for bar type using .select()

- spec/api/api.x-spec.js
- src/api/api.x.js
- src/data/data.js
#634
- Update on correct .x() update for indexed type
- Added to check argument data types
- Added test code
> fix(api): Correct .x()/.xs() to work properly

- spec/interactions/zoom-spec.js
#617
Test codes for onzoomstart, onzoom and onzoomend
> test(zoom): Add test codes for zoom callbacks

- spec/api/api.data-spec.js
- src/api/api.data.js
#637
- Implemented data.min()/max()
- Specified the return type for data APIs
> feat(data): Intent to ship data.min()/max()

- spec/shape/shape.line-spec.js
- src/data/data.js
- src/shape/line.js
#630
Correct on getting correct coordinate values evaluating if data is grouped or not
> fix(area-line-range): Fix working with grouped data

- spec/internals/data-spec.js
- spec/shape/shape.arc-spec.js
- src/api/api.data.js
- src/data/data.js
#643
Added to get different ratio when data is hidden
> fix(shape): Fix normalization on hidden data

- demo/index.html
- src/scss/theme/graph.scss
#631
Add new css theme 'graph' file
> feat(theme): Add new 'graph' theme

- spec/internals/data-spec.js
- src/data/data.js
#623
When value is non numeric, set zero as a replacement
> fix(shape): Fix for empty data in normalization

- spec/internals/data-spec.js
- src/data/data.js
#623
Add preventing condition to make sure calculating ratio value
> fix(shape): Prevent when non-existed data.hide is given

- spec/shape/shape.point-spec.js
- src/shape/point.js
#648
Check for the cx attribute for newly added point element to exclude
from the transition
> fix(shape): Correct newly added points transition position

- spec/internals/tooltip-spec.js
- src/internals/tooltip.js
#660
Correct getting nullable index value
> fix(tooltip): Fix for dynamically loaded data adding column

- src/config/Options.js
- src/config/config.js
- src/internals/util.js
- Changed the way on getting options value
- Removed merge util function
- Shortened some destructuring assignment
> refactor(Options): Remove unnecessary codes

- package-lock.json
- package.json
- src/core.js
#666
- Update core.js require() import to use ESM' import
- Add 'sideEffects':false option
> chore(build): Change require() to import statement

- spec/api/api.load-spec.js
> test(load): Add test case using different load option

- spec/internals/axis-spec.js
- src/axis/AxisRenderer.js
- src/axis/AxisRendererHelper.js
#672
It was caused by getting tick's position earlier than it was set
> fix(Axis): Fix tick text position

- spec/internals/axis-spec.js
- src/axis/AxisRenderer.js
- src/axis/AxisRendererHelper.js
#25
Make the transition update to happen last
> fix(Axis): Fix text alignment when legend is not showing

- config/jsdoc.js
- jsdoc.json
- package-lock.json
- package.json
#688
Change to generate from `src` folder
> chore(jsdoc): Update jsdoc generation

- spec/internals/domain-spec.js
- src/data/data.js
- src/internals/domain.js
#685
When has multi xs, the value should be compared based on correct x Axis index value
> fix(domain): Fix getting Y domain min/max value

- .gitignore
- src/data/data.js
#690
- Add .iml to gitignore
- Simply .getIndexByX()
> refactor(domain): Improve on .getIndexByX()

- spec/internals/legend-spec.js
- src/internals/legend.js
#705
Scale & sizes update should peform after template updates
> fix(legend): Fix resizing when legend template is used

- spec/internals/legend-spec.js
- src/internals/ChartInternal.js
- src/internals/legend.js
#705
Correct arcs transform when template legend is used
> fix(legend): Fix resize for arc

- spec/internals/util-spec.js
- src/data/data.js
- src/internals/ChartInternal.js
- src/internals/domain.js
- src/internals/util.js
Correct incorrect data sort, caused by the issue #710
> skip: fix on side-effect

- spec/internals/core-spec.js
- src/axis/Axis.js
- src/internals/ChartInternal.js
- src/internals/scale.js
- src/internals/size.js
#36
Make not generate axes when they're not visible.
This will also improve shrinking unnecessary node handligs.
> refactor(axis): Do not generate unnecessary axes

- demo/demo.js
- package-lock.json
- spec/shape/shape.bar-spec.js
- src/config/Options.js
- src/shape/bar.js
- src/shape/shape.js
- types/options.d.ts
- webpack.config.js
#720
Implement bar.width.dataset feature to allow specify width for each dataset.
> feat(bar): Intent to ship variant width

- package-lock.json
- package.json
- yarn.lock
> chore(dev-env): update dependency to the latest

- config/nightly.js
- package.json
#544
To automate nightly build from Travis CI cron job.
> chore(build): Automate nightly build

- spec/interactions/zoom-spec.js
- src/shape/line.js
#728
Correct the condition on getting x scale.
It was set the condition in opposite way.
> fix(line): Correct zoom with data.regions

- demo/demo.js
- demo/simple-sidebar.css
- spec/internals/title-spec.js
- src/config/Options.js
- src/internals/legend.js
- src/internals/text.js
- src/internals/title.js
#612, #727
- Implementation on multiline title text
- Applied cache to reduce call on  getting text element's dimension
> feat(title): Intent to ship multilined title

- spec/shape/shape.radar-spec.js
- src/shape/radar.js
#735
Add type check for ratio value to not erroneously use radar.size.ratio value.
> fix(radar): Fix incorrect rendering

- spec/internals/axis-spec.js
- src/axis/Axis.js
- src/internals/scale.js
#717
x and y axis should be present even they're not shown.
> fix(axis): fix side-effects from #717

- demo/demo.js
- spec/interactions/subchart-spec.js
- spec/internals/axis-spec.js
- src/axis/AxisRenderer.js
- src/config/Options.js
- src/interactions/subchart.js
- src/internals/ChartInternal.js
- src/internals/legend.js
- src/internals/scale.js
- src/internals/size.js
- types/axis.d.ts
- types/options.d.ts
#737
Implementation of 'tick.show' and 'tick.text.show' options
- Do not generate unnecessary nodes when is not shown
- Correct the subchart extent size when subchart.size.height is set
- Fix incorrect sizing when subchart.axis.x.show=false
- Add subchart test cases
> feat(axis): Intent to ship tick show options

- demo/demo.js
- spec/interactions/interaction-spec.js
- spec/internals/color-spec.js
- src/config/Options.js
- src/interactions/interaction.js
- src/internals/color.js
- src/shape/arc.js
- src/shape/bar.js
- types/options.d.ts
#754
#768
- Implmentation of color.onover new option.
- It also fixes data.onover/out for arc type on touch environment
> feat(color): Intent to ship color.onover

- spec/interactions/interaction-spec.js
- src/shape/arc.js
- src/shape/radar.js
#768
For radar type, data.onover/out should be called interacting with the axis text element
> fix(radar): Fix data.onover/out callback

- spec/internals/bb-spec.js
- spec/internals/data-spec.js
- src/internals/ChartInternal.js
#780
Fix on incorrect referencing on data label's text elements
> fix(chart): Correct data label text prop ref

- spec/api/api.tooltip-spec.js
- src/api/api.tooltip.js
- src/interactions/interaction.js
#785
- Correct the incorrect mouse coordinate values.
- Add more detailed description for API.
> fix(tooltip): Fix tooltip.show() for multi x axis

- demo/demo.js
- spec/shape/shape.arc-spec.js
- src/config/Options.js
- src/shape/arc.js
#784
Implement multiline text label for donut & pie type
> feat(arc): Enhance multiline text label

- spec/interactions/subchart-spec.js
- src/api/api.chart.js
- src/interactions/subchart.js
- src/internals/ChartInternal.js
- src/internals/legend.js
#778
Adjust subchart selection area when resize happens
> fix(subchart): Maintain subchart selection on resize

- spec/interactions/subchart-spec.js
- src/interactions/subchart.js
#778
Use org domain/scale to maintain subchart selection on resize
> fix(subchart): Maintaion selection for category x axis

- config/webpack.config.development.js
- config/webpack.config.production.js
- config/webpack.config.theme.js
- package-lock.json
Apply option interface change as of v2.0 update
> chore(dev-env): Fix option for clean-webpack-plugin

- src/api/api.flow.js
- src/api/api.zoom.js
- src/axis/Axis.js
- src/data/data.convert.js
- src/data/data.js
- src/data/data.load.js
- src/interactions/zoom.js
- src/internals/ChartInternal.js
- src/internals/class.js
- src/internals/clip.js
- src/internals/color.js
- src/internals/size.js
- src/internals/title.js
- src/internals/tooltip.js
- src/shape/line.js
- Move clip initialization to initClip()
- Merge .initZoomBehaviour() to .initZoom()
- Add .convertData() for data conversion
- Remove unused .getAreaBaseValue()
> refactor(all): Make some refactorings

- spec/interactions/subchart-spec.js
- src/api/api.flow.js
- src/config/Options.js
- src/interactions/subchart.js
- src/internals/ChartInternal.js
- types/axis.d.ts
#142
- Correct extent to work properly
- Improved to be called once during init & window resizing
> fix(subchart): Correct subchart extent option

- spec/shape/shape.arc-spec.js
- src/shape/arc.js
#784
- Add condition to check if text has been updated
- For multilined text, reset html before update
> fix(pie): Correct multiline label text

- demo/demo.js
- spec/api/api.zoom-spec.js
- src/axis/Axis.js
- src/axis/AxisRendererHelper.js
- src/internals/ChartInternal.js
Fix on axis transition. At the initialization, it shouldn't be
apply transition & later should depend the transition.duration setting
> skip: updates on axis transition

- spec/internals/tooltip-spec.js
- src/api/api.tooltip.js
- src/config/Options.js
- src/internals/tooltip.js
- types/options.d.ts
#812
Implement to not hide on user interaction, but it hides when .hide() is called.
> feat(tooltip): Intent to ship tooltip.doNotHide

- demo/chart.js
- demo/demo.js
- demo/simple-sidebar.css
- package-lock.json
- package.json
- spec/internals/tooltip-spec.js
- src/config/Options.js
- src/internals/legend.js
- src/internals/tooltip.js
- src/internals/util.js
- types/options.d.ts
- yarn.lock
#813
- Implementation of tooltip.contents.template
- Update legend template processing with util's .tplProcess()
- Update dependencies to the latest
> feat(tooltip): Intent to ship tooltip.contents.template

- package-lock.json
- package.json
- yarn.lock
Update sinon to latest version
> chore(dependency): update dependency to the latest

- spec/internals/grid-spec.js
- src/axis/AxisRendererHelper.js
- src/internals/grid.js
#820
Fix on x and y Axes default grid lines position
> fix(grid): Correct grid position

- demo/demo.js
- demo/simple-sidebar.css
#824
Correct css selector id to lowercase.
> style(demo): Correct style rule to be lowercase

- demo/demo.js
- spec/internals/tooltip-spec.js
- src/config/Options.js
- src/internals/tooltip.js
- types/options.d.ts
#826
Implement to add additional text content within template syntax
> feat(tooltip): Intent to ship tooltip.contents.text

- spec/interactions/interaction-spec.js
- spec/shape/shape.bar-spec.js
- spec/shape/shape.point-spec.js
- src/config/Options.js
- src/shape/bar.js
- src/shape/line.js
- src/shape/shape.js
- types/options.d.ts
#831
Implementation of the new senstivity option
- point.senstivity
Was already existed as undocumented. Also updated some work flow on this.
- bar.senstivity
> feat(point,bar): Intent to ship sensitivity

- spec/shape/shape.bar-spec.js
- src/shape/bar.js
#832
Fix incorrect bar width total sum.
Side-effect caused by #720
> fix(bar): Fix bar position on width option

- spec/api/api.flow-spec.js
- src/api/api.flow.js
- src/internals/ChartInternal.js
- types/chart.d.ts
#825
Check for the visibility of tab for .flow() execution.
> refactor(flow): Mitigation for .flow() when isn't visible

- spec/plugin/stanford/stanford-elements-spec.js
- spec/plugin/stanford/stanford-spec.js
#829
Add test codes for stanford diagram
> test(plugin): Add test code for stanford plugin

- demo/chart.js
#853
Make each item navigation by onhashchange event
> chore(demo): Enhance navigation

- spec/shape/shape.line-spec.js
- src/shape/line.js
#855
Change the gradient update condition to handle dynamic data loading
> fix(area): Apply gradient on dynamic data loading

- spec/internals/axis-spec.js
- src/axis/Axis.js
- src/internals/size.js
#859
Adjust range at the time of generation & time of update.
> fix(axis): Adjust axes range

- config/banner.js
- config/webpack.config.plugin.js
- config/webpack.config.theme.js
- Update plugin banner text
- Add banner for minified plugin build
> chore(build): Update on build banner

- demo/chart.js
- demo/index.html
- demo/simple-sidebar.css
#810, #822
- Split html/css code block to better visibility
- Make geenration code editable & executable on the fly
> chore(demo): Add editing functionality

- spec/api/api.load-spec.js
- spec/shape/shape.arc-spec.js
- src/data/data.convert.js
- src/data/data.load.js
#863
Make data indexing to happens on every data convert even 'index'
property value exists.
> fix(data): Fix data indexing

- demo/chart.js
- demo/demo.js
- src/api/api.load.js
- src/config/Options.js
#866
- Add keys, mimeType & headers descriptions
- Rename demo key name: 'DataFromURL-csv' to 'DataFromURL'
- Make generation code var name to handle multiple instances
> docs(api): Update on .load() description

- spec/internals/color-spec.js
- src/shape/bar.js
#872
Removed inline `stroke` css property setting for bar `<path>`
> refactor(bar): Remove stroke style for bar

- demo/demo.js
- spec/internals/data-spec.js
- src/config/Options.js
- src/internals/text.js
- types/options.d.ts
#876
Implementation on data label texts align for bar type
> feat(data): Intent to ship data.labels.centered

- demo/chart.js
- demo/index.html
- demo/simple-sidebar.css
#883
Add online code launch functionality.
[skip ci]
> chore(demo): Add launch code editor

- src/internals/domain.js
> refactor(domain): some refactoring

- .travis.yml
- spec/interactions/zoom-spec.js
- src/interactions/zoom.js
#890
Add 'orgXScale' state to be used for re-scale on zooming
> fix(zoom): Fix zoom rescale by wheel

- spec/interactions/zoom-spec.js
- src/api/api.zoom.js
- src/interactions/interaction.js
- src/interactions/zoom.js
#736, #818
- Fix on rotated drag & wheel zooming
- Fix cursor style when is rotated
- Remove unused altKey zooming
> fix(zoom): Fix on rotated axis

- src/internals/browser.js
- Update on getting global
- Side-effect caused by: 9d6de876848f8ef1594a5b7a5e388c6264a2c781
> fix(ua): Fix the side-effect by refactoring

- spec/interactions/zoom-spec.js
- src/data/data.js
- src/internals/text.js
#906
Make to use zoomscale when is available to get the distance of points
> fix(zoom): Fix tooltip pos for bubble/scatter

- spec/interactions/zoom-spec.js
- src/api/api.zoom.js
- src/interactions/zoom.js
- src/internals/ChartInternal.js
- src/internals/legend.js
- src/internals/scale.js
#913
Maintain zoom level on legend visibility change
> fix(zoom): Fix zoom level reset

- spec/internals/axis-spec.js
- src/axis/Axis.js
#920
Make sure to measure size with the final rendered axis tick text.
> fix(axis): Fix on axis width sizing

- spec/interactions/zoom-spec.js
- src/config/Options.js
- src/internals/grid.js
#799
Make grid to be scale on zoom when zoomScale exist.
> fix(grid): Correct grid scale on zoom

- spec/shape/shape.line-spec.js
- src/shape/line.js
#930
Replace data name to work with special chars.
> fix(line): Fix areaGradient for spaced data name

- spec/internals/bb-spec.js
- src/core.js
- src/internals/util.js
- types/bb.d.ts
#932
Implementation of global configuration setting.
> feat(core): Intent to ship global config

- src/config/Options.js
- src/core.js
- src/internals/ChartInternal.js
- src/internals/util.js
- types/bb.d.ts
- types/options.d.ts
#928
Implement stats collector.
> feat(stats): Intent to ship stats

- spec/shape/shape.arc-spec.js
- src/shape/arc.js
#935
Update condition when generate arc path value.
> fix(arc): Fix to generate arc when data is zero

- spec/internals/color-spec.js
- src/config/Options.js
- src/internals/color.js
#950
- Fix erroneous loop condition to determine color value
- Make threshold values to be alined as the max ( n < n1 ==> n <= n1)
> fix(color): Fix on color.threshold.values handling

- config/webpack.config.production.js
#949
Applied directly the formatter
- https://github.com/webpack-contrib/eslint-loader/issues/238#issuecomment-505672107
> chore(build): Fix eslint-loader error

- spec/shape/shape.radar-spec.js
- src/internals/ChartInternal.js
#952
Generate radar prior the line element, which draws data points.
> fix(radar): Make data points stay over radar

- spec/shape/shape.radar-spec.js
- src/internals/ChartInternal.js
#953
Make radar chart to be positioned at the center of bind element.
> fix(radar): Fix radar positioning

- src/config/Options.js
- src/internals/ChartInternal.js
- src/internals/util.js
- types/options.d.ts
#964
Remove stats added by #934
> fix(stats): Remove stats

- spec/internals/tooltip-spec.js
- src/axis/Axis.js
- src/data/data.convert.js
- src/data/data.js
- src/interactions/interaction.js
- src/internals/ChartInternal.js
- src/internals/tooltip.js
- src/shape/line.js
#963
Make to update eventRect elements
> fix(tooltip): Correct tooltip on dynamic loading

- demo/demo.js
- spec/shape/shape.bubble-spec.js
- src/config/Options.js
- src/data/data.convert.js
- src/data/data.js
- src/internals/text.js
- src/internals/tooltip.js
- src/shape/bubble.js
- src/shape/line.js
- src/shape/shape.js
#484
Implementation of bubble dimension
> feat(bubble): Intent to ship dimension

- types/options.d.ts
Issue
#979
Make sure function types to be wrapped with the parenthesis.
[skip ci]
> docs(types): Fix on erroneous types

- spec/shape/shape.arc-spec.js
- src/internals/util.js
- src/shape/arc.js
- src/shape/radar.js
#982
Fix multiline vertical position.
> fix(text): Correct text vertical align

- spec/plugin/stanford/stanford-spec.js
- src/plugin/stanford/Elements.js
- src/plugin/stanford/Options.js
- src/plugin/stanford/index.js
- types/plugin/stanford/options.d.ts
#987
- Specify missing parameter data types on definition
- Update regions text function's percentage parameter to be number
- Update API doc description & examples
> refactor(stanford): Updates on data types

- spec/internals/bb-spec.js
- spec/plugin/stanford/stanford-spec.js
- src/config/Options.js
- src/internals/ChartInternal.js
- types/options.d.ts
#989
- Pass instance argument for callback options to facilitate the usage.
- Align all callbacks' default value to `undefined`
> feat(options): Pass instance arg to callbacks

- spec/shape/shape.radar-spec.js
- src/shape/radar.js
#997
Typecast axis text value to be dispalyed from the helper function.
> fix(radar): Correct display of indexed axis

- demo/demo.js
- spec/shape/shape.radar-spec.js
- src/config/Options.js
- src/shape/radar.js
- types/options.d.ts
#998
- Make defalut axis text to be positioned not overlapping chart area
- Implement axis text position
> feat(radar): Intent to ship axis.text.position

- src/axis/Axis.js
- src/data/data.js
- src/interactions/interaction.js
- src/internals/scale.js
- Removed .getXAxisTickValues(), .getYAxisTickValues() and .getY2AxisTickValues()
- Merged .getXAxis() and .getYAxis() to .getAxis()
> refactor(axis): Remove duplications

- src/api/api.flow.js
- src/data/data.js
- src/interactions/interaction.js
- src/internals/ChartInternal.js
- src/shape/point.js
- src/shape/shape.js
#1006
- Update removal nodes selection range on .flow()
- refactor point.js
- Update useless return from forEach on .generateWait()
- Update getting x tick values differ for flow and non-flow
> fix(flow): Fix data points removal

- spec/internals/axis-spec.js
- src/axis/Axis.js
- src/config/Options.js
#1011 
- Fix getting correct anchor value for label text.
- Add reference @see tag to doc for axis label position options.
> fix(axis): Correct label text position

- spec/internals/color-spec.js
- src/internals/color.js
#754, #872
Remove setting stroke value on  onover/onout interaction.
> fix(color): Correct to not set stroke

- spec/interactions/interaction-spec.js
- src/data/data.js
- src/interactions/interaction.js
#1019
- Make sure to get x Axis tick values
- Revert .updateXs()
> fix(interaction): Fix on eventRect generation

- spec/interactions/interaction-spec.js
- src/api/api.flow.js
- src/data/data.js
- src/interactions/interaction.js
- src/internals/ChartInternal.js
- src/internals/util.js
- src/shape/line.js
- src/shape/point.js
#1028, #1019, #963
- Rewrite of .getMaxDataCountTarget(), to get unique value based on x Axis.
- .updateDataIndexByX() & .updateXs() are based on the .getMaxDataCountTrarget()
- Add .updatePointClass() to update data point's class
- Refactor point.js to not receive `cssClassFn` on udpating data point's class
- Update .getUnique() to handle datetime type
> fix(interaction): Fix on eventRect rederaw

- spec/api/api.data-spec.js
- src/api/api.data.js
#1035
Change the condition to retrieve exact data.
> fix(api): Fix .data() to return exact data

- spec/internals/bb-spec.js
- spec/internals/core-spec.js
- spec/internals/data-spec.js
- spec/internals/util-spec.js
Add test codes to improve coverage
> test(core,data): Add test codes for not covered

- spec/assets/common.css
- spec/internals/bb-spec.js
- src/config/Options.js
- src/internals/ChartInternal.js
- types/options.d.ts
#1024
Make mutation work on class attribute changes also.
> refactor(options): Make render to react on class

- spec/api/api.axis-spec.js
- spec/api/api.category-spec.js
- spec/api/api.chart-spec.js
- spec/api/api.focus-spec.js
- spec/api/api.grid-spec.js
- spec/api/api.load-spec.js
- spec/api/api.region-spec.js
- spec/api/api.selection-spec.js
- spec/api/api.show-spec.js
- spec/api/api.tooltip-spec.js
- spec/api/api.zoom-spec.js
- spec/assets/util.js
- spec/interactions/interaction-spec.js
- spec/internals/axis-spec.js
- spec/internals/bb-spec.js
- spec/internals/color-spec.js
- spec/internals/core-spec.js
- spec/internals/data-spec.js
- spec/internals/grid-spec.js
- spec/internals/legend-spec.js
- spec/internals/selection-spec.js
- spec/internals/tooltip-spec.js
- spec/plugin/textoverlap/textoverlap-spec.js
- spec/shape/shape.arc-spec.js
- spec/shape/shape.bar-spec.js
- spec/shape/shape.bubble-spec.js
- spec/shape/shape.line-spec.js
Remove access d3 as global, importing as module on each test files
> test(all): Make to import d3 module

- config/banner.js
- package-lock.json
- package.json
- src/axis/Axis.js
- src/internals/util.js
- webpack.config.js
- yarn.lock
#1042
- Make d3 modules to be dependant as individual rather than the entire d3 module.
- Remove the use of Object.assign
> chore(dev-env): Update on d3 dependency

- src/plugin/stanford/Elements.js
- src/shape/arc.js
- src/shape/line.js
- src/shape/point.js
#1059
- Make element's css value to be string
- Revert on
https://github.com/naver/billboard.js/commit/54631506721bc64476d5c8fd64a2a681f3b340c1#diff-851f1a6e431d0ae7dc68b646d27821a8R90-R93
> fix(all): Fix possible IE9 style value

- spec/internals/axis-spec.js
- src/axis/Axis.js
#1068
Include subchart x axis on culling process.
Subchart x axis should be aligned with the x axis culling.
> fix(axis): Correct subchart x axis culling

- types/chart.d.ts
#1105
Add missing type definitions for data & zoom
> docs(types): Add missing type definition

- spec/api/api.zoom-spec.js
- spec/interactions/zoom-spec.js
- src/api/api.zoom.js
#1109
Add omitted argument for onzoom option callback.
> fix(zoom): Fix to pass domain arg on onzoom

- demo/demo.js
- spec/shape/shape.arc-spec.js
- src/config/Options.js
- src/shape/arc.js
- types/options.d.ts
#1128
Implementation of startingAngle option for pie & donut.
```js
donut: {
startingAngle: 0.5
},
pie: {
startingAngle: 1
}
```
> feat(arc): Intent to ship pie/donut.startingAngle

- demo/demo.js
- demo/simple-sidebar.css
- spec/internals/bb-spec.js
- src/config/Options.js
- src/internals/ChartInternal.js
- types/options.d.ts
#1131
Implementation of background option.
> feat(options): Intent to ship background

- spec/internals/axis-spec.js
- src/axis/Axis.js
- src/axis/AxisRenderer.js
- src/config/Options.js
- src/internals/size.js
- types/axis.d.ts
#1157, #1158
- Implement axis.y2.tick.rotate, to make consistent aligned as x and y tick.rotate
- Add missing data type for axis.padding
- Remove unused & undocumented axis.y.padding.ratio
> feat(axis): Intent to ship axis.y2.tick.rotate

- spec/interactions/interaction-spec.js
- src/interactions/interaction.js
- src/internals/color.js
#1168
Replace arc data names having space(or special chars).
`'data 1 2' --> 'data-1-2'`
> fix(arc): Fix handling spaced data name

- spec/internals/data-spec.js
- src/shape/line.js
#1172
Correct line commands for nullish data with regions options.
> fix(line): Fix nullish data rendering with regions

- spec/interactions/interaction-spec.js
https://github.com/naver/billboard.js/pull/1173#pullrequestreview-335177305
Update wrong assertion test for selection with data names.
> test(interaction): Update arc selector assertion

- spec/interactions/interaction-spec.js
- src/data/data.js
#1199
Make sure to filter nullish data when finding closest data points.
> fix(interaction): Fix null data point interaction

- src/data/data.convert.js
- Replace for loop to .forEach
- Moved ._convertCsvTsvToData() as separate private function
> refactor(data): Refactoring on data conversion

- package.json
#1190
Add npmName, npmFileMap as cdnjs doc states:
https://github.com/cdnjs/cdnjs/blob/master/CONTRIBUTING-WIP.md#23-auto-update-example
> chore(package.json): Add info for cdnjs Auto-upate

- spec/shape/shape.radar-spec.js
- src/internals/ChartInternal.js
- src/internals/text.js
- src/shape/radar.js
#1241
- Fix excluding text rendering for 'radar' type
- Fix text element's x/y attributes to pass indexed value correctly
> fix(radar): Correct text label not showing

- types/chart.d.ts
#1248
Fix incorrect data return types for .data() APIs.
> chore(types): Correct .data() APIs types

- spec/internals/axis-spec.js
- src/axis/AxisRenderer.js
#1271
When <title> element is already appended, make to use them rather than appending.
> fix(axis): Fix adding duplicated <title> element

- spec/internals/axis-spec.js
- src/axis/Axis.js
- src/internals/size.js
#1270
- Add condition to handle axis label when tick.rotate option applied
- Refactored axis label position related code
> fix(axis): Fix axis label text position

- spec/internals/axis-spec.js
- src/axis/Axis.js
#1273
- Fix the side-effect caused by the change.
Correct y Axis label positioning.
> skip: fix the side-effect #1273

- spec/interactions/interaction-spec.js
- src/internals/ChartInternal.js
- src/internals/grid.js
#1239
On touch environment, make focus grid line to be maintained on resize(rotate)
> fix(grid): Fix focus grid to be maintained on resize

- demo/demo.js
- src/internals/size.js
Ref https://github.com/naver/billboard.js/pull/1250#issuecomment-600575228
- Reduced the data length of the demo to make more clearly distingish autorotate option in action
- Update the missing code during the merge
> skip: Update missing from #1250 merge

- src/shape/point.js
#1287
Replace the use of classList to not break legacy browser compatibility.
> fix(point): Replace the use of classList

- spec/assets/util.js
- spec/shape/shape.arc-spec.js
- src/shape/arc.js
#1298
Explicitly remove text where is not shown.
> fix(arc): Fix label text update w/threshold

- .dependabot/config.yml
- package.json
- yarn.lock
#1299
Add dependabot config file
- https://dependabot.com/docs/config-file/
> chore(dev-env): Add dpendabot config

- spec/assets/common.css
- spec/internals/tooltip-spec.js
- src/internals/tooltip.js
#1362
Update tooltip left position value when is displaying for the rightest positined data point.
> fix(tooltip): Fix tooltip rightest positioning

- spec/shape/shape.line-spec.js
- src/shape/shape.js
#1368
#1336
Get correct offset data value
> fix(shape): Fix step type data label text position

- demo/demo.js
- spec/internals/axis-spec.js
- src/axis/Axis.js
- src/axis/AxisRenderer.js
#1392
- When axis.x.tick.count option value is given greater the current data  value size, update the count to the data value size for category x Axis
- Refactoring of Axis.js and AxisRenderer.js
- Remove unecessary tick.count option for XAxisTickAutorotate demo
> fix(axis): Fix duplicated axis text generation

- spec/internals/grid-spec.js
- src/internals/grid.js
#1407
Fix x grid positioning function.
> fix(grid): Fix x grid positioning & rendering

- package.json
- yarn.lock
#1424, #1425, #1426, #1428
Update dependencies to the latest
> chore(deps-env): Update dependency

- src/ChartInternal/internals/text.ts
- src/ChartInternal/internals/type.ts
- src/ChartInternal/shape/arc.ts
- src/ChartInternal/shape/bar.ts
- src/config/Options/shape/gauge.ts
- test/shape/arc-spec.ts
- types/options.d.ts
#1439
- Implement labe.threshold for gauge
- Update $el.text to refer data label text element for Arc types
> feat(gauge): Intent to ship gauge.label.threshold

- package.json
- yarn.lock
#1487, #1489, #1490, #1491
Update dependencies to the latest
> chore(deps-env): update dependencies

- config/webpack.config.development.js
- config/webpack.config.packaged.js
- config/webpack.config.plugin.js
- config/webpack.config.production.js
- config/webpack.config.theme.js
- package.json
- yarn.lock
#1494
- Apply API changes of webpack-merge
- Update dependencies to the latest
> chore(dev-env): update webpack-merge config

- types/bb.d.ts
- types/index.d.ts
#1520
Add exports for shapes and interaction modules in types definition.
> fix(types): add missing named exports

- src/ChartInternal/shape/area.ts
- src/ChartInternal/shape/line.ts
- test/api/load-spec.ts
#1547
Make sure to pass <g class=bb-chart-line> element for area node generation.
> fix(area): Fix dynamic area loading

- src/config/Options/common/main.ts
- src/config/Options/common/tooltip.ts
- types/axis.d.ts
- types/chart.d.ts
- types/options.d.ts
#1551
- Specify explicitly this context for all callbacks
- Remove ctx params from examples docs
> fix(types): Specify context for callbacks

- package.json
- types/axis.d.ts
- types/bb.d.ts
- types/options.d.ts
- types/plugin/bubblecompare/index.d.ts
- types/plugin/bubblecompare/options.d.ts
- types/tslint.json
- types/types.d.ts
- yarn.lock
#1615
- Update missing param types for donut.ratio
- Remove unused npm script for type cheking
- Add dtslint to be checked before push
> fix(types): Fix donut option types

- src/ChartInternal/interactions/eventrect.ts
- src/ChartInternal/shape/shape.ts
- test/esm/bar-spec.ts
- test/esm/esm-spec.ts
#1619, #1620
- Add conditional to check when only 'bar' named binding is imported.
- Add test codes for ESM
> fix(bar): Fix not firing data.onclick

- demo/index.html
- src/scss/theme/datalab.scss
#241
New 'datalab' theme.
The screenshot can be found at:
- https://github.com/naver/billboard.js/wiki/Themes
> feat(theme): Add new 'datalab' theme

- src/ChartInternal/data/data.ts
- src/ChartInternal/interactions/eventrect.ts
- test/interactions/zoom-spec.ts
- test/internals/tooltip-spec.ts
#1651
- Be sure event target element to be event rect element
- Make evaluate event rect clientBoundingRect after the UI thread execution
> fix(interaction): fix for data point click on mobile

- config/deploy.sh
- src/module/util.ts
#1666
- Terminate deploy script for 'next' branch
- Add @private for findIndex()
> chore(release): fix not to deploy next tag to gh-pages

- src/ChartInternal/internals/legend.ts
- src/ChartInternal/shape/shape.ts
- test/esm/bar-spec.ts
#1663
Condition is removed after the build, where is causing unexpected issue.
Update condition to not be removed from the build.
> fix(shape): fix possible condition removal by transpiler

- src/Plugin/Plugin.js
#1665
Plugin dev from the  JS based project could face extra work because of the TS based Plugin class.
So, providing JS version will solve the issue.
> feat(plugin): Add JS  Plugin class file

- src/ChartInternal/interactions/interaction.ts
- test/assets/helper.ts
- test/assets/util.ts
- test/esm/bar-spec.ts
#https://github.com/naver/billboard.js/issues/1663#issuecomment-690991679
- Add condition to execute $$.unexpandCircles()
- Split test's util file to be helper/util for ESM test
> fix(bar): fix on bar tooglip grouped false

- src/ChartInternal/internals/tooltip.ts
- test/api/tooltip-spec.ts
#1715
Add condition to execute related code only when tooltip element exists.
> fix(tooltip): fix error throwing for tootip.show=false

- src/ChartInternal/interactions/eventrect.ts
- test/api/chart-spec.ts
#1752
Make sure referencing event rect element when updating event rect's
dimension.
> fix(event): fix referencing event element

- src/ChartInternal/shape/arc.ts
- src/ChartInternal/shape/gauge.ts
- test/shape/gauge-spec.ts
#1759
Max label text should reflect data value, regardless the max option value set.
> fix(gauge): fix to be consistent max label value

- demo/demo.js
- src/ChartInternal/internals/text.ts
- src/config/Options/data/data.ts
- src/config/Options/shape/donut.ts
- src/config/Options/shape/gauge.ts
- test/internals/data-spec.ts
- types/options.d.ts
#1784
- Implement multiline using '\n'
- Update description for line break
> feat(data): Intent to ship data.label multiline

- src/ChartInternal/interactions/eventrect.ts
- test/esm/scatter-spec.ts
#1795
Add condition to check $$.toggleShape to be run.
> fix(eventRect): fix data.onclick work for scatter/bubble

- config/webpack/development.js
- src/ChartInternal/shape/arc.ts
- src/ChartInternal/shape/gauge.ts
- src/config/Options/shape/gauge.ts
- test/shape/gauge-spec.ts
- types/options.d.ts
#1804
Implement gauge.background.
```js
gauge: {
background: "red"
}
```
> feat(gauge): Intent to ship gauge.background

- src/module/browser.ts
#1778
Update the way of checking global and try..catch block to prevent undefined error.
> chore(browser): udpate retrive of global

- .github/workflows/test-deploy.yml
#1756
Add release & deploy steps
> chore(ci): add release step

- src/module/browser.ts
> fix(browser): fix retrieving global

- .github/workflows/ci.yml
- .github/workflows/release.yml
#1756
Split release workflow from CI workflow.
> chore(workflows): update release

- types/chart.d.ts
#1848
Fix wrong data type definition.
> fix(types): fix .load() data type

- src/ChartInternal/data/data.ts
- src/ChartInternal/internals/legend.ts
- test/internals/legend-spec.ts
- test/internals/tooltip-spec.ts
#1847
Fix insconsistent param format for color callback function
> fix(color): fix color callback mismatch

- src/ChartInternal/shape/arc.ts
- test/internals/color-spec.ts
- test/internals/tooltip-spec.ts
Fix color value setting caused by the #1857
#1847
> fix(arc): fix setting color value

- src/Chart/api/tooltip.ts
- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/interactions/interaction.ts
- src/ChartInternal/internals/tooltip.ts
- src/ChartInternal/shape/arc.ts
- src/config/Options/common/tooltip.ts
- test/api/tooltip-spec.ts
#1859
- fix tooltip.show() api not working for arc types
- fix tooltip.init option not working for arc types
> fix(tooltip): fix arc's tooltip interaction

- src/ChartInternal/data/IData.ts
- src/ChartInternal/shape/arc.ts
- src/config/Options/data/data.ts
- src/config/Options/shape/radar.ts
- test/internals/data-spec.ts
- types/options.d.ts
#1863
- When data.order is given a function for arc type, make to invoke.
- Add examples code usiing data.order function
> fix(data): fix data.order to work for arc types

- src/ChartInternal/data/data.ts
- src/ChartInternal/shape/arc.ts
- src/config/Options/data/data.ts
- types/options.d.ts
#1863
Remove inconsistency between arc & other sort data param type.
> refactor(data): make consistent sort data param type

- src/Chart/api/zoom.ts
- test/api/zoom-spec.ts
#1868
Correct passing parsed domain value for withinRange()
> fix(api): fix zoom for timesries axis

- src/ChartInternal/shape/point.ts
- test/internals/legend-spec.ts
#1887
Incorrect id value was set for custom data point.
Side-effect caused by 6ff9aec0
> fix(point): fix usePoint defs id value

- src/ChartInternal/shape/bar.ts
- test/shape/bar-spec.ts
#1907
Fix to take based domain value when calculate bars width size.
> fix(bar): fix bar width on zoom

- src/ChartInternal/internals/grid.ts
- test/interactions/interaction-spec.ts
- test/internals/grid-spec.ts
#1924
Grid initialization should be processed even interaction is disabled.
> fix(grid): fix rendering when interaction is disabled

- src/ChartInternal/interactions/subchart.ts
- src/ChartInternal/internals/class.ts
- src/ChartInternal/internals/text.ts
- src/ChartInternal/shape/arc.ts
- src/ChartInternal/shape/area.ts
- src/ChartInternal/shape/bar.ts
- src/ChartInternal/shape/line.ts
- src/ChartInternal/shape/point.ts
- src/ChartInternal/shape/radar.ts
- test/internals/color-spec.ts
Simplify redundant class functions.
> refactor(class): refactor getting classes

- src/ChartInternal/shape/line.ts
- test/api/load-spec.ts
#1938
Fix side-effect caused by 9d6e1e0.
> fix(api): fix loading area-line-range

- src/ChartInternal/Axis/Axis.ts
- src/ChartInternal/Axis/AxisRenderer.ts
- src/ChartInternal/internals/redraw.ts
- test/interactions/subchart-spec.ts
- test/internals/legend-spec.ts
#1949
- Make to not transitioning x Axis ticks during zooming action
- Fix legend transitioning when transition.duration=0
> fix(zoom): fix x Axis tick transition during zoom

- src/ChartInternal/internals/legend.ts
- test/api/show-spec.ts
#1950
Make sure to remove inline opacity when .hide() is called
> fix(legend): fix hiding via .hide()

- package.json
- yarn.lock
Fix dependency security vulnerability
> chore(deps-dev): fix dependency vulnerability

- src/ChartInternal/internals/tooltip.ts
- test/internals/tooltip-spec.ts
#1979
Prevent propagation among instances if isn't instantiated from the user's event
> fix(tooltip): fix linked tooltip recursive call

- src/ChartInternal/internals/size.ts
- test/internals/axis-spec.ts
#1990
Do not call unnecessary axis.create()
> fix(axis): fix axis.x.tick.tooltip on rotated axis

- src/Chart/api/subchart.ts
- src/config/resolver/interaction.ts
- test/api/subchart-spec.ts
- types/chart.d.ts
#1993
Implement new subchart APIs
- .subchart.show()
- .subchart.hide()
- .subchart.toggle()
> feat(api): Intent to ship subchart APIs

- src/index.esm.ts
- test/esm/esm-spec.ts
#2007
Fix to export candlestick module
> fix(candlestick): fix exporting candlestick module

- src/ChartInternal/internals/type.ts
- test/internals/data-spec.ts
#2020
Filter nullish data to exclude from rendering
> fix(type): filter nullish data

- .husky/commit-msg
- .husky/pre-push
- config/webpack/development.js
- package.json
- yarn.lock
#2014, #2015, #2016, #2017, #2018
- Update webpack-dev-server v4 beta1 and its configurations
- Upgrade husky to v6 and its configurations
- Update dev dependencies to the latest
> chore(dev-deps): update webpack-dev-server and husky

- src/Chart/api/tooltip.ts
- src/ChartInternal/interactions/eventrect.ts
- src/ChartInternal/interactions/interaction.ts
- src/ChartInternal/shape/bar.ts
- src/ChartInternal/shape/shape.ts
- src/scss/billboard.scss
- src/scss/theme/datalab.scss
- src/scss/theme/graph.scss
- src/scss/theme/insight.scss
- test/shape/candelstick-spec.ts
#2036
- Add expand/unexpand class name during interaction
- Refactor expand/unexpand codes
> fix(candlestick): fix to set expand state

- demo/demo.js
- src/ChartInternal/interactions/subchart.ts
- src/config/Options/interaction/subchart.ts
- test/interactions/subchart-spec.ts
- types/options.d.ts
#2044
Implement subchart.showHandle option
```js
subchart: {
show: true,
// will show subchart's handlebar
showHandle: true
}
```
> feat(subchart): Intent to ship subchart.showHandle

- package.json
- yarn.lock
update dependency to fix security vulnerability
> chore(dev-deps): udpate dependency

- src/ChartInternal/data/data.ts
- test/internals/axis-spec.ts
#2096
Do not exclude nullish data to determine axis' max value
for grouped data.
> fix(data): Fix nullish data filtering for grouped data

- src/ChartInternal/interactions/zoom.ts
- src/ChartInternal/internals/tooltip.ts
- test/interactions/zoom-spec.ts
- test/internals/tooltip-spec.ts
#2095
- Update eventReceiver.coords during 'wheel' zoom
- Fix tooltip position, to use correct zoom scale
> fix(zoom): Fix incorrect tooltip position

- src/ChartInternal/data/IData.ts
- src/ChartInternal/data/data.ts
- src/ChartInternal/interactions/zoom.ts
- test/interactions/interaction-spec.ts
#2104
Remove data.onclick call from zoom drag 'end' event
> fix(data): Fix duplicated data.onclick call

- src/ChartInternal/shape/point.ts
- test/shape/point-spec.ts
#2107
Exclude position computation for nullish data
> fix(point): Fix custom point for nullish data

- demo/demo.js
- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/data/IData.ts
- src/ChartInternal/internals/color.ts
- src/ChartInternal/internals/text.ts
- src/ChartInternal/shape/arc.ts
- src/config/Options/data/data.ts
- test/internals/data-spec.ts
- types/options.d.ts
#1954
Implementation for new data.labels.backgroundColors option
> feat(data.labels): Intent to ship data.labels.backgroundColors

- src/ChartInternal/data/load.ts
- src/module/util.ts
Only transtion when transition.duration is truthy.
> refactor(load): do not transit on unload

- src/ChartInternal/data/IData.ts
- src/ChartInternal/internals/grid.ts
- src/ChartInternal/internals/scale.ts
- test/interactions/zoom-spec.ts
#2156
- Make .xv() to use zoom scale when is present
- Specify data type parameter within scale.ts
> fix(zoom,grid): fix grid line pos during zoom

- src/ChartInternal/internals/color.ts
- src/ChartInternal/internals/text.ts
- test/internals/data-spec.ts
#2160
Suffix data id value to handle spaced data ids.
> fix(data): Handle spaced data name for label bg color

- config/webpack/plugin.js
- demo/demo.js
- demo/index.html
- src/Plugin/tableview/Options.ts
- src/Plugin/tableview/const.ts
- src/Plugin/tableview/index.ts
- test/plugin/bubble-compare/bubble-compare-spec.ts
- test/plugin/tableview/tableview-spec.ts
- types/plugin/tableview/index.d.ts
- types/plugin/tableview/options.d.ts
#1873
```js
const chart = bb.generate({
...
plugins: [
new bb.plugin.tableview({
selector: "#my-table-view",
categoryTitle: "Year",
categoryFormat: function(v) {
// do some transformation
...
return v;
},
class: "my-class-name",
style: true,
title: "My Data List",
updateOnToggle: false
}),
]
});
```
> feat(plugin): Intent to ship TableView plugin

- src/ChartInternal/Axis/AxisRendererHelper.ts
- test/api/flow-spec.ts
#2189
Handle transitionise to return more accurately
with the given param values.
> fix(Axis): fix transition on flow

- src/ChartInternal/Axis/AxisRenderer.ts
- test/internals/axis-spec.ts
#2210
Add conditional check on getting tickInteval.
> fix(axis): fix bar type tick.fit=false throwing error

- src/Chart/api/chart.ts
- test/api/subchart-spec.ts
#2201
Hide zoom reset button during subchart's toggle.
> fix(api): fix subchart APIs usage with zoom reset button

- src/Chart/api/regions.ts
- src/Chart/api/show.ts
- src/Chart/api/zoom.ts
- src/ChartInternal/Axis/Axis.ts
- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/data/load.ts
- src/ChartInternal/interactions/drag.ts
- src/ChartInternal/interactions/subchart.ts
- src/ChartInternal/internals/grid.ts
- src/ChartInternal/internals/legend.ts
- src/ChartInternal/internals/redraw.ts
- src/ChartInternal/internals/region.ts
- src/ChartInternal/internals/selection.ts
- src/ChartInternal/internals/text.ts
- src/ChartInternal/internals/transform.ts
- src/ChartInternal/shape/arc.ts
- src/ChartInternal/shape/area.ts
- src/ChartInternal/shape/bar.ts
- src/ChartInternal/shape/candlestick.ts
- src/ChartInternal/shape/line.ts
- src/ChartInternal/shape/point.ts
- src/ChartInternal/shape/radar.ts
- src/config/Options/common/main.ts
- test/api/zoom-spec.ts
- test/internals/data-spec.ts
- test/internals/grid-spec.ts
Every transition should be consistent with the given
transition.duration option value.
To handle this, added .$T() to control every transition
selections.
> refactor(transition): make consistent transition

- src/ChartInternal/Axis/Axis.ts
- src/ChartInternal/Axis/AxisRenderer.ts
- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/internals/text.ts
#2232
Consistent transition for axis
> refactor(axis): consistent transition on axis

- src/module/browser.ts
#2247
Fallback when window.requestIdleCallback not exists.
> fix(browser): add requestIdleCallback fallback

- src/ChartInternal/data/data.ts
- src/ChartInternal/internals/text.ts
- src/ChartInternal/shape/bar.ts
- test/shape/bar-spec.ts
#2251
Return 0(zero) getting ratio, when all data values are 0(zero).
> fix(bar): fix data label to be shown for 0 values

- src/ChartInternal/interactions/interaction.ts
- src/ChartInternal/interactions/zoom.ts
- test/esm/subchart-spec.ts
#2255
Move .unbindZoomEvent() from zoom.ts --> interaction.ts
> fix(subchart): fix subchart esm import failure

- src/ChartInternal/internals/tooltip.ts
- test/internals/tooltip-spec.ts
#2265
Fix call context for tooltip.position
> fix(tooltip): fix tooltip.position call context

- src/Chart/api/chart.ts
- src/Chart/api/tooltip.ts
- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/interactions/eventrect.ts
- src/ChartInternal/interactions/interaction.ts
- src/ChartInternal/internals/domain.ts
- src/ChartInternal/internals/grid.ts
- src/ChartInternal/internals/redraw.ts
- src/ChartInternal/internals/scale.ts
- src/ChartInternal/internals/size.axis.ts
- src/ChartInternal/internals/size.ts
- src/ChartInternal/internals/tooltip.ts
- src/ChartInternal/shape/arc.ts
- src/ChartInternal/shape/shape.ts
Replace all condtional checking property existence by
optional chaining operator.
> refactor(all): simplify condition by optional chaining

- src/ChartInternal/ChartInternal.ts
- src/config/const.ts
- src/module/error.ts
- src/module/util.ts
- test/api/axis-spec.ts
- test/api/category-spec.ts
- test/api/data-spec.ts
- test/api/focus-spec.ts
- test/api/grid-spec.ts
- test/api/legend-spec.ts
- test/assets/module/util.ts
- test/assets/util.ts
- test/esm/esm-error-spec.ts
- test/internals/bb-spec.ts
- test/internals/class-spec.ts
- test/shape/arc-spec.ts
#2311
Throw error and give more informative message when module isn't
specified or load correctly.
ex)
When `area-line-range` is specified as `data.type`, but isn't imported nor specified correctly, will error log as follows.
> feat(error): Enhance error logging for ESM import

- src/ChartInternal/internals/grid.ts
- src/module/util.ts
- test/assets/util.ts
- test/esm/bar-spec.ts
#2310
Make the call of .showcircleFocus() by optional chaining,
to prevent possible error.
> fix(grid): pPrevent error othrow

- src/ChartInternal/interactions/zoom.ts
- test/interactions/zoom-spec.ts
#2343
Check event source prop value by optional chaining,
to not throw unexpected error.
> fix(zoom): Fix error throw on drag zoom interaction

- src/ChartInternal/Axis/Axis.ts
- src/ChartInternal/shape/arc.ts
- src/scss/billboard.scss
- src/scss/theme/datalab.scss
- src/scss/theme/graph.scss
- src/scss/theme/insight.scss
#2209
- Remove gauge title inline style setting, and moves to be done from css file
- Remove unused rules
> refactor(style): remove unused/inline style rules

- package.json
- types/types.d.ts
#2422
- Fix candlestick data type definition
- Add d3 type definition
- Remove unused script command
> fix(types): fix candlestick data type

- src/ChartInternal/data/data.ts
- src/ChartInternal/shape/bar.ts
- src/ChartInternal/shape/shape.ts
- test/internals/tooltip-spec.ts
#2434
- Make handling candlestick type shape in .findClosest()
- Move .isWithinBar() from bar.ts -> shape.ts
> fix(tooltip): fix candlestick tooltip display with xs option

- demo/demo.js
- src/ChartInternal/data/data.ts
- src/ChartInternal/shape/bar.ts
- src/ChartInternal/shape/shape.ts
- src/config/Options/shape/bar.ts
- test/shape/bar-spec.ts
#2428
Implement bar radius for stacking bars
> feat(bar): Implement stacking bar radius

- src/ChartInternal/shape/bar.ts
- src/ChartInternal/shape/shape.ts
#2428
Reinforce the conditional for stacking bar check
> refactor(bar): refactor on draw bar

- src/ChartInternal/shape/arc.ts
- src/ChartInternal/shape/radar.ts
- test/interactions/interaction-spec.ts
#2477
Add missing event value set to state
> fix(event): fix touch event handling on arc

- types/axis.d.ts
- types/chart.d.ts
#2499
Fix wrong types gropings for some axis options.
> fix(types): Fix axis types defintion

- src/ChartInternal/Axis/Axis.ts
- src/ChartInternal/internals/domain.ts
- test/internals/domain-spec.ts
#2523
Make sure to check given data value to check zerobased type
with correlated bound axis.
> fix(domain): Fix incorrect domain updates

- src/module/util.ts
#2526
Touch detection based on navigator.userAgent isn't trustable.
Add some conditionals based on feature detection.
> refactor(util): Avoid touch detection by userAgent

- src/ChartInternal/Axis/Axis.ts
- test/api/subchart-spec.ts
#2556
Add conditional to check if tick text node exists
> fix(axis): Fix error when tick text isn't accessible

- webpack.config.cjs
#2560
Make to use env variable
> fix(build): Fix incorrect versioning on build

- src/ChartInternal/Axis/Axis.ts
- test/internals/axis-spec.ts
#2571
Remove conditional added from #2523
> fix(axis): fix hidden axis rescale on dynamic load

- src/ChartInternal/Axis/Axis.ts
- test/internals/axis-spec.ts
#2582
Make text node's visibility to be updated from the possible visibility status.
> fix(axis): Fix culling visibility on dynamic loading

- src/ChartInternal/interactions/flow.ts
- test/api/flow-spec.ts
#2595
Set flow start index value to zero when data's x is nullable.
> fix(api): Fix flow on indexed/category axis type

- src/module/generator.ts
- src/module/util.ts
- test/internals/generator-spec.ts
#2606
Add bulletproof code, when tab isn't visible terminate the loop.
> fix(generator): Prevent possible infinite loop when tab isn't visible

- babel.config.cjs
- package.json
- src/ChartInternal/Axis/AxisRenderer.ts
- yarn.lock
#2671 #2664 #2665 #2666 #2667
- Make arrow function to be wrapped as '.bind(this)'
https://babeljs.io/docs/en/babel-plugin-transform-arrow-functions#spec
- Update Axis 'this' code to make transpiled correctly
> fix(build): Fix this keyword transpile

- src/ChartInternal/internals/scale.ts
- test/interactions/zoom-spec.ts
#2667
Make sure getting subX's scale.
> fix(scale): fix getting tickOffset

- demo/demo.js
- package.json
- src/ChartInternal/internals/text.ts
- src/config/Options/data/data.ts
- test/internals/text-spec.ts
- types/options.d.ts
- yarn.lock
#2662
Implement data.labels.rotate option
```js
data: {
labels: {
rotate: 90
}
}
```
> feat(data): Intent to ship data.labels.rotate

- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/internals/redraw.ts
- test/internals/bb-spec.ts
#2650
Fix legend not resized properly during resize events
> fix(resize): Fix legend resize

- src/ChartInternal/ChartInternal.ts
- test/internals/bb-spec.ts
#2726 
Fix call context to be Chart instance
> fix(option): Fix onresize/onresized call context

- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/internals/class.ts
- src/ChartInternal/internals/color.ts
- src/ChartInternal/internals/legend.ts
- src/ChartInternal/internals/style.ts
- src/ChartInternal/internals/text.ts
- src/ChartInternal/shape/arc.ts
- src/ChartInternal/shape/bar.ts
- src/ChartInternal/shape/line.ts
- src/ChartInternal/shape/point.ts
- src/config/Store/State.ts
- test/internals/boost-spec.ts
#2736
- Split related methods to style.ts
- Expand applying to legend and Arc elements
> refactor(option): refactor useCssRule implementation

- src/Chart/api/data.ts
- src/Chart/api/selection.ts
- src/ChartInternal/Axis/AxisRenderer.ts
- src/ChartInternal/Axis/AxisRendererHelper.ts
- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/data/convert.ts
- src/ChartInternal/data/data.ts
- src/ChartInternal/interactions/drag.ts
- src/ChartInternal/internals/color.ts
- src/ChartInternal/internals/domain.ts
- src/ChartInternal/internals/format.ts
- src/ChartInternal/internals/region.ts
- src/ChartInternal/internals/scale.ts
- src/ChartInternal/internals/size.axis.ts
- src/ChartInternal/internals/style.ts
- src/ChartInternal/internals/text.ts
- src/ChartInternal/internals/tooltip.ts
- src/ChartInternal/shape/arc.ts
- src/ChartInternal/shape/area.ts
- src/ChartInternal/shape/bar.ts
- src/ChartInternal/shape/point.ts
- src/ChartInternal/shape/polar.ts
- src/ChartInternal/shape/shape.ts
- src/Plugin/sparkline/index.ts
- src/Plugin/textoverlap/index.ts
- src/config/Options/data/data.ts
- src/config/Store/Element.ts
- src/module/Cache.ts
- src/module/generator.ts
- src/module/util.ts
Ref.
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-export
> style(all): specify type only imports

- src/ChartInternal/data/convert.ts
- src/module/util.ts
- src/module/worker.ts
- test/assets/module/util.ts
- test/internals/boost-spec.ts
#2778
- Release URL object after worker execution is done
- Reuse Blob object for same function
> fix(options): Fix possible memory leak for boost.useWorker

- src/ChartInternal/shape/line.ts
- test/shape/area-spec.ts
#2826
Make sure area element to be generated only for area types.
> fix(area): Fix unnecessary area element generation

- types/index.d.ts
#2833
Export 'polar' module from the type definition
> fix(type): Add missing polar module export

- src/ChartInternal/ChartInternal.ts
- tsconfig.json
#2856
- Update entry point from tsconfig https://stackoverflow.com/a/57730727/4427557
- Update to remove ambiguity using 'type' reserved keyword on named binding import
> fix(typescript): update entry point in tsconfig

- demo/demo.js
- src/ChartInternal/internals/color.ts
- src/ChartInternal/shape/area.ts
- src/ChartInternal/shape/bar.ts
- src/config/Options/shape/bar.ts
- test/shape/area-spec.ts
- test/shape/bar-spec.ts
- types/options.d.ts
#397
Implement gradient color for bar
```js
bar: {
linearGradient: true // or set an object value to specify more in detail
}
```
> feat(options): Intent to ship bar.linearGradient

- src/ChartInternal/internals/legend.ts
Split big complicated one function to smaller ones.
> refactor(legend): Destruct .updateLegendElement()

- src/ChartInternal/data/IData.ts
- src/ChartInternal/interactions/interaction.ts
- test/interactions/interaction-spec.ts
#2901
Fix onover/onout event call on same x axis bar shape.
> fix(interaction): Fix incorrect data.onover/out event call

- src/ChartInternal/interactions/eventrect.ts
- test/interactions/interaction-spec.ts
- test/internals/tooltip-spec.ts
#2913
Fix the first and last x Axis' event receiver coordinate width to fully occupy x Axis space
> fix(eventrect): Fix eventReceiver coordinates

- src/ChartInternal/Axis/AxisRendererHelper.ts
- test/internals/axis-spec.ts
#2924
Check the given x tick value to get correct scale.
> fix(axis): Fix translate NaN error

- src/ChartInternal/shape/arc.ts
- src/config/Options/shape/arc.ts
- test/shape/arc-spec.ts
- types/options.shape.d.ts
#2938
- Fix arc command param flag value setting error during transition
- Add test to check interpolated Arc path during transition
> skip: fix cornerRadius transition error

- src/ChartInternal/shape/line.ts
- test/internals/data-spec.ts
- test/shape/line-spec.ts
#2950
Remove unnecessary padding for category type axis
> fix(options): Fix data.regions path rendering for category axis

- src/Chart/api/chart.ts
- Add detail description for key name argument usage
- Add conditional to make sure to return initial generation option when no argument is given
> refactor(api): update .config() API doc & condition

- types/chart.d.ts
#3037
Fix wrong .grid API parameter type
> fix(type): fix wrong .grid() API param type

- src/Chart/api/data.ts
- src/Chart/api/grid.x.ts
- src/Chart/api/grid.y.ts
- src/Chart/api/regions.ts
#3047
Change function definition to named function
to make JSDoc builder to parse and generate without duplication.
> docs(api): Remove method duplication

- src/ChartInternal/internals/text.ts
- src/ChartInternal/shape/bar.ts
- test/shape/bar-spec.ts
#3049
Fix the overflow condition to be skipped for inverted axis.
> fix(bar): Fix drawing on inverted axis

- types/chart.d.ts
- types/options.d.ts
#3037
Align region interface to be used on option and api
> fix(type): align grid api with option interface

- src/ChartInternal/data/data.ts
#3055
Do not compute ratio when the index total is zero.
> fix(data): Fix ratio calculation

- packages/react/CHANGELOG.md
- packages/react/README.md
- packages/react/demo/App.tsx
- packages/react/package.json
- packages/react/src/index.tsx
- packages/react/yarn.lock
#3077
- Export option type interface from billboard.js
- Fix some type missmatch
> fix(type): fix to export option type definition

- src/ChartInternal/data/data.ts
- test/internals/data-spec.ts
#3096
Remove the strict length check to determine ranged data type to mitigate unexpected error when data length exceed.
> fix(data): mitigate bar/bubble ranged data to handle data length exceed

- src/module/util.ts
- test/api/chart-spec.ts
#3098
To remove potential return of same value from Math.random(), replace it by crypto.getRandomValues().
> refactor(util): remove the use of Math.random()

- src/ChartInternal/data/data.ts
- src/ChartInternal/interactions/eventrect.ts
- test/internals/data-spec.ts
#3124
Fix convert data for step when has no value
> fix(data): fix break when whole dataseries are null

- src/ChartInternal/data/convert.ts
- src/ChartInternal/internals/type.ts
- test/internals/type-spec.ts
#3125
Check when falsy and non-valid chart type value is specified.
> fix(options): Fix handling for falsy data.types

- src/ChartInternal/shape/point.ts
- src/Plugin/sparkline/index.ts
- test/plugin/sparkline/sparkline-spec.ts
- types/options.d.ts
#3171
Handle point.focus.only option
> fix(sparkline): Fix to work point.focus.only option

- demo/chart.js
- demo/demo.js
- demo/tomorrow.css
- src/Chart/Chart.ts
- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/data/data.ts
- src/ChartInternal/internals/size.ts
- src/ChartInternal/shape/arc.ts
- src/config/Options/common/legend.ts
- src/config/Options/shape/arc.ts
- src/config/Options/shape/donut.ts
- src/config/Options/shape/gauge.ts
- src/config/Store/State.ts
- src/config/classes.ts
- src/scss/billboard.scss
- src/scss/theme/datalab.scss
- src/scss/theme/graph.scss
- src/scss/theme/insight.scss
- test/shape/arc-needle-spec.ts
- types/options.shape.d.ts
#3205
Implement arc.needle option
- Generation options:
```js
[donut | gaguge]: {
// when 'arc.needle.show=true' is set, will able to use template to reflect needle value
title: "{=NEEDLE_VALUE}"
},
arc: {
needle: {
show: true,
color: "red", // any valid CSS color
// for customized needle
path: function(length) {
const len = length - 20;
// will return upper arrow shape path
// Note: The path should begun from '0,0' coordinate to top center.
const path = `M 0 -${len + 20}
L -12 -${len}
L -5 -${len}
L -5 0
A 1 1 0 0 0 5 0
L 5 -${len}
L 12 -${len} Z`;
return path;
},
value: 40,  // will make needle to point value 40.
length: 80, // needle length in percentages relative to radius.
top: {
// rx and ry are the two radii of the ellipse;
// …
```
> feat(arc): Intent to ship arc.needle

- src/ChartInternal/interactions/eventrect.ts
- test/api/load-spec.ts
#3218
Fix the side effect caused by #3203.
Make sure to set proper class name for eventRect element.
> fix(api): fix classname setting for  eventRect element

- src/scss/billboard.scss
- src/scss/theme/graph.scss
- src/scss/theme/insight.scss
- test/api/chart-spec.ts
- test/api/export-spec.ts
- yarn.lock
#3222
shpe-rendering:crispEdge CSS property causing shape to not be rendered correctly on Windows.
Remove from dist CSS files to prevent the issue.
> fix(shape): Fix shape rendering issue on Windows

- demo/index.html
- demo/simple-sidebar.css
- demo/tomorrow.css
- src/scss/theme/dark.scss
> feat(theme): Intent to ship dark theme

- demo/demo.js
- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/shape/bar.ts
- src/config/Options/shape/bar.ts
- test/api/export-spec.ts
- test/shape/bar-spec.ts
- types/options.shape.d.ts
#2965
- Implement bar.front option
- Make eventRect element to stay at the top of shape elements
```js
bar: {
front: true
}
```
> feat(bar): Intent to ship bar.front

- demo/demo.js
- src/ChartInternal/data/IData.ts
- src/ChartInternal/data/data.ts
- src/ChartInternal/shape/bubble.ts
- src/ChartInternal/shape/point.ts
- src/config/Options/common/point.ts
- test/interactions/interaction-spec.ts
- test/internals/tooltip-spec.ts
- test/shape/point-spec.ts
- types/options.d.ts
#2568
Extend point.sensitivity option to able control the sensitivity of each data point
```js
point: {
// having lower value, means how closer to be for interaction
sensitivity: 3,
// sensitivity based on point's radius
sensitivity: "radius",
// callback for each point to determine the sensitivity
sensitivity: function(d) {
// ex. of argument d:
// ==> {x: 2, value: 55, id: 'data3', index: 2, r: 19.820624179302296}
// returning d.r, will make sensitivity same as point's radius value.
return d.r;
}
}
```
> feat(point): Enhance point.sensitivity

- src/ChartInternal/internals/grid.ts
- src/ChartInternal/internals/region.ts
- test/api/flow-spec.ts
- Merge separated updateXGridLines & updateYGridLines to single updateGridLines
- Do not generate text node when has no text value
> refactor(grid): Refactor grid update

- demo/chart.js
- src/Chart/api/export.ts
- src/ChartInternal/internals/tooltip.ts
- src/Plugin/tableview/index.ts
- src/module/util.ts
- test/assets/module/util.ts
- test/plugin/tableview/tableview-spec.ts
Re-einforce string replacement for script tag
> chore(plugin, api): Sanitize for possible security vulnerability

- src/Chart/api/axis.ts
#3343 
Add notes for .axis() methods, where only applicable for chart types which has x and y axes.
> docs(api): Add notes for .axis' methods

- src/ChartInternal/interactions/subchart.ts
- test/interactions/subchart-spec.ts
- test/internals/data-spec.ts
#3358
- Update handlebar path coordinate to ease control of the position
- Fix horizontal/vertical align based on the subchart height
> fix(subchart): Fix handlebar position

- test/api/subchart-spec.ts
#3342
Reinforce test case for subchart api
> test(subchart): add test case for subchart api

- src/ChartInternal/interactions/flow.ts
- test/api/flow-spec.ts
- test/interactions/drag-spec.ts
- test/internals/data-spec.ts
#3360
- Remove duplicated condition "v === 'gridLines.x'
- Update test generation options
> refactor(flow): Remove duplicated condition

- src/ChartInternal/internals/title.ts
- test/internals/title-spec.ts
#3363
fix title text alignment
> fix(title): fix center align

- src/ChartInternal/internals/category.ts
- test/api/category-spec.ts
- test/internals/tooltip-spec.ts
#3333
Reinforce test codees to increase coverage
> test(internals): Add tests for internals code

- src/Plugin/stanford/index.ts
- test/internals/text-spec.ts
- test/plugin/sparkline/sparkline-spec.ts
- test/plugin/stanford/stanford-spec.ts
- test/plugin/tableview/tableview-spec.ts
#3333
- Remove duplicated code from stanford plugin
- Reinforce test codes for plugins
> test(plugin): Add tests for plugins

- src/module/Cache.ts
- test/esm/esm-error-spec.ts
- test/module/module-spec.ts
#3333
- Fix cache remove bug when id is given as string
- Reinforce test for module
> test(module): Add test for module

- src/Plugin/stanford/Elements.ts
- test/plugin/stanford/stanford-elements-spec.ts
- test/plugin/stanford/stanford-spec.ts
#3333
Add test cases for timeseries and category type axis
> test(plugin): Reinforce stanford test

- test/plugin/stanford/stanford-elements-spec.ts
- test/plugin/tableview/tableview-spec.ts
#3333
Reinforce test for stanford & tableview plugins
> test(plugin): Add test for stanford & tableview

- src/module/worker.ts
- test/internals/boost-spec.ts
#3333 
- Add conditional for onerror logging
- Update test condition
> test(module): update test for worker

- src/ChartInternal/shape/candlestick.ts
- test/shape/candelstick-spec.ts
#3387
Fix rendering with negative values on rotated axis
> fix(candlestick): Fix rendering on rotated axis

- karma.conf.cjs
- src/ChartInternal/internals/category.ts
- src/module/browser.ts
- src/module/worker.ts
- test/api/category-spec.ts
- test/module/module-spec.ts
#3333
- update some browser & worker module as function to facilitate test
- add test case for internal/category
> test(module): Add test for module & category

- src/ChartInternal/internals/tooltip.ts
- test/internals/tooltip-spec.ts
#3392
Add test to check arguments passed to format.value function
> test(tooltip): Add test to check arguments value

- src/ChartInternal/shape/shape.ts
- test/shape/bar-spec.ts
#3372
When is same group, but bound to different xs,
should stack if they're at same x axis value
> fix(bar): Fix stacking bar position on multiple xs

- src/ChartInternal/data/data.ts
- src/ChartInternal/internals/redraw.ts
- src/ChartInternal/shape/shape.ts
- test/internals/tooltip-spec.ts
#3388
- Make .circleY() visible and included as part of common
- Move .circleY() to shape.ts file
> fix(shape): Fix circleY() undefined error

- src/ChartInternal/internals/clip.ts
- test/internals/axis-x-spec.ts
#3367
Make x Axis clipPath y coordinate to be fixed
> refactor(clipPath): fix side-effect caused by #3367

- src/ChartInternal/internals/tooltip.ts
#3407 
Remove optional chaining as a possible prevention from the fix of #3407 Can be removed, as of conditional from event interaction will prevent it.
> refactor(tooltip): Remove optional chainigs

- src/ChartInternal/internals/domain.ts
- src/ChartInternal/internals/size.axis.ts
- test/internals/axis-x-spec.ts
#3424
Fix conditional to check given value is numeric
> fix(axis): Fix axis.x.height=0 to be applied

- src/ChartInternal/Axis/Axis.ts
- src/ChartInternal/ChartInternal.ts
- src/ChartInternal/internals/clip.ts
- src/ChartInternal/internals/legend.ts
- src/ChartInternal/internals/size.axis.ts
- src/ChartInternal/internals/size.ts
- src/ChartInternal/internals/tooltip.ts
- src/ChartInternal/internals/transform.ts
- src/Plugin/stanford/index.ts
- src/config/Options/axis/y2.ts
- src/config/Options/common/main.ts
- test/internals/axis-spec.ts
- test/internals/padding-spec.ts
- test/internals/text-spec.ts
- test/internals/title-spec.ts
- test/internals/tooltip-spec.ts
- test/shape/arc-needle-spec.ts
- test/shape/area-spec.ts
- test/shape/bar-spec.ts
#3426
- Refactor getting padding values by direction
- Fix padding.bottom to follow from as other directions
- For more info, checkout the below documentation
- ℹ️ [Understanding padding](https://github.com/naver/billboard.js/wiki/Understanding-padding)
> fix(option): Fix inconsistency of padding

- src/ChartInternal/interactions/interaction.ts
- src/ChartInternal/internals/selection.ts
- src/ChartInternal/shape/point.ts
- src/Plugin/sparkline/index.ts
- test/esm/bar-spec.ts
#3456
Fix side effect caused by #3407.
Add prevention on call of .isPointFocusOnly()
> fix(point): Fix pointFucusOnly check error

- src/ChartInternal/internals/text.ts
- test/internals/text-spec.ts
#3547
Index argument passed to data.labels.format
should be couning nullish value
> fix(labels): Fix index argument for nullish value

- src/module/browser.ts
#3489
Fix the referencing error and the condition to prevent some potential issue.
side-effect caused by https://github.com/naver/billboard.js/commit/201a8e3ce7c3fe65085f17e7a0ed726cbf7ec325
> fix(module): Fix getFallback() uninitialized variable

- src/ChartInternal/internals/clip.ts
- src/ChartInternal/internals/size.ts
- src/ChartInternal/internals/transform.ts
- test/internals/padding-spec.ts
#3433
Adjust top padding on rotated axis
Adjust right padding for 'fit' mode with legend positioned at right
> fix(option): Fix rotated top padding

- test/assets/module/util.ts
> test(util): Fix browser module import path on Windows

- src/Chart/api/zoom.ts
- src/ChartInternal/data/load.ts
- src/ChartInternal/interactions/zoom.ts
- src/ChartInternal/internals/domain.ts
- src/ChartInternal/internals/scale.ts
- test/api/load-spec.ts
#3422
Fix dynamic data loading when zoom-in state,
to keep current zoom-in state and update scale according new data range
> fix(zoom): Fix zoom state on data load

- src/ChartInternal/internals/size.axis.ts
- test/internals/axis-spec.ts
#3643
Update condition determining x Axis tick is rotated to consider absolute number(weather positive or negative) value.
> fix(axis): Fix x Axis tick height calculation

- demo/types/types.js
- src/ChartInternal/Axis/AxisRenderer.ts
- src/ChartInternal/interactions/zoom.ts
- src/ChartInternal/shape/shape.ts
- test/interactions/zoom-spec.ts
#3636
Reflect x axis min/max on bar width calculation
> fix(bar): Fix bar's width update with x axis min/max

- src/config/Store/State.ts
- src/config/resolver/axis.ts
- src/config/resolver/shape.ts
#3658
Add missing extend modules
> fix(radar): Fix working on esm

- src/ChartInternal/internals/legend.ts
- test/internals/legend-spec.ts
#3662
Make legend title to use data.names values if specified.
> fix(legend): Fix legend title to show data.names if set

- .husky/commit-msg
- .husky/pre-commit
- .husky/pre-push
#3617
Add shell definition and run husky.sh command at the top to work on windows environment
> chore(husky): Add shell info to pre hooks

- types/options.shape.d.ts
#3697
Add definition for arc.needle.value
> fix(types): Add missing arc.needle.value

- src/Chart/api/regions.ts
- types/options.d.ts
#3732
- Add type definition
- Add on API example code
> fix(region): Add missing region.label option

- src/ChartInternal/data/data.ts
- src/ChartInternal/interactions/eventrect.ts
- src/ChartInternal/shape/point.ts
- src/module/util.ts
- test/api/load-spec.ts
- test/assets/module/util.ts
#3740
- Fix circle selector, where mismatch detection of scatter/bubble type
- Rename isboolean -> isBoolean util function name
- Split event binding call for singleX and multipleX
> fix(api): Fix scatter type loading

- package.json
- yarn.lock
#3750 #3751 #3752
update dependencies to the latest
> chore(deps-dev): update dependency

- src/ChartInternal/interactions/interaction.ts
- test/shape/treemap-spec.ts
#3766
Pass element argument for data.onover/out callback
> fix(treemap): Fix missing element arg on data.onover/out

- demo/types/types.js
- src/ChartInternal/data/load.ts
- src/ChartInternal/shape/funnel.ts
- test/shape/funnel-spec.ts
#3787
- Fix incorrect path with padding option
- Fix incorrect path generation on unload
> fix(funnel): Fix padding and unload

- src/ChartInternal/interactions/zoom.ts
#3857
update the use of navigator object from window
> refactor(zoom): navigator to be referenced from window

- package.json
remove unnecessary script command
> chore: remove unnecessary script

- src/ChartInternal/Axis/AxisRendererHelper.ts
#3882
Fix param type to not be optional
> refactor(axis): Clarify param and types

- src/ChartInternal/interactions/eventrect.ts
- src/ChartInternal/shape/arc.ts
- src/ChartInternal/shape/funnel.ts
- src/ChartInternal/shape/radar.ts
- src/ChartInternal/shape/treemap.ts
- src/config/Options/interaction/interaction.ts
- test/interactions/interaction-spec.ts
- types/options.d.ts
#3887
Implement onout to keep selected state when is away from chart area
```js
interaction: {
onout: false
}
```
> feat(interaction): Intent to ship interaction.onout

- src/module/util.ts
#3854
update media feature detection for mouse and touch detection
> fix(input): Fix touch/mouse input detection

- src/ChartInternal/interactions/eventrect.ts
- test/shape/point-spec.ts
#3900
- prevent getting attribute value from undefined value
- treat point.senstivity correctly
> fix(point): fix sensitivity error when blank area is clicked

- src/ChartInternal/shape/bar.ts
- test/shape/bar-spec.ts
#3903
clip-path style should be updated according the data toggles
> refactor(bar): handle clip-path updates

- src/ChartInternal/interactions/eventrect.ts
- src/ChartInternal/shape/point.ts
remove duplicated code and get point sensitivity value from same method
> refactor(point): remove duplication getting sensitivity value

- src/ChartInternal/data/data.ts
- src/ChartInternal/internals/tooltip.ts
- src/module/util.ts
- test/interactions/viewbox-spec.ts
#3917
- Fix coordinate value translating SVG to DOM
- Adjust tooltip position by its type
> fix(tooltip): Fix tooltip position on viewBox resizing

- src/ChartInternal/Axis/Axis.ts
- src/ChartInternal/interactions/subchart.ts
- src/ChartInternal/interactions/zoom.ts
- src/config/Options/axis/x.ts
- test/interactions/drag-spec.ts
- types/axis.d.ts
#3768
Make axis.x.extent option to limit dragging area for zoom drag
> fix(axis): Fix x axis extent to work

- src/ChartInternal/data/data.ts
- src/ChartInternal/interactions/interaction.ts
- test/interactions/viewbox-spec.ts
#3925
Fix the event target on viewBox svg -> eventRect element
> fix(tooltip): Fix tooltip interaction on viewBox

- src/ChartInternal/Axis/Axis.ts
- test/internals/axis-spec.ts
#3948
- Move tooltip element to be appended at the last position of axis
- Do not generate node if isn't shown
> fix(axis): Fix axis tooltip visibility

- src/ChartInternal/Axis/Axis.ts
- test/api/flow-spec.ts
- test/api/zoom-spec.ts
- test/interactions/zoom-spec.ts
- test/internals/axis-spec.ts
#3951
Generate axis label node when is necessary only
> refactor(axis): Efficiently generate axis label node

- src/ChartInternal/interactions/interaction.ts
- types/chart.d.ts
#3969
- Add missing definition for circles & needle element
- Simplify condition for arc data selection
> fix(types): update type definitions for elements

- src/ChartInternal/data/data.ts
- src/ChartInternal/internals/text.ts
- src/ChartInternal/shape/bar.ts
- src/ChartInternal/shape/candlestick.ts
- src/ChartInternal/shape/funnel.ts
- src/ChartInternal/shape/line.ts
- src/ChartInternal/shape/point.ts
- src/ChartInternal/shape/radar.ts
- src/ChartInternal/shape/treemap.ts
- test/interactions/interaction-spec.ts
- test/internals/axis-spec.ts
- test/internals/data-spec.ts
- test/shape/area-range-spec.ts
#3973
Filter nullish data to be exclude on rendering & generation
> fix(data): Filter nullish data from rendering

- src/ChartInternal/internals/domain.ts
- test/internals/domain-spec.ts
#3985
Prevent domain value to return NaN value when result is returning Infinite value
> fix(domain): handle NaN values in data label calculations

- src/ChartInternal/data/convert.ts
- src/ChartInternal/data/data.ts
- src/ChartInternal/shape/arc.ts
optimize data processing and improve number handling
> refactor(data): optimize data key extraction and improve category checking logic

- src/ChartInternal/data/convert.ts
to reduce complexity, split set of xs values from .convertDataToTargets()
> refactor(convert): split setXs function
